/* Po polsku - lesson data: A1
   Registered onto window.PP_LEVELS by index.html (loaded in order).
   Safe to edit this file alone; a syntax error here shows a load
   message instead of breaking the app engine. */
(function(){
  window.PP_LEVELS = window.PP_LEVELS || [];
  window.PP_LEVELS.push(
  {
      level: "A1",
      blurb: "Survival basics",
      topics: [
        {
          name: "Pierwsze zwroty",
          emoji: "👋",
          desc: "Greetings and the phrases you need in week one",
          cards: [
            { pl:"Dzień dobry", en:"Good morning / Hello", hint:"Formal - use any time of day until evening.", ex:"Dzień dobry, poproszę bilet.", exEn:"Hello, one ticket please." },
            { pl:"Dobry wieczór", en:"Good evening", hint:"Swap in for dzień dobry once it gets dark.", ex:"Dobry wieczór, stolik dla dwóch osób.", exEn:"Good evening, a table for two." },
            { pl:"Cześć", en:"Hi / Bye", hint:"Informal - for friends, not officials.", ex:"Cześć, dawno się nie widzieliśmy!", exEn:"Hi, long time no see!" },
            { pl:"Do widzenia", en:"Goodbye", hint:"The polite, all-purpose goodbye.", ex:"Do widzenia, do jutra!", exEn:"Goodbye, see you tomorrow!" },
            { pl:"Na razie", en:"See you / Bye for now", hint:"Casual, between friends.", ex:"Na razie, muszę już iść.", exEn:"See you, I have to go now." },
            { pl:"Dziękuję", en:"Thank you", hint:"'Dzięki' is the casual short form.", ex:"Dziękuję za pomoc.", exEn:"Thank you for your help." },
            { pl:"Proszę", en:"Please / Here you go / You're welcome", hint:"One word, several jobs.", ex:"Proszę, to dla ciebie.", exEn:"Here you go, this is for you." },
            { pl:"Przepraszam", en:"Sorry / Excuse me", hint:"Also to get someone's attention.", ex:"Przepraszam, gdzie jest wyjście?", exEn:"Excuse me, where is the exit?" },
            { pl:"Tak / Nie", en:"Yes / No", hint:"The two you'll say most often.", ex:"Tak, poproszę. Nie, dziękuję.", exEn:"Yes, please. No, thank you." },
            { pl:"Nie rozumiem", en:"I don't understand", hint:"Add 'po polsku' for 'in Polish'.", ex:"Przepraszam, nie rozumiem.", exEn:"Sorry, I don't understand." },
            { pl:"Nie wiem", en:"I don't know", hint:"Very handy, very common.", ex:"Nie wiem, gdzie to jest.", exEn:"I don't know where it is." },
            { pl:"Czy mówi pan po angielsku?", en:"Do you speak English?", hint:"To a man. To a woman say 'pani' instead of 'pan'.", ex:"Przepraszam, czy mówi pan po angielsku?", exEn:"Excuse me, do you speak English?" },
            { pl:"Jak masz na imię?", en:"What's your name?", hint:"Informal. Formal: 'Jak się pan/pani nazywa?'", ex:"Cześć, jak masz na imię?", exEn:"Hi, what's your name?" },
            { pl:"Mam na imię...", en:"My name is...", hint:"Follow with your first name.", ex:"Mam na imię Anna.", exEn:"My name is Anna." },
            { pl:"Miło mi", en:"Nice to meet you", hint:"Short and natural when introduced.", ex:"Miło mi cię poznać.", exEn:"Nice to meet you." },
            { pl:"Jak się masz?", en:"How are you?", hint:"Informal. In Poland this is a real question, not a passing hello - ask it when you actually want to know, and expect a real answer. A common reply: 'dobrze' - good.", ex:"Cześć Marek, jak się masz?", exEn:"Hi Marek, how are you?" },
            { pl:"Co słychać?", en:"What's up? / How's it going?", hint:"Casual and friendly. Reply lightly: 'wszystko dobrze' or 'po staremu' (same as always).", ex:"Hej, co słychać u ciebie?", exEn:"Hey, how's it going with you?" },
            { pl:"Co tam?", en:"What's up? (very casual)", hint:"Breezy, among friends - lighter than 'jak się masz?'. Often answered with a shrug: 'nic nowego' (nothing new).", ex:"Co tam, Kasia?", exEn:"What's up, Kasia?" },
            { pl:"Wszystko w porządku", en:"Everything's fine / All good", hint:"Also asked as a question to check on someone.", ex:"Wszystko w porządku, dziękuję.", exEn:"Everything's fine, thanks." },
            { pl:"Poproszę...", en:"I'd like... (ordering)", hint:"Softer than 'chcę'. 'Poproszę kawę' - a coffee, please.", ex:"Poproszę kawę i wodę.", exEn:"A coffee and a water, please." },
            { pl:"Ile to kosztuje?", en:"How much is it?", hint:"Your everyday shopping question.", ex:"Przepraszam, ile to kosztuje?", exEn:"Excuse me, how much is it?" },
            { pl:"Gdzie jest toaleta?", en:"Where is the toilet?", hint:"'Gdzie jest...' = where is... for anything.", ex:"Przepraszam, gdzie jest toaleta?", exEn:"Excuse me, where is the toilet?" },
            { pl:"Nie ma za co", en:"You're welcome / Don't mention it", hint:"The natural reply when someone thanks you.", ex:"Dziękuję! - Nie ma za co.", exEn:"Thank you! - You're welcome." },
            { pl:"Smacznego!", en:"Enjoy your meal!", hint:"Said before eating - by staff, hosts, or anyone at the table.", ex:"Proszę bardzo, smacznego!", exEn:"Here you are, enjoy your meal!" },
            { pl:"Na zdrowie!", en:"Cheers! / Bless you!", hint:"A toast when drinking - and also what you say when someone sneezes.", ex:"Na zdrowie! Za nasze spotkanie!", exEn:"Cheers! To our meeting!" },
            { pl:"Powodzenia!", en:"Good luck!", hint:"For an exam, a trip, anything ahead.", ex:"Powodzenia na egzaminie!", exEn:"Good luck on the exam!" },
            { pl:"Do zobaczenia", en:"See you (soon)", hint:"Warmer than 'do widzenia'; you expect to meet again.", ex:"Dziękuję za dziś, do zobaczenia!", exEn:"Thanks for today, see you!" }
          ]
        },
        {
          name: "Liczby i ceny",
          emoji: "🔢",
          desc: "Numbers, money and paying for things",
          cards: [
            { pl:"jeden", en:"one", hint:"The number 1.", ex:"Poproszę jeden bilet.", exEn:"One ticket, please." },
            { pl:"dwa", en:"two", hint:"The number 2.", ex:"Mam dwa koty.", exEn:"I have two cats." },
            { pl:"trzy", en:"three", hint:"The number 3.", ex:"Trzy kawy poproszę.", exEn:"Three coffees, please." },
            { pl:"cztery", en:"four", hint:"The number 4.", ex:"Stolik na cztery osoby.", exEn:"A table for four." },
            { pl:"pięć", en:"five", hint:"The number 5.", ex:"To kosztuje pięć złotych.", exEn:"It costs five zloty." },
            { pl:"sześć", en:"six", hint:"The number 6.", ex:"Mam sześć jabłek.", exEn:"I have six apples." },
            { pl:"siedem", en:"seven", hint:"The number 7.", ex:"Autobus numer siedem.", exEn:"Bus number seven." },
            { pl:"osiem", en:"eight", hint:"The number 8.", ex:"Pracuję osiem godzin.", exEn:"I work eight hours." },
            { pl:"dziewięć", en:"nine", hint:"The number 9.", ex:"Dziewięć złotych za bilet.", exEn:"Nine zloty for a ticket." },
            { pl:"dziesięć", en:"ten", hint:"The number 10.", ex:"Tramwaj przyjedzie za dziesięć minut.", exEn:"The tram arrives in ten minutes." },
            { pl:"dwadzieścia", en:"twenty", hint:"The number 20.", ex:"To kosztuje dwadzieścia złotych.", exEn:"It costs twenty zloty." },
            { pl:"sto", en:"a hundred", hint:"The number 100.", ex:"Sto złotych, proszę.", exEn:"A hundred zloty, please." },
            { pl:"złoty", en:"zloty (the currency)", hint:"PLN. Plural forms: złote / złotych.", ex:"Płacę pięćdziesiąt złotych.", exEn:"I'm paying fifty zloty." },
            { pl:"grosz", en:"grosz (a penny)", hint:"1/100 of a złoty.", ex:"To kosztuje dwa złote pięćdziesiąt groszy.", exEn:"It costs two zloty fifty." },
            { pl:"Ile płacę?", en:"How much do I pay?", hint:"Ask this at the till.", ex:"Ile płacę za wszystko?", exEn:"How much do I pay for everything?" },
            { pl:"Czy mogę zapłacić kartą?", en:"Can I pay by card?", hint:"Card is accepted almost everywhere.", ex:"Czy mogę zapłacić kartą?", exEn:"Can I pay by card?" },
            { pl:"gotówka", en:"cash", hint:"'gotówką' = in cash.", ex:"Płacę gotówką.", exEn:"I'm paying in cash." },
            { pl:"razem", en:"together / in total", hint:"Useful when splitting or totalling.", ex:"Ile razem?", exEn:"How much in total?" },
            { pl:"reszta", en:"change (money back)", hint:"Feminine noun. 'Reszty nie trzeba' uses the genitive of negation.", ex:"Reszty nie trzeba.", exEn:"Keep the change." },
            { pl:"drogo / tanio", en:"expensive / cheap", hint:"Adverb forms you'll hear a lot.", ex:"To za drogo!", exEn:"That's too expensive!" }
          ]
        },
        {
          name: "W kawiarni",
          emoji: "☕",
          desc: "Ordering coffee, snacks and drinks",
          cards: [
            { pl:"kawa", en:"coffee", hint:"Feminine noun.", ex:"Poproszę kawę z mlekiem.", exEn:"A coffee with milk, please." },
            { pl:"herbata", en:"tea", hint:"Feminine noun.", ex:"Wolę herbatę niż kawę.", exEn:"I prefer tea to coffee." },
            { pl:"woda", en:"water", hint:"gazowana = sparkling, niegazowana = still.", ex:"Poproszę wodę niegazowaną.", exEn:"Still water, please." },
            { pl:"mleko", en:"milk", hint:"Neuter noun.", ex:"Kawa z mlekiem, proszę.", exEn:"Coffee with milk, please." },
            { pl:"cukier", en:"sugar", hint:"Masculine noun.", ex:"Bez cukru, dziękuję.", exEn:"No sugar, thank you." },
            { pl:"sok", en:"juice", hint:"'sok pomarańczowy' = orange juice.", ex:"Poproszę sok pomarańczowy.", exEn:"An orange juice, please." },
            { pl:"ciasto", en:"cake", hint:"A slice = 'kawałek'.", ex:"Kawałek ciasta poproszę.", exEn:"A slice of cake, please." },
            { pl:"kanapka", en:"sandwich", hint:"'z serem' = with cheese.", ex:"Poproszę kanapkę z serem.", exEn:"A cheese sandwich, please." },
            { pl:"Co pan poleca?", en:"What do you recommend?", hint:"To a woman: 'Co pani poleca?'", ex:"Nie wiem, co wybrać. Co pan poleca?", exEn:"I don't know what to pick. What do you recommend?" },
            { pl:"Dla mnie...", en:"For me... (ordering)", hint:"Point and name your choice.", ex:"Dla mnie herbata, proszę.", exEn:"A tea for me, please." },
            { pl:"na wynos", en:"to take away", hint:"'na miejscu' = to have here.", ex:"Na wynos, proszę.", exEn:"To take away, please." },
            { pl:"na miejscu", en:"to have here / dine in", hint:"The opposite of na wynos.", ex:"Na miejscu czy na wynos?", exEn:"To have here or take away?" },
            { pl:"Smacznego!", en:"Enjoy your meal!", hint:"Said before eating - reply the same.", ex:"Smacznego!", exEn:"Enjoy your meal!" },
            { pl:"stolik", en:"table", hint:"Diminutive of 'stół'.", ex:"Czy ten stolik jest wolny?", exEn:"Is this table free?" },
            { pl:"karta / menu", en:"menu", hint:"Both are used.", ex:"Poproszę kartę.", exEn:"The menu, please." },
            { pl:"Czy jest wi-fi?", en:"Is there wi-fi?", hint:"Ask for the 'hasło' - password.", ex:"Przepraszam, czy jest tu wi-fi?", exEn:"Excuse me, is there wi-fi here?" },
            { pl:"gorący / zimny", en:"hot / cold", hint:"Adjectives - endings change by gender.", ex:"Poproszę zimną wodę.", exEn:"Cold water, please." },
            { pl:"duży / mały", en:"big / small", hint:"For sizes.", ex:"Dużą kawę poproszę.", exEn:"A large coffee, please." },
            { pl:"Coś jeszcze?", en:"Anything else?", hint:"What staff often ask you. You'll hear both 'Coś jeszcze?' and 'Jeszcze coś?'.", ex:"Coś jeszcze do picia?", exEn:"Anything else to drink?" },
            { pl:"To wszystko", en:"That's all", hint:"To close your order.", ex:"Nie, dziękuję, to wszystko.", exEn:"No thanks, that's all." }
          ]
        },
        {
          name: "Orientacja",
          emoji: "🧭",
          desc: "Finding your way and asking directions",
          cards: [
            { pl:"Gdzie jest...?", en:"Where is...?", hint:"The key question for anything.", ex:"Gdzie jest apteka?", exEn:"Where is the pharmacy?" },
            { pl:"na lewo", en:"to the left", hint:"For turning use 'w lewo': skręcić w lewo.", ex:"Toaleta jest na lewo.", exEn:"The toilet is to the left." },
            { pl:"na prawo", en:"to the right", hint:"Also 'w prawo'.", ex:"Sklep jest na prawo.", exEn:"The shop is on the right." },
            { pl:"prosto", en:"straight ahead", hint:"Direction, not 'simple' here.", ex:"Proszę iść prosto.", exEn:"Go straight ahead." },
            { pl:"blisko", en:"near / close", hint:"Opposite of daleko.", ex:"To jest bardzo blisko.", exEn:"It's very close." },
            { pl:"daleko", en:"far", hint:"'Czy to daleko?' = Is it far?", ex:"Czy to daleko stąd?", exEn:"Is it far from here?" },
            { pl:"tutaj / tu", en:"here", hint:"Both are common.", ex:"Proszę się zatrzymać tutaj.", exEn:"Please stop here." },
            { pl:"tam", en:"there", hint:"Point as you say it.", ex:"Sklep jest tam.", exEn:"The shop is over there." },
            { pl:"obok", en:"next to / beside", hint:"Followed by the genitive.", ex:"Apteka jest obok banku.", exEn:"The pharmacy is next to the bank." },
            { pl:"za rogiem", en:"around the corner", hint:"'róg' = corner.", ex:"Piekarnia jest za rogiem.", exEn:"The bakery is around the corner." },
            { pl:"ulica", en:"street", hint:"Shortened to 'ul.' in addresses.", ex:"Mieszkam na ulicy Długiej.", exEn:"I live on Długa Street." },
            { pl:"centrum", en:"the centre / downtown", hint:"City centre.", ex:"Idę do centrum.", exEn:"I'm going to the centre." },
            { pl:"sklep", en:"shop", hint:"'sklep spożywczy' = grocery shop.", ex:"Gdzie jest najbliższy sklep?", exEn:"Where's the nearest shop?" },
            { pl:"dworzec", en:"station (train / bus)", hint:"'dworzec kolejowy' = train station.", ex:"Jak dojść na dworzec?", exEn:"How do I get to the station?" },
            { pl:"bank", en:"bank", hint:"'bankomat' = ATM.", ex:"Szukam banku.", exEn:"I'm looking for a bank." },
            { pl:"Jak dojść do...?", en:"How do I get to...? (on foot)", hint:"For walking directions.", ex:"Jak dojść do rynku?", exEn:"How do I get to the market square?" },
            { pl:"mapa", en:"map", hint:"Feminine noun.", ex:"Mam mapę w telefonie.", exEn:"I have a map on my phone." },
            { pl:"skręcić", en:"to turn", pair:"skręcać / skręcić", hint:"'skręcić w prawo/lewo'.", ex:"Proszę skręcić w prawo.", exEn:"Turn right, please." },
            { pl:"róg", en:"corner", hint:"'na rogu' = on the corner.", ex:"Na rogu jest kawiarnia.", exEn:"There's a café on the corner." },
            { pl:"w pobliżu", en:"nearby / in the area", hint:"'niedaleko' works too.", ex:"Czy jest tu w pobliżu bankomat?", exEn:"Is there an ATM nearby?" }
          ]
        },
        {
          name: "O mnie",
          emoji: "🙋",
          desc: "Introducing yourself and getting understood",
          cards: [
            { pl:"Nazywam się...", en:"My name is... (full name)", hint:"Use with your surname.", ex:"Nazywam się Jan Kowalski.", exEn:"My name is Jan Kowalski." },
            { pl:"Jestem z...", en:"I'm from...", hint:"Country takes the genitive.", ex:"Jestem z Hiszpanii.", exEn:"I'm from Spain." },
            { pl:"Mieszkam w...", en:"I live in...", hint:"City takes the locative.", ex:"Mieszkam w Krakowie.", exEn:"I live in Kraków." },
            { pl:"Uczę się polskiego", en:"I'm learning Polish", hint:"'uczyć się' + genitive.", ex:"Uczę się polskiego od roku.", exEn:"I've been learning Polish for a year." },
            { pl:"Pracuję jako...", en:"I work as...", hint:"Add your job after 'jako'.", ex:"Pracuję jako programista.", exEn:"I work as a programmer." },
            { pl:"Mam... lat", en:"I'm ... years old", hint:"'Mam trzydzieści lat.'", ex:"Mam trzydzieści lat.", exEn:"I'm thirty years old." },
            { pl:"Nie mówię dobrze po polsku", en:"I don't speak Polish well", hint:"Buys you patience.", ex:"Przepraszam, nie mówię dobrze po polsku.", exEn:"Sorry, I don't speak Polish well." },
            { pl:"Mówię trochę po polsku", en:"I speak a little Polish", hint:"'trochę' = a little.", ex:"Mówię trochę po polsku.", exEn:"I speak a little Polish." },
            { pl:"Czy może pan powtórzyć?", en:"Can you repeat that?", hint:"To a woman: 'pani'.", ex:"Przepraszam, czy może pan powtórzyć?", exEn:"Sorry, can you repeat that?" },
            { pl:"Proszę mówić wolniej", en:"Please speak more slowly", hint:"A lifesaver early on.", ex:"Proszę mówić wolniej.", exEn:"Please speak more slowly." },
            { pl:"Nie jestem stąd", en:"I'm not from here", hint:"'stąd' = from here.", ex:"Nie jestem stąd, jestem turystą.", exEn:"I'm not from here, I'm a tourist." },
            { pl:"Jak się to pisze?", en:"How do you spell it?", hint:"For names and addresses.", ex:"Jak się pisze pana nazwisko?", exEn:"How do you spell your surname?" },
            { pl:"Mam pytanie", en:"I have a question", hint:"Polite way to start.", ex:"Przepraszam, mam pytanie.", exEn:"Excuse me, I have a question." },
            { pl:"Rozumiem", en:"I understand", hint:"'Nie rozumiem' = I don't.", ex:"Tak, teraz rozumiem.", exEn:"Yes, now I understand." },
            { pl:"Czy może mi pan pomóc?", en:"Can you help me?", hint:"To a woman: 'Czy może mi pani...'", ex:"Przepraszam, czy może mi pan pomóc?", exEn:"Excuse me, can you help me?" },
            { pl:"Skąd pan jest?", en:"Where are you from?", hint:"To a woman: 'Skąd pani jest?'", ex:"A skąd pan jest?", exEn:"And where are you from?" },
            { pl:"mój / moja", en:"my (m / f)", hint:"Agrees with the noun's gender.", ex:"To jest mój telefon.", exEn:"This is my phone." },
            { pl:"Miłego dnia!", en:"Have a nice day!", hint:"Warm way to end a chat.", ex:"Dziękuję, miłego dnia!", exEn:"Thanks, have a nice day!" },
            { pl:"Do zobaczenia", en:"See you (later)", hint:"Friendlier than 'do widzenia'.", ex:"Do zobaczenia jutro.", exEn:"See you tomorrow." },
            { pl:"Nie ma problemu", en:"No problem", hint:"Very common reassurance.", ex:"Nie ma problemu!", exEn:"No problem!" }
          ]
        },
        {
          name: "Poranna rutyna",
          emoji: "⏰",
          desc: "Getting up, showering, getting dressed, and having breakfast",
          cards: [
            { pl:"budzik", en:"alarm clock", hint:"Masculine noun.", ex:"Mój budzik dzwoni o siódmej rano.", exEn:"My alarm clock rings at seven in the morning." },
            { pl:"budzić się", en:"to wake up", pair:"budzić się / obudzić się", hint:"Verb. 'Budzę się' = I wake up.", ex:"Budzę się wcześnie rano.", exEn:"I wake up early in the morning." },
            { pl:"wstawać", en:"to get up", pair:"wstawać / wstać", hint:"Verb. 'Wstaję' = I get up.", ex:"Budzę się o szóstej, ale wstaję o wpół do siódmej.", exEn:"I wake up at six, but I get up at half past six." },
            { pl:"łazienka", en:"bathroom", hint:"Feminine noun.", ex:"Najpierw idę do łazienki.", exEn:"First, I go to the bathroom." },
            { pl:"brać prysznic", en:"to take a shower", pair:"brać / wziąć prysznic", hint:"Verb. 'Biorę prysznic' = I take a shower.", ex:"Rano zazwyczaj biorę szybki prysznic.", exEn:"In the morning, I usually take a quick shower." },
            { pl:"myć zęby", en:"to brush teeth", pair:"myć / umyć zęby", hint:"Literally 'to wash teeth'. 'Myję zęby' = I brush my teeth.", ex:"Po śniadaniu myję zęby.", exEn:"I brush my teeth after breakfast." },
            { pl:"ręcznik", en:"towel", hint:"Masculine noun.", ex:"Gdzie jest mój czysty ręcznik?", exEn:"Where is my clean towel?" },
            { pl:"ubierać się", en:"to get dressed", pair:"ubierać się / ubrać się", hint:"Verb. 'Ubieram się' = I get dressed.", ex:"Biorę prysznic i szybko się ubieram.", exEn:"I take a shower and get dressed quickly." },
            { pl:"ubranie", en:"clothes", hint:"Neuter noun. Often used in singular.", ex:"Zakładam czyste ubranie.", exEn:"I put on clean clothes." },
            { pl:"śniadanie", en:"breakfast", hint:"Neuter noun. 'Na śniadanie' = for breakfast.", ex:"Co jesz na śniadanie?", exEn:"What do you eat for breakfast?" },
            { pl:"robić śniadanie", en:"to make breakfast", pair:"robić / zrobić śniadanie", hint:"Verb. 'Robię' = I make/do.", ex:"Robię śniadanie dla mojej rodziny.", exEn:"I am making breakfast for my family." },
            { pl:"jeść śniadanie", en:"to eat breakfast", pair:"jeść / zjeść śniadanie", hint:"Verb. 'Jem' = I eat.", ex:"Codziennie jem śniadanie w domu.", exEn:"I eat breakfast at home every day." },
            { pl:"Jestem głodny", en:"I am hungry", hint:"A woman says 'Jestem głodna'.", ex:"Rano zawsze jestem bardzo głodny.", exEn:"I am always very hungry in the morning." },
            { pl:"najpierw", en:"first", hint:"Used for sequencing actions.", ex:"Najpierw piję kawę, a potem jem.", exEn:"First I drink coffee, and then I eat." },
            { pl:"potem", en:"then / later", hint:"Used to describe what happens next.", ex:"Jem śniadanie, a potem ubieram się.", exEn:"I eat breakfast, and then I get dressed." },
            { pl:"spieszyć się", en:"to be in a hurry", pair:"spieszyć się (impf only)", hint:"Verb. 'Spieszę się' = I am in a hurry.", ex:"Nie mam czasu na śniadanie, spieszę się do pracy.", exEn:"I don't have time for breakfast, I am in a hurry to work." },
            { pl:"wychodzić z domu", en:"to leave the house", pair:"wychodzić / wyjść z domu", hint:"Verb. 'Wychodzę' = I am leaving.", ex:"Wychodzę z domu o ósmej piętnaście.", exEn:"I leave the house at eight fifteen." }
          ]
        },
        {
          name: "Rodzina i ludzie",
          emoji: "👨‍👩‍👧",
          desc: "Family members and the people in your life",
          cards: [
            { pl:"rodzina", en:"family", hint:"Feminine noun.", ex:"Moja rodzina mieszka daleko.", exEn:"My family lives far away." },
            { pl:"mama", en:"mum", hint:"Everyday word; formal: 'matka'.", ex:"Moja mama świetnie gotuje.", exEn:"My mum cooks really well." },
            { pl:"tata", en:"dad", hint:"Everyday word; formal: 'ojciec'. Masculine despite the -a ending.", ex:"Mój tata pracuje w banku.", exEn:"My dad works at a bank." },
            { pl:"brat", en:"brother", hint:"Plural: 'bracia'.", ex:"Mam starszego brata.", exEn:"I have an older brother." },
            { pl:"siostra", en:"sister", hint:"Plural: 'siostry'.", ex:"Moja siostra ma na imię Ewa.", exEn:"My sister's name is Ewa." },
            { pl:"syn / córka", en:"son / daughter", hint:"The two words for your children.", ex:"Mam syna i córkę.", exEn:"I have a son and a daughter." },
            { pl:"mąż / żona", en:"husband / wife", hint:"'mój mąż', 'moja żona'.", ex:"To jest moja żona, Anna.", exEn:"This is my wife, Anna." },
            { pl:"dziecko / dzieci", en:"child / children", hint:"Irregular plural.", ex:"Czy masz dzieci?", exEn:"Do you have children?" },
            { pl:"babcia", en:"grandma", hint:"Grandfather: 'dziadek'.", ex:"Moja babcia mieszka w Krakowie.", exEn:"My grandma lives in Krakow." },
            { pl:"dziadek", en:"grandpa", hint:"Grandparents together: 'dziadkowie'.", ex:"Mój dziadek ma osiemdziesiąt lat.", exEn:"My grandpa is eighty years old." },
            { pl:"przyjaciel / przyjaciółka", en:"close friend (m / f)", hint:"A close friend; a casual friend is 'znajomy / znajoma'.", ex:"To jest mój przyjaciel Marek.", exEn:"This is my friend Marek." },
            { pl:"znajomy / znajoma", en:"acquaintance / friend (m / f)", hint:"Less intimate than 'przyjaciel'.", ex:"To jest moja znajoma z pracy.", exEn:"This is a friend of mine from work." },
            { pl:"kolega / koleżanka", en:"colleague, mate (m / f)", hint:"From work, school, or the neighbourhood.", ex:"Mój kolega z pracy jest z Ukrainy.", exEn:"My colleague from work is from Ukraine." },
            { pl:"chłopak / dziewczyna", en:"boyfriend / girlfriend", hint:"Also just 'boy / girl' - context decides.", ex:"Moja dziewczyna uczy się polskiego.", exEn:"My girlfriend is learning Polish." },
            { pl:"To jest mój... / moja...", en:"This is my... (m / f)", hint:"'mój' before masculine, 'moja' before feminine nouns.", ex:"To jest mój brat, a to moja siostra.", exEn:"This is my brother, and this is my sister." },
            { pl:"Czy masz rodzeństwo?", en:"Do you have siblings?", hint:"'rodzeństwo' = siblings, used in singular.", ex:"Czy masz rodzeństwo?", exEn:"Do you have siblings?" },
            { pl:"ludzie", en:"people", hint:"Plural only - the singular is 'człowiek'. 'ludzie' is the subject form, but after 'dużo', 'mało', 'kilku', 'wielu' or a negation it becomes 'ludzi': dużo ludzi, nie ma ludzi.", ex:"W parku jest dużo ludzi.", exEn:"There are a lot of people in the park." },
            { pl:"pan / pani", en:"gentleman, sir / lady, madam", hint:"Also how you address strangers politely.", ex:"Ten pan czeka na autobus.", exEn:"That gentleman is waiting for the bus." }
          ]
        },
        {
          name: "Dni i czas",
          emoji: "📅",
          desc: "Days of the week and talking about time",
          cards: [
            { pl:"poniedziałek", en:"Monday", hint:"'w poniedziałek' = on Monday.", ex:"W poniedziałek zaczynam pracę.", exEn:"On Monday I start work." },
            { pl:"wtorek", en:"Tuesday", hint:"'we wtorek' = on Tuesday - note 'we', not 'w'.", ex:"We wtorek mam lekcję polskiego.", exEn:"On Tuesday I have a Polish lesson." },
            { pl:"środa", en:"Wednesday", hint:"'w środę' = on Wednesday. Literally 'the middle' of the week.", ex:"W środę idę na siłownię.", exEn:"On Wednesday I go to the gym." },
            { pl:"czwartek", en:"Thursday", hint:"'w czwartek' = on Thursday. From 'cztery' (four) - the fourth day.", ex:"W czwartek mam spotkanie.", exEn:"On Thursday I have a meeting." },
            { pl:"piątek", en:"Friday", hint:"'w piątek' = on Friday. From 'pięć' (five).", ex:"W piątek wieczorem spotykam się ze znajomymi.", exEn:"On Friday evening I meet up with friends." },
            { pl:"sobota", en:"Saturday", hint:"'w sobotę' = on Saturday.", ex:"W sobotę długo śpię.", exEn:"On Saturday I sleep in." },
            { pl:"niedziela", en:"Sunday", hint:"'w niedzielę' = on Sunday. Most shops in Poland are closed on Sundays.", ex:"W niedzielę sklepy są zamknięte.", exEn:"On Sunday the shops are closed." },
            { pl:"dzień / tydzień", en:"day / week", hint:"'w tym tygodniu' = this week.", ex:"Mam wolny dzień w tym tygodniu.", exEn:"I have a day off this week." },
            { pl:"weekend", en:"weekend", hint:"'w weekend' = at the weekend.", ex:"Co robisz w weekend?", exEn:"What are you doing at the weekend?" },
            { pl:"dziś / dzisiaj", en:"today", hint:"Both forms are common and interchangeable.", ex:"Dzisiaj jest piątek.", exEn:"Today is Friday." },
            { pl:"jutro", en:"tomorrow", hint:"'pojutrze' = the day after tomorrow.", ex:"Jutro mam egzamin.", exEn:"Tomorrow I have an exam." },
            { pl:"wczoraj", en:"yesterday", hint:"'przedwczoraj' = the day before yesterday. Feminine form: byłam.", ex:"Wczoraj byłem w kinie.", exEn:"Yesterday I was at the cinema." },
            { pl:"rano", en:"in the morning", hint:"'jutro rano' = tomorrow morning.", ex:"Rano piję kawę.", exEn:"In the morning I drink coffee." },
            { pl:"po południu", en:"in the afternoon", hint:"Literally 'after noon'.", ex:"Po południu mam czas.", exEn:"In the afternoon I have time." },
            { pl:"wieczorem", en:"in the evening", hint:"'dziś wieczorem' = tonight.", ex:"Wieczorem oglądam serial.", exEn:"In the evening I watch a series." },
            { pl:"w nocy", en:"at night", hint:"'dobranoc' = good night.", ex:"W nocy dobrze śpię.", exEn:"At night I sleep well." },
            { pl:"godzina", en:"hour / o'clock", hint:"'pół godziny' = half an hour.", ex:"Lekcja trwa jedną godzinę.", exEn:"The lesson lasts one hour." },
            { pl:"O której godzinie?", en:"At what time?", hint:"The key question for appointments.", ex:"O której godzinie zaczynamy?", exEn:"At what time do we start?" },
            { pl:"o siódmej / o ósmej", en:"at seven / at eight", hint:"Times use ordinal numbers: o siódmej, o ósmej, o dziewiątej.", ex:"Wstaję o siódmej rano.", exEn:"I get up at seven in the morning." },
            { pl:"Która jest godzina?", en:"What time is it?", hint:"The everyday way to ask for the time.", ex:"Przepraszam, która jest godzina?", exEn:"Excuse me, what time is it?" },
            { pl:"teraz / później", en:"now / later", hint:"Two words you will use constantly.", ex:"Teraz pracuję, porozmawiamy później.", exEn:"I'm working now, we'll talk later." },
            { pl:"zawsze / nigdy", en:"always / never", hint:"'nigdy' pairs with 'nie': nigdy nie mam czasu.", ex:"Zawsze jem śniadanie, ale nigdy nie jem kolacji.", exEn:"I always eat breakfast, but I never eat supper." }
          ]
        },
        {
          name: "Miesiące i pory roku",
          emoji: "🍂",
          desc: "Months, seasons, and saying when something happens",
          cards: [
            { pl:"styczeń", en:"January", hint:"'w styczniu' = in January.", ex:"W styczniu jest bardzo zimno.", exEn:"In January it is very cold." },
            { pl:"luty", en:"February", hint:"'w lutym' = in February.", ex:"W lutym często pada śnieg.", exEn:"In February it often snows." },
            { pl:"marzec", en:"March", hint:"'w marcu' = in March.", ex:"W marcu zaczyna się wiosna.", exEn:"In March spring begins." },
            { pl:"kwiecień", en:"April", hint:"'w kwietniu' = in April. From 'kwiat' (flower).", ex:"W kwietniu wszystko kwitnie.", exEn:"In April everything is in bloom." },
            { pl:"maj", en:"May", hint:"'w maju' = in May. The long weekend 'majówka' starts the month.", ex:"W maju jest piękna pogoda.", exEn:"In May the weather is beautiful." },
            { pl:"czerwiec", en:"June", hint:"'w czerwcu' = in June.", ex:"W czerwcu kończy się szkoła.", exEn:"In June school ends." },
            { pl:"lipiec", en:"July", hint:"'w lipcu' = in July. From 'lipa' (linden tree).", ex:"W lipcu mam urlop.", exEn:"In July I have vacation." },
            { pl:"sierpień", en:"August", hint:"'w sierpniu' = in August.", ex:"W sierpniu jadę nad morze.", exEn:"In August I am going to the seaside." },
            { pl:"wrzesień", en:"September", hint:"'we wrześniu' = in September - note 'we'.", ex:"We wrześniu dzieci wracają do szkoły.", exEn:"In September children go back to school." },
            { pl:"październik", en:"October", hint:"'w październiku' = in October.", ex:"W październiku zaczynają się zajęcia na uczelni.", exEn:"In October university classes begin." },
            { pl:"listopad", en:"November", hint:"'w listopadzie' = in November. From 'liść' (leaf) - leaves falling.", ex:"W listopadzie jest szaro i zimno.", exEn:"In November it is grey and cold." },
            { pl:"grudzień", en:"December", hint:"'w grudniu' = in December.", ex:"W grudniu są święta.", exEn:"In December there are the holidays." },
            { pl:"miesiąc", en:"month", hint:"'w tym miesiącu' = this month; 'za miesiąc' = in a month.", ex:"Mieszkam tu od trzech miesięcy.", exEn:"I have lived here for three months." },
            { pl:"rok", en:"year", hint:"'w tym roku' = this year. Plural: lata.", ex:"Uczę się polskiego od roku.", exEn:"I have been learning Polish for a year." },
            { pl:"wiosna", en:"spring", hint:"'wiosną' or 'na wiosnę' = in spring.", ex:"Wiosną dni są coraz dłuższe.", exEn:"In spring the days get longer and longer." },
            { pl:"lato", en:"summer", hint:"'latem' = in summer. Also the plural of 'rok' (lata = years).", ex:"Latem jeżdżę nad jezioro.", exEn:"In summer I go to the lake." },
            { pl:"jesień", en:"autumn", hint:"'jesienią' = in autumn.", ex:"Jesienią często pada deszcz.", exEn:"In autumn it often rains." },
            { pl:"zima", en:"winter", hint:"'zimą' or 'w zimie' = in winter.", ex:"Zimą wcześnie robi się ciemno.", exEn:"In winter it gets dark early." },
            { pl:"Kiedy?", en:"When?", hint:"The question word for time.", ex:"Kiedy masz urodziny?", exEn:"When is your birthday?" },
            { pl:"urodziny", en:"birthday", hint:"Plural only. 'Wszystkiego najlepszego!' = happy birthday!", ex:"Moje urodziny są w maju.", exEn:"My birthday is in May." }
          ]
        },
        {
          name: "Jedzenie - podstawy",
          emoji: "🍞",
          desc: "Basic food words and saying what you like",
          cards: [
            { pl:"chleb", en:"bread", hint:"Masculine noun. 'kromka chleba' = a slice of bread.", ex:"Kupuję świeży chleb w piekarni.", exEn:"I buy fresh bread at the bakery." },
            { pl:"bułka", en:"bread roll", hint:"Feminine noun. A breakfast staple in Poland.", ex:"Na śniadanie jem bułkę z masłem.", exEn:"For breakfast I eat a roll with butter." },
            { pl:"masło", en:"butter", hint:"Neuter noun.", ex:"Poproszę chleb i masło.", exEn:"Bread and butter, please." },
            { pl:"ser", en:"cheese", hint:"'ser żółty' = hard cheese, 'biały ser' = curd cheese.", ex:"Lubię kanapki z serem.", exEn:"I like cheese sandwiches." },
            { pl:"jajko", en:"egg", hint:"Neuter noun. Plural: 'jajka'.", ex:"Na śniadanie jem dwa jajka.", exEn:"For breakfast I eat two eggs." },
            { pl:"szynka", en:"ham", hint:"Feminine noun.", ex:"Poproszę kanapkę z szynką.", exEn:"A ham sandwich, please." },
            { pl:"mięso", en:"meat", hint:"Neuter noun. 'kurczak' = chicken, 'wieprzowina' = pork.", ex:"Nie jem mięsa.", exEn:"I don't eat meat." },
            { pl:"kurczak", en:"chicken", hint:"Masculine noun.", ex:"Na obiad jest kurczak z ryżem.", exEn:"For lunch there is chicken with rice." },
            { pl:"ryba", en:"fish", hint:"Feminine noun.", ex:"W piątek często jem rybę.", exEn:"On Friday I often eat fish." },
            { pl:"warzywa", en:"vegetables", hint:"Plural noun. Singular: 'warzywo'.", ex:"Kupuję warzywa na targu.", exEn:"I buy vegetables at the market." },
            { pl:"owoce", en:"fruit", hint:"Plural noun. Singular: 'owoc'.", ex:"Jem dużo owoców latem.", exEn:"I eat a lot of fruit in summer." },
            { pl:"jabłko", en:"apple", hint:"Neuter noun. Poland is famous for its apples.", ex:"Codziennie jem jedno jabłko.", exEn:"Every day I eat one apple." },
            { pl:"pomidor", en:"tomato", hint:"Masculine noun. 'zupa pomidorowa' = tomato soup.", ex:"Do kanapki dodaję pomidora.", exEn:"I add a tomato to my sandwich." },
            { pl:"ziemniaki", en:"potatoes", hint:"Plural of 'ziemniak'. A staple of Polish dinners.", ex:"Na obiad są ziemniaki i kotlet.", exEn:"For lunch there are potatoes and a cutlet." },
            { pl:"ryż / makaron", en:"rice / pasta", hint:"The two most common alternatives to potatoes.", ex:"Wolę makaron niż ryż.", exEn:"I prefer pasta to rice." },
            { pl:"zupa", en:"soup", hint:"Feminine noun. Poles often start lunch with soup.", ex:"Na początek poproszę zupę.", exEn:"To start, I'd like soup." },
            { pl:"obiad", en:"lunch / dinner (main meal)", hint:"The main meal of the day, usually early afternoon.", ex:"Obiad jem zazwyczaj o czternastej.", exEn:"I usually eat lunch at two p.m." },
            { pl:"kolacja", en:"supper / evening meal", hint:"A lighter evening meal.", ex:"Na kolację jem kanapki.", exEn:"For supper I eat sandwiches." },
            { pl:"lubię / nie lubię", en:"I like / I don't like", hint:"'lubić' + accusative: lubię kawę, nie lubię herbaty.", ex:"Lubię pierogi, ale nie lubię ryb.", exEn:"I like pierogi, but I don't like fish." },
            { pl:"smaczny", en:"tasty", hint:"'To jest bardzo smaczne!' = this is very tasty!", ex:"Ta zupa jest bardzo smaczna.", exEn:"This soup is very tasty." },
            { pl:"głodny / chce mi się pić", en:"hungry / I'm thirsty", hint:"A woman says 'głodna'. For thirst Polish uses 'chce mi się pić' - the adjective 'spragniony' is bookish.", ex:"Jestem głodny i chce mi się pić.", exEn:"I am hungry and thirsty." }
          ]
        },
        {
          name: "Pogoda dzisiaj",
          emoji: "🌤️",
          desc: "Everyday weather talk and small-talk openers",
          cards: [
            { pl:"Jaka jest pogoda?", en:"What's the weather like?", hint:"The basic weather question.", ex:"Jaka dzisiaj jest pogoda?", exEn:"What's the weather like today?" },
            { pl:"Pada deszcz", en:"It's raining", hint:"Often just 'pada'.", ex:"Weź parasol, pada deszcz.", exEn:"Take an umbrella, it's raining." },
            { pl:"Pada śnieg", en:"It's snowing", hint:"Same verb 'padać' as for rain.", ex:"Zimą często pada śnieg.", exEn:"In winter it often snows." },
            { pl:"Świeci słońce", en:"The sun is shining", hint:"'słonecznie' = sunny.", ex:"Dzisiaj świeci słońce.", exEn:"Today the sun is shining." },
            { pl:"Jest zimno", en:"It's cold", hint:"'Jest mi zimno' = I am cold.", ex:"Dzisiaj jest bardzo zimno.", exEn:"Today it is very cold." },
            { pl:"Jest ciepło", en:"It's warm", hint:"'Jest gorąco' = it's hot.", ex:"Na dworze jest ciepło.", exEn:"It is warm outside." },
            { pl:"Jest gorąco", en:"It's hot", hint:"For real summer heat.", ex:"W lipcu jest bardzo gorąco.", exEn:"In July it is very hot." },
            { pl:"Wieje wiatr", en:"The wind is blowing", hint:"'wietrznie' = windy.", ex:"Nad morzem zawsze wieje wiatr.", exEn:"At the seaside the wind is always blowing." },
            { pl:"Jest pochmurno", en:"It's cloudy", hint:"'chmura' = a cloud.", ex:"Dzisiaj jest pochmurno i szaro.", exEn:"Today it is cloudy and grey." },
            { pl:"mgła", en:"fog", hint:"Feminine noun. 'Jest mgła' = it's foggy.", ex:"Rano była gęsta mgła.", exEn:"In the morning there was thick fog." },
            { pl:"stopnie", en:"degrees", hint:"'pięć stopni' = five degrees; 'minus pięć' below zero.", ex:"Dzisiaj jest dziesięć stopni.", exEn:"Today it is ten degrees." },
            { pl:"prognoza pogody", en:"weather forecast", hint:"Check it before a trip: 'sprawdzić prognozę'.", ex:"Sprawdzam prognozę pogody na jutro.", exEn:"I'm checking the weather forecast for tomorrow." },
            { pl:"parasol", en:"umbrella", hint:"Masculine noun. Feminine form: zapomniałam.", ex:"Zapomniałem parasola.", exEn:"I forgot my umbrella." },
            { pl:"Ale ładna pogoda!", en:"What lovely weather!", hint:"'Ale...' = what a...! Great small talk.", ex:"Ale ładna dzisiaj pogoda!", exEn:"What lovely weather today!" },
            { pl:"Ale brzydka pogoda!", en:"What awful weather!", hint:"The other half of Polish small talk.", ex:"Ale brzydka pogoda, cały dzień pada.", exEn:"What awful weather, it's been raining all day." },
            { pl:"Zimno dzisiaj, prawda?", en:"Cold today, isn't it?", hint:"'prawda?' turns anything into small talk.", ex:"Zimno dzisiaj, prawda?", exEn:"Cold today, isn't it?" },
            { pl:"Podobno będzie padać", en:"Apparently it's going to rain", hint:"'podobno' = apparently / they say.", ex:"Podobno jutro będzie padać.", exEn:"Apparently it's going to rain tomorrow." }
          ]
        },
        {
          name: "Pierwsze czasowniki",
          emoji: "🏃",
          desc: "The twenty survival verbs you need first",
          cards: [
            { pl:"być", en:"to be", hint:"Irregular: jestem, jesteś, jest, jesteśmy, jesteście, są.", ex:"Jestem z Hiszpanii.", exEn:"I am from Spain." },
            { pl:"mieć", en:"to have", pair:"mieć (impf only)", hint:"mam, masz, ma. 'Mam pytanie' = I have a question.", ex:"Mam dwa koty i psa.", exEn:"I have two cats and a dog." },
            { pl:"chcieć", en:"to want", pair:"chcieć / zechcieć", hint:"chcę, chcesz, chce. Softer: 'chciałbym' = I would like.", ex:"Chcę mówić po polsku.", exEn:"I want to speak Polish." },
            { pl:"móc", en:"can / to be able to", pair:"móc (impf only)", hint:"mogę, możesz, może. 'Czy mogę...?' = may I...?", ex:"Czy mogę tu usiąść?", exEn:"Can I sit here?" },
            { pl:"musieć", en:"must / to have to", pair:"musieć (impf only)", hint:"muszę, musisz, musi.", ex:"Muszę już iść.", exEn:"I have to go now." },
            { pl:"iść", en:"to go (on foot, now)", pair:"iść / pójść", hint:"idę, idziesz, idzie. For walking somewhere right now.", ex:"Idę do sklepu.", exEn:"I am going to the shop." },
            { pl:"jechać", en:"to go (by vehicle, now)", pair:"jechać / pojechać", hint:"jadę, jedziesz, jedzie. For any transport.", ex:"Jadę tramwajem do centrum.", exEn:"I am going to the centre by tram." },
            { pl:"robić", en:"to do / to make", pair:"robić / zrobić", hint:"robię, robisz, robi. 'Co robisz?' = what are you doing?", ex:"Co robisz w weekend?", exEn:"What are you doing at the weekend?" },
            { pl:"mówić", en:"to speak / to say", pair:"mówić / powiedzieć", hint:"mówię, mówisz, mówi. 'Mówię po polsku' = I speak Polish.", ex:"Mówię trochę po polsku.", exEn:"I speak a little Polish." },
            { pl:"rozumieć", en:"to understand", pair:"rozumieć / zrozumieć", hint:"rozumiem, rozumiesz, rozumie.", ex:"Rozumiem, ale proszę mówić wolniej.", exEn:"I understand, but please speak more slowly." },
            { pl:"wiedzieć", en:"to know (a fact)", pair:"wiedzieć (impf only)", hint:"wiem, wiesz, wie. For facts; for people and places use 'znać'.", ex:"Nie wiem, gdzie to jest.", exEn:"I don't know where it is." },
            { pl:"znać", en:"to know (a person, place)", pair:"znać / poznać", hint:"znam, znasz, zna. 'Znam Warszawę' = I know Warsaw.", ex:"Czy znasz tę restaurację?", exEn:"Do you know this restaurant?" },
            { pl:"jeść", en:"to eat", pair:"jeść / zjeść", hint:"jem, jesz, je. Irregular but essential.", ex:"Co jesz na śniadanie?", exEn:"What do you eat for breakfast?" },
            { pl:"pić", en:"to drink", pair:"pić / wypić", hint:"piję, pijesz, pije.", ex:"Piję dużo wody.", exEn:"I drink a lot of water." },
            { pl:"kupować", en:"to buy", pair:"kupować / kupić", hint:"kupuję, kupujesz. Perfective 'kupić' for a single purchase.", ex:"Kupuję bilet w aplikacji.", exEn:"I buy a ticket in the app." },
            { pl:"mieszkać", en:"to live (reside)", pair:"mieszkać / zamieszkać", hint:"mieszkam, mieszkasz. 'Gdzie mieszkasz?' = where do you live?", ex:"Mieszkam w Warszawie od roku.", exEn:"I have lived in Warsaw for a year." },
            { pl:"pracować", en:"to work", pair:"pracować (impf only)", hint:"pracuję, pracujesz.", ex:"Pracuję w biurze w centrum.", exEn:"I work in an office in the centre." },
            { pl:"lubić", en:"to like", pair:"lubić / polubić", hint:"lubię, lubisz. Takes accusative: lubię kawę.", ex:"Lubię polskie jedzenie.", exEn:"I like Polish food." },
            { pl:"kochać", en:"to love", pair:"kochać / pokochać", hint:"kocham, kochasz. 'Kocham cię' = I love you.", ex:"Kocham to miasto.", exEn:"I love this city." },
            { pl:"szukać", en:"to look for", pair:"szukać / poszukać", hint:"szukam, szukasz. Takes genitive: szukam pracy.", ex:"Szukam dobrej kawiarni.", exEn:"I am looking for a good café." },
            { pl:"czekać", en:"to wait", pair:"czekać / poczekać", hint:"czekam, czekasz. 'Czekam na...' + accusative.", ex:"Czekam na autobus.", exEn:"I am waiting for the bus." },
            { pl:"pomagać", en:"to help", pair:"pomagać / pomóc", hint:"pomagam, pomagasz. Takes dative: pomagam mamie.", ex:"Czy mogę ci pomóc?", exEn:"Can I help you?" }
          ]
        }
      ]
    }
  );
})();
