/* Po polsku - lesson data: A2
   Registered onto window.PP_LEVELS by index.html (loaded in order).
   Safe to edit this file alone; a syntax error here shows a load
   message instead of breaking the app engine. */
(function(){
  window.PP_LEVELS = window.PP_LEVELS || [];
  window.PP_LEVELS.push(
  {
      level: "A2",
      blurb: "Living in Poland",
      topics: [
        {
          name: "Komunikacja miejska",
          emoji: "🚋",
          desc: "Trams, buses, tickets and getting around",
          cards: [
            { pl:"przystanek", en:"stop (bus / tram)", hint:"Masculine noun.", ex:"Wysiadam na następnym przystanku.", exEn:"I'm getting off at the next stop." },
            { pl:"bilet", en:"ticket", hint:"jednorazowy = single, czasowy = time-based.", ex:"Kupiłem bilet w automacie.", exEn:"I bought a ticket at the machine." },
            { pl:"Poproszę bilet 20-minutowy", en:"A 20-minute ticket, please", hint:"Many Polish cities sell time-based tickets, not per-ride.", ex:"Dzień dobry, poproszę bilet 20-minutowy.", exEn:"Hello, a 20-minute ticket, please." },
            { pl:"Czy ten tramwaj jedzie do centrum?", en:"Does this tram go to the centre?", hint:"Swap 'tramwaj' for 'autobus' for a bus.", ex:"Przepraszam, czy ten tramwaj jedzie do centrum?", exEn:"Excuse me, does this tram go to the centre?" },
            { pl:"Który autobus jedzie na dworzec?", en:"Which bus goes to the station?", hint:"Swap 'dworzec' for any destination.", ex:"Przepraszam, który autobus jedzie na dworzec?", exEn:"Excuse me, which bus goes to the station?" },
            { pl:"Gdzie mam wysiąść?", en:"Where should I get off?", hint:"Ask the driver or a fellow passenger.", ex:"Gdzie mam wysiąść na dworzec?", exEn:"Where should I get off for the station?" },
            { pl:"Następny przystanek", en:"Next stop", hint:"You'll hear this announced on board.", ex:"Następny przystanek: Rynek.", exEn:"Next stop: the Main Square." },
            { pl:"Przepraszam, wysiadam", en:"Excuse me, I'm getting off", hint:"Say it to move toward the door.", ex:"Przepraszam, wysiadam na następnym.", exEn:"Excuse me, I'm getting off at the next one." },
            { pl:"Czy mogę przejść?", en:"Can I get through?", hint:"For a crowded tram or bus.", ex:"Przepraszam, czy mogę przejść?", exEn:"Excuse me, can I get through?" },
            { pl:"metro", en:"metro / underground", hint:"Only Warsaw has a metro - other cities rely on trams and buses.", ex:"Codziennie jadę metrem do pracy.", exEn:"I take the metro to work every day." },
            { pl:"Muszę się przesiąść", en:"I have to change lines", hint:"'przesiadka' = a transfer.", ex:"Muszę się przesiąść na inny tramwaj.", exEn:"I have to change to another tram." },
            { pl:"Czy muszę skasować bilet?", en:"Do I need to validate the ticket?", hint:"'kasownik' = the validator machine.", ex:"Przepraszam, czy muszę skasować bilet?", exEn:"Excuse me, do I need to validate the ticket?" },
            { pl:"Tramwaj ma opóźnienie", en:"The tram is delayed", hint:"'opóźnienie' = delay.", ex:"Mój tramwaj ma dziś opóźnienie.", exEn:"My tram is delayed today." },
            { pl:"rozkład jazdy", en:"timetable", hint:"Posted at every stop and in the app.", ex:"Sprawdzam rozkład jazdy w aplikacji.", exEn:"I'm checking the timetable in the app." },
            { pl:"Kiedy jest następny autobus?", en:"When is the next bus?", hint:"Or check the countdown on the stop sign.", ex:"Przepraszam, kiedy jest następny autobus?", exEn:"Excuse me, when is the next bus?" },
            { pl:"Bilet miesięczny", en:"Monthly ticket", hint:"Cheaper if you travel daily.", ex:"Mam bilet miesięczny na metro.", exEn:"I have a monthly ticket for the metro." },
            { pl:"Wsiadam / Wysiadam", en:"I'm getting on / getting off", hint:"The verb pair you'll use most.", ex:"Wsiadam do tramwaju numer 10.", exEn:"I get on tram number 10." },
            { pl:"peron", en:"platform", hint:"For the metro and rail stations.", ex:"Pociąg odjeżdża z peronu drugiego.", exEn:"The train leaves from platform two." },
            { pl:"Czy to jest dobry kierunek?", en:"Is this the right direction?", hint:"Handy when you're unsure which way.", ex:"Przepraszam, czy to jest dobry kierunek na centrum?", exEn:"Excuse me, is this the right direction for the centre?" },
            { pl:"Zgubiłem się", en:"I'm lost", hint:"A woman says 'zgubiłam się'.", ex:"Chyba się zgubiłem, gdzie jest przystanek?", exEn:"I think I'm lost, where's the stop?" },
            { pl:"przystanek na żądanie", en:"request stop", hint:"The bus/tram stops only if you signal - press the button inside, or wave it down from the stop.", ex:"To przystanek na żądanie, naciśnij guzik.", exEn:"It's a request stop, press the button." },
            { pl:"Uwaga, zmiana trasy", en:"Attention, the route has changed", hint:"You'll hear this during roadworks or events. 'objazd' = a detour.", ex:"Uwaga, zmiana trasy z powodu remontu.", exEn:"Attention, route change due to roadworks." },
            { pl:"przystanek końcowy", en:"the last stop / terminus", hint:"Everyone gets off here. Also announced as 'stacja końcowa' on the metro.", ex:"Przystanek końcowy, proszę wysiadać.", exEn:"Last stop, everyone please get off." }
          ]
        },
        {
          name: "W aptece",
          emoji: "💊",
          desc: "The pharmacy: symptoms and medicine",
          cards: [
            { pl:"apteka", en:"pharmacy", hint:"'apteka całodobowa' = 24-hour pharmacy.", ex:"Gdzie jest najbliższa apteka?", exEn:"Where's the nearest pharmacy?" },
            { pl:"lek / lekarstwo", en:"medicine", hint:"Both mean medicine.", ex:"Potrzebuję leku na gardło.", exEn:"I need medicine for my throat." },
            { pl:"recepta", en:"prescription", hint:"'na receptę' = prescription-only.", ex:"Czy to jest na receptę?", exEn:"Is this prescription-only?" },
            { pl:"bez recepty", en:"over the counter", hint:"No prescription needed.", ex:"Czy dostanę to bez recepty?", exEn:"Can I get this without a prescription?" },
            { pl:"Mam receptę", en:"I have a prescription", hint:"Say this at the counter. Polish e-prescriptions come as a 4-digit code (kod) plus your PESEL - just read it out.", ex:"Dzień dobry, mam receptę - kod to 1234.", exEn:"Hello, I have a prescription - the code is 1234." },
            { pl:"Coś na ból głowy", en:"Something for a headache", hint:"'coś na...' = something for...", ex:"Poproszę coś na ból głowy.", exEn:"Something for a headache, please." },
            { pl:"ból gardła", en:"sore throat", hint:"'ból' = pain / ache.", ex:"Mam ból gardła od wczoraj.", exEn:"I've had a sore throat since yesterday." },
            { pl:"gorączka", en:"fever", hint:"'Mam gorączkę' = I have a fever.", ex:"Mam gorączkę i boli mnie głowa.", exEn:"I have a fever and a headache." },
            { pl:"przeziębienie", en:"a cold", hint:"'jestem przeziębiony/a' = I have a cold.", ex:"Chyba mam przeziębienie.", exEn:"I think I have a cold." },
            { pl:"kaszel", en:"cough", hint:"'suchy' = dry, 'mokry' = chesty.", ex:"Mam suchy kaszel.", exEn:"I have a dry cough." },
            { pl:"katar", en:"runny / blocked nose", hint:"Very common word in winter.", ex:"Mam katar i kaszel.", exEn:"I have a runny nose and a cough." },
            { pl:"tabletki", en:"tablets / pills", hint:"Singular: 'tabletka'.", ex:"Ile tabletek dziennie?", exEn:"How many tablets a day?" },
            { pl:"syrop", en:"syrup", hint:"'syrop na kaszel' = cough syrup.", ex:"Poproszę syrop na kaszel.", exEn:"Cough syrup, please." },
            { pl:"plaster", en:"plaster / band-aid", hint:"Plural: 'plastry'.", ex:"Czy ma pan plastry?", exEn:"Do you have any plasters?" },
            { pl:"Boli mnie...", en:"My ... hurts", hint:"'Boli mnie głowa/brzuch'.", ex:"Boli mnie brzuch.", exEn:"My stomach hurts." },
            { pl:"Jak często?", en:"How often?", hint:"For dosing questions.", ex:"Jak często brać ten lek?", exEn:"How often should I take this medicine?" },
            { pl:"po jedzeniu", en:"after meals", hint:"'przed jedzeniem' = before meals.", ex:"Brać po jedzeniu.", exEn:"Take after meals." },
            { pl:"dawka", en:"dose", hint:"Feminine noun.", ex:"Jaka jest dawka dla dorosłych?", exEn:"What's the dose for adults?" },
            { pl:"Czy to jest bezpieczne?", en:"Is it safe?", hint:"Good to ask about side effects.", ex:"Czy to jest bezpieczne dla dzieci?", exEn:"Is it safe for children?" },
            { pl:"antybiotyk", en:"antibiotic", hint:"Always prescription-only in Poland.", ex:"Czy potrzebuję antybiotyku?", exEn:"Do I need an antibiotic?" },
            { pl:"Poproszę o paragon", en:"A receipt, please", hint:"Useful for insurance claims.", ex:"Poproszę o paragon.", exEn:"A receipt, please." }
          ]
        },
        {
          name: "Sprawy urzędowe",
          emoji: "🏛️",
          desc: "Offices, paperwork and appointments",
          cards: [
            { pl:"urząd", en:"office (government)", hint:"'urząd miasta' = city office.", ex:"Muszę iść do urzędu.", exEn:"I have to go to the office." },
            { pl:"PESEL", en:"PESEL (national ID number)", hint:"Poland's personal ID number - you'll need it often.", ex:"Potrzebuję numeru PESEL.", exEn:"I need a PESEL number." },
            { pl:"wniosek", en:"application", hint:"'złożyć wniosek' = to submit one.", ex:"Muszę złożyć wniosek.", exEn:"I have to submit an application." },
            { pl:"złożyć wniosek", en:"to submit an application", hint:"The core bureaucratic verb.", ex:"Gdzie mogę złożyć wniosek?", exEn:"Where can I submit the application?" },
            { pl:"dokument", en:"document", hint:"Often means ID here.", ex:"Proszę pokazać dokument.", exEn:"Please show some ID." },
            { pl:"dowód osobisty", en:"ID card", hint:"For citizens; foreigners use passport / karta pobytu.", ex:"Nie mam dowodu osobistego.", exEn:"I don't have an ID card." },
            { pl:"paszport", en:"passport", hint:"Your main ID as a foreigner.", ex:"Proszę o paszport.", exEn:"Your passport, please." },
            { pl:"karta pobytu", en:"residence card", hint:"The key document for foreigners.", ex:"Czekam na kartę pobytu.", exEn:"I'm waiting for my residence card." },
            { pl:"formularz", en:"form", hint:"'wypełnić formularz' = fill in a form.", ex:"Jak wypełnić ten formularz?", exEn:"How do I fill in this form?" },
            { pl:"wypełnić", en:"to fill in", hint:"Used for forms.", ex:"Proszę wypełnić formularz.", exEn:"Please fill in the form." },
            { pl:"podpis", en:"signature", hint:"'podpisać' = to sign.", ex:"Proszę o podpis tutaj.", exEn:"Your signature here, please." },
            { pl:"podpisać", en:"to sign", hint:"The verb form.", ex:"Gdzie mam podpisać?", exEn:"Where do I sign?" },
            { pl:"termin", en:"deadline / appointment date", hint:"Two meanings by context.", ex:"Jaki jest termin?", exEn:"What's the deadline?" },
            { pl:"umówić się na wizytę", en:"to book an appointment", hint:"For offices and clinics.", ex:"Chciałbym umówić się na wizytę.", exEn:"I'd like to book an appointment." },
            { pl:"kolejka", en:"queue / line", hint:"'stać w kolejce' = to queue.", ex:"Muszę stać w kolejce.", exEn:"I have to stand in the queue." },
            { pl:"numerek", en:"queue ticket (number)", hint:"Take one on arrival.", ex:"Proszę pobrać numerek.", exEn:"Please take a queue ticket." },
            { pl:"okienko", en:"service window / counter", hint:"Where you're served.", ex:"Proszę podejść do okienka numer trzy.", exEn:"Please go to window number three." },
            { pl:"opłata", en:"fee / charge", hint:"'bezpłatny' = free of charge.", ex:"Jaka jest opłata?", exEn:"What's the fee?" },
            { pl:"zaświadczenie", en:"certificate / official confirmation", hint:"Often needed as proof.", ex:"Potrzebuję zaświadczenia z pracy.", exEn:"I need a certificate from work." },
            { pl:"Czy potrzebuję...?", en:"Do I need...?", hint:"For checking requirements.", ex:"Czy potrzebuję tłumaczenia?", exEn:"Do I need a translation?" }
          ]
        },
        {
          name: "W restauracji",
          emoji: "🍽️",
          desc: "Booking, ordering and paying at a restaurant",
          cards: [
            { pl:"stolik na dwie osoby", en:"a table for two", hint:"Change the number as needed.", ex:"Poproszę stolik na dwie osoby.", exEn:"A table for two, please." },
            { pl:"rezerwacja", en:"reservation", hint:"'na nazwisko' = under the name of.", ex:"Mam rezerwację na nazwisko Nowak.", exEn:"I have a reservation under Nowak." },
            { pl:"karta / menu", en:"menu", hint:"'karta win' = wine list.", ex:"Poproszę kartę.", exEn:"The menu, please." },
            { pl:"przystawka", en:"starter / appetiser", hint:"Comes before the main.", ex:"Na przystawkę poproszę zupę.", exEn:"For a starter, I'll have soup." },
            { pl:"danie główne", en:"main course", hint:"'danie' = dish.", ex:"Co pan poleca na danie główne?", exEn:"What do you recommend for the main?" },
            { pl:"zupa", en:"soup", hint:"'zupa pomidorowa' = tomato soup.", ex:"Poproszę zupę pomidorową.", exEn:"Tomato soup, please." },
            { pl:"deser", en:"dessert", hint:"'na deser' = for dessert.", ex:"Na deser poproszę lody.", exEn:"For dessert, I'll have ice cream." },
            { pl:"Dla mnie...", en:"For me... (ordering)", hint:"Then name your dish.", ex:"Dla mnie kurczak, proszę.", exEn:"The chicken for me, please." },
            { pl:"Jestem wegetarianinem", en:"I'm vegetarian", hint:"A woman says 'wegetarianką'.", ex:"Jestem wegetarianinem.", exEn:"I'm vegetarian." },
            { pl:"Czy to danie jest ostre?", en:"Is this dish spicy?", hint:"'ostry' = spicy / sharp.", ex:"Czy to danie jest ostre?", exEn:"Is this dish spicy?" },
            { pl:"Czy jest wolny stolik?", en:"Is there a free table?", hint:"When you walk in without booking.", ex:"Dzień dobry, czy jest wolny stolik?", exEn:"Hello, is there a free table?" },
            { pl:"Czy mogę prosić o...?", en:"Could I have...?", hint:"Polite request.", ex:"Czy mogę prosić o wodę?", exEn:"Could I have some water?" },
            { pl:"widelec / nóż / łyżka", en:"fork / knife / spoon", hint:"The basic cutlery.", ex:"Brakuje mi widelca.", exEn:"I'm missing a fork." },
            { pl:"Było pyszne", en:"It was delicious", hint:"'pyszny' = delicious.", ex:"Dziękuję, było pyszne!", exEn:"Thank you, it was delicious!" },
            { pl:"Rachunek, proszę", en:"The bill, please", hint:"'rachunek' = the bill.", ex:"Poproszę rachunek.", exEn:"The bill, please." },
            { pl:"Płacimy razem", en:"We're paying together", hint:"One bill for the table.", ex:"Płacimy razem.", exEn:"We're paying together." },
            { pl:"Płacimy osobno", en:"We're paying separately", hint:"Split the bill.", ex:"Czy możemy zapłacić osobno?", exEn:"Can we pay separately?" },
            { pl:"napiwek", en:"tip", hint:"Around 10% is normal if happy.", ex:"Zostawię napiwek.", exEn:"I'll leave a tip." },
            { pl:"na wynos", en:"to take away", hint:"Same as in a café.", ex:"Czy mogę to wziąć na wynos?", exEn:"Can I take this away?" },
            { pl:"Smacznego", en:"Enjoy your meal", hint:"Said to others before eating.", ex:"Smacznego!", exEn:"Enjoy your meal!" }
          ]
        },
        {
          name: "Mieszkanie",
          emoji: "🏠",
          desc: "Renting a flat and dealing with problems",
          cards: [
            { pl:"mieszkanie", en:"flat / apartment", hint:"'wynajmować mieszkanie' = to rent a flat.", ex:"Wynajmuję mieszkanie w centrum.", exEn:"I rent a flat in the centre." },
            { pl:"wynajem", en:"rent / rental", hint:"The rent amount / the renting.", ex:"Ile wynosi wynajem?", exEn:"How much is the rent?" },
            { pl:"czynsz", en:"building service charge", hint:"Monthly building fee, often on top of rent.", ex:"Czynsz jest osobno.", exEn:"The service charge is separate." },
            { pl:"kaucja", en:"deposit", hint:"Usually one month's rent.", ex:"Ile wynosi kaucja?", exEn:"How much is the deposit?" },
            { pl:"umowa", en:"contract", hint:"'podpisać umowę' = to sign a contract.", ex:"Muszę podpisać umowę.", exEn:"I have to sign the contract." },
            { pl:"właściciel", en:"owner / landlord", hint:"A woman is 'właścicielka'.", ex:"Zadzwonię do właściciela.", exEn:"I'll call the landlord." },
            { pl:"rachunki", en:"bills / utilities", hint:"'wliczone' = included.", ex:"Czy rachunki są wliczone?", exEn:"Are the bills included?" },
            { pl:"prąd", en:"electricity", hint:"Masculine noun.", ex:"Nie mam prądu w kuchni.", exEn:"There's no electricity in the kitchen." },
            { pl:"woda", en:"water (utility)", hint:"'ciepła woda' = hot water.", ex:"Nie ma ciepłej wody.", exEn:"There's no hot water." },
            { pl:"ogrzewanie", en:"heating", hint:"Matters a lot in winter.", ex:"Ogrzewanie nie działa.", exEn:"The heating isn't working." },
            { pl:"internet", en:"internet", hint:"'w cenie' = included in the price.", ex:"Czy internet jest w cenie?", exEn:"Is internet included in the price?" },
            { pl:"klucze", en:"keys", hint:"Singular: 'klucz'.", ex:"Zgubiłem klucze.", exEn:"I've lost my keys." },
            { pl:"Coś nie działa", en:"Something isn't working", hint:"'działać' = to work / function.", ex:"Przepraszam, coś nie działa.", exEn:"Sorry, something isn't working." },
            { pl:"zepsuł się", en:"it broke / is broken", hint:"'zepsuty' = broken.", ex:"Zepsuł się piekarnik.", exEn:"The oven has broken." },
            { pl:"naprawić", en:"to repair / fix", hint:"'naprawa' = a repair.", ex:"Czy może pan to naprawić?", exEn:"Can you fix this?" },
            { pl:"kuchnia", en:"kitchen", hint:"Also means 'cuisine'.", ex:"Kuchnia jest mała, ale wygodna.", exEn:"The kitchen is small but comfortable." },
            { pl:"łazienka", en:"bathroom", hint:"Feminine noun.", ex:"Łazienka jest po lewej.", exEn:"The bathroom is on the left." },
            { pl:"sypialnia", en:"bedroom", hint:"'dwie sypialnie' = two bedrooms.", ex:"Mieszkanie ma dwie sypialnie.", exEn:"The flat has two bedrooms." },
            { pl:"sąsiad", en:"neighbour", hint:"A woman is 'sąsiadka'.", ex:"Mój sąsiad jest miły.", exEn:"My neighbour is nice." },
            { pl:"umeblowane", en:"furnished", hint:"'nieumeblowane' = unfurnished.", ex:"Czy mieszkanie jest umeblowane?", exEn:"Is the flat furnished?" },
            { pl:"pokój", en:"room", hint:"'pokój dzienny' = living room; 'kawalerka' = a studio flat.", ex:"Szukam mieszkania z dwoma pokojami.", exEn:"I'm looking for a two-room flat." },
            { pl:"salon", en:"living room", hint:"Where you relax and host guests. Also 'pokój dzienny'.", ex:"Wieczorem oglądamy film w salonie.", exEn:"In the evening we watch a film in the living room." },
            { pl:"przedpokój", en:"hallway / entrance hall", hint:"The area just inside the front door where you leave shoes and coats.", ex:"Zostaw buty w przedpokoju.", exEn:"Leave your shoes in the hallway." },
            { pl:"balkon", en:"balcony", hint:"'z balkonem' = with a balcony - a selling point in listings.", ex:"Latem jem śniadanie na balkonie.", exEn:"In summer I eat breakfast on the balcony." },
            { pl:"meble", en:"furniture", hint:"Plural noun. Singular 'mebel' is rare.", ex:"Kupiliśmy nowe meble do salonu.", exEn:"We bought new furniture for the living room." },
            { pl:"łóżko", en:"bed", hint:"Neuter noun. 'iść do łóżka' = go to bed.", ex:"Łóżko w sypialni jest wygodne.", exEn:"The bed in the bedroom is comfortable." },
            { pl:"stół", en:"table", hint:"'stół' = dining table; 'stolik' = a small/coffee table.", ex:"Kolacja jest na stole.", exEn:"Dinner is on the table." },
            { pl:"krzesło", en:"chair", hint:"Plural 'krzesła'. A soft armchair is a 'fotel'.", ex:"Przy stole są cztery krzesła.", exEn:"There are four chairs at the table." },
            { pl:"kanapa", en:"sofa / couch", hint:"Also 'sofa'. 'wersalka' = a sofa bed.", ex:"Kot śpi na kanapie.", exEn:"The cat is sleeping on the sofa." },
            { pl:"szafa", en:"wardrobe", hint:"For clothes. 'szafka' = a small cabinet/cupboard.", ex:"Powieś płaszcz w szafie.", exEn:"Hang your coat in the wardrobe." },
            { pl:"lodówka", en:"fridge", hint:"'zamrażarka' = freezer.", ex:"Mleko jest w lodówce.", exEn:"The milk is in the fridge." },
            { pl:"kuchenka", en:"cooker / stove", hint:"Don't confuse with 'kuchnia' (the room). 'piekarnik' = oven.", ex:"Włącz kuchenkę, ugotuję makaron.", exEn:"Turn on the stove, I'll cook pasta." },
            { pl:"pralka", en:"washing machine", hint:"A key question when renting: 'Czy jest pralka?'.", ex:"Pralka jest w łazience.", exEn:"The washing machine is in the bathroom." },
            { pl:"zmywarka", en:"dishwasher", hint:"Not in every flat - worth asking about.", ex:"Włożę talerze do zmywarki.", exEn:"I'll put the plates in the dishwasher." },
            { pl:"okno", en:"window", hint:"Neuter. 'parapet' = windowsill.", ex:"Otwórz okno, jest duszno.", exEn:"Open the window, it's stuffy." },
            { pl:"lampa", en:"lamp / light", hint:"'żarówka' = light bulb.", ex:"Lampa w sypialni się przepaliła.", exEn:"The lamp in the bedroom has burnt out." }
          ]
        },
        {
          name: "Życie codzienne i rutyna",
          emoji: "🔄",
          desc: "Daily life, routines, and frequency",
          cards: [
            { pl:"zazwyczaj", en:"usually", hint:"Adverb of frequency.", ex:"Zazwyczaj wstaję o siódmej rano.", exEn:"I usually get up at seven in the morning." },
            { pl:"codziennie", en:"every day", hint:"Very common for habits.", ex:"Codziennie piję dwie kawy.", exEn:"I drink two coffees every day." },
            { pl:"często / rzadko", en:"often / rarely", hint:"Opposites.", ex:"Często czytam, ale rzadko oglądam telewizję.", exEn:"I often read, but I rarely watch TV." },
            { pl:"wracać do domu", en:"to return home", hint:"Verb. 'Wracam' = I return.", ex:"Zazwyczaj wracam do domu po szesnastej.", exEn:"I usually return home after 4 PM." },
            { pl:"sprzątać", en:"to clean", hint:"Verb. 'Sprzątam' = I clean.", ex:"W sobotę sprzątam całe mieszkanie.", exEn:"On Saturday I clean the whole flat." },
            { pl:"prać", en:"to do laundry", hint:"Verb. 'Piorę' = I wash (clothes).", ex:"Muszę dzisiaj wyprać ubrania.", exEn:"I have to wash clothes today." },
            { pl:"odpoczywać", en:"to rest", hint:"Verb. 'Odpoczywam' = I rest.", ex:"Wieczorem wreszcie mogę odpocząć.", exEn:"In the evening I can finally rest." },
            { pl:"kłaść się spać", en:"to go to sleep", hint:"Reflexive verb. 'Kładę się' = I lay down.", ex:"Kładę się spać około północy.", exEn:"I go to sleep around midnight." },
            { pl:"zasypiać", en:"to fall asleep", hint:"Verb.", ex:"Zasypiam bardzo szybko.", exEn:"I fall asleep very fast." },
            { pl:"w dni robocze", en:"on weekdays", hint:"Monday to Friday.", ex:"W dni robocze jestem bardzo zajęty.", exEn:"On weekdays I am very busy." },
            { pl:"harmonogram", en:"schedule", hint:"Masculine noun.", ex:"Mój harmonogram jest bardzo napięty.", exEn:"My schedule is very tight." },
            { pl:"obowiązki domowe", en:"chores", hint:"Plural noun.", ex:"Nie lubię obowiązków domowych.", exEn:"I don't like household chores." }
          ]
        },
        {
          name: "Dom i rodzina",
          emoji: "🛋️",
          desc: "Family relations, flats, and furniture",
          cards: [
            { pl:"rodzice", en:"parents", hint:"Plural noun.", ex:"Moi rodzice mieszkają na wsi.", exEn:"My parents live in the countryside." },
            { pl:"rodzeństwo", en:"siblings", hint:"Neuter noun. Used collectively.", ex:"Czy masz rodzeństwo?", exEn:"Do you have any siblings?" },
            { pl:"wujek / ciocia", en:"uncle / aunt", hint:"Extended family.", ex:"W weekend odwiedzam ciocię.", exEn:"I am visiting my aunt this weekend." },
            { pl:"dziadkowie", en:"grandparents", hint:"Plural noun.", ex:"Moi dziadkowie mają małego psa.", exEn:"My grandparents have a small dog." },
            { pl:"małżeństwo", en:"married couple / marriage", hint:"Neuter noun.", ex:"Oni są szczęśliwym małżeństwem.", exEn:"They are a happy married couple." },
            { pl:"salon", en:"living room", hint:"Masculine noun.", ex:"Wieczorem siedzimy w salonie.", exEn:"In the evening we sit in the living room." },
            { pl:"meble", en:"furniture", hint:"Plural noun.", ex:"Kupiliśmy nowe meble do sypialni.", exEn:"We bought new furniture for the bedroom." },
            { pl:"szafa", en:"wardrobe", hint:"Feminine noun.", ex:"Moja szafa jest pełna ubrań.", exEn:"My wardrobe is full of clothes." },
            { pl:"kanapa", en:"sofa", hint:"Feminine noun.", ex:"Ta kanapa jest bardzo wygodna.", exEn:"This sofa is very comfortable." },
            { pl:"lodówka", en:"fridge", hint:"Feminine noun.", ex:"W lodówce nie ma mleka.", exEn:"There is no milk in the fridge." },
            { pl:"pralka", en:"washing machine", hint:"Feminine noun.", ex:"Pralka znowu się zepsuła.", exEn:"The washing machine broke again." },
            { pl:"zmywarka", en:"dishwasher", hint:"Feminine noun.", ex:"Muszę rozładować zmywarkę.", exEn:"I have to unload the dishwasher." },
            { pl:"odkurzacz", en:"vacuum cleaner", hint:"Masculine noun.", ex:"Gdzie schowałeś odkurzacz?", exEn:"Where did you hide the vacuum?" },
            { pl:"przeprowadzka", en:"moving house", hint:"Feminine noun.", ex:"Przeprowadzka to duży stres.", exEn:"Moving house is a big stress." }
          ]
        },
        {
          name: "Zdrowie i ciało",
          emoji: "🩺",
          desc: "Body parts, well-being, and doctor visits",
          cards: [
            { pl:"lekarz", en:"doctor", hint:"Masculine noun. 'Lekarka' for a woman.", ex:"Muszę umówić się do lekarza.", exEn:"I need to make an appointment with a doctor." },
            { pl:"dentysta", en:"dentist", hint:"Masculine/Feminine noun.", ex:"Boli mnie ząb, idę do dentysty.", exEn:"My tooth hurts, I'm going to the dentist." },
            { pl:"przychodnia", en:"clinic / health centre", hint:"Feminine noun.", ex:"Przychodnia jest otwarta do osiemnastej.", exEn:"The clinic is open until 6 PM." },
            { pl:"badanie", en:"examination / test", hint:"Neuter noun. E.g., badanie krwi (blood test).", ex:"Lekarz zlecił dodatkowe badania.", exEn:"The doctor ordered additional tests." },
            { pl:"skierowanie", en:"referral", hint:"Neuter noun. Needed for specialists.", ex:"Mam skierowanie do specjalisty.", exEn:"I have a referral to a specialist." },
            { pl:"głowa", en:"head", hint:"Feminine noun.", ex:"Strasznie boli mnie głowa.", exEn:"My head hurts terribly." },
            { pl:"brzuch", en:"stomach / belly", hint:"Masculine noun.", ex:"Nie mogę jeść, boli mnie brzuch.", exEn:"I can't eat, my stomach hurts." },
            { pl:"plecy", en:"back", hint:"Plural noun.", ex:"Bolą mnie plecy od siedzenia.", exEn:"My back hurts from sitting." },
            { pl:"ręka", en:"arm / hand", hint:"Feminine noun.", ex:"Złamałem prawą rękę.", exEn:"I broke my right arm." },
            { pl:"noga", en:"leg", hint:"Feminine noun.", ex:"Boli mnie lewa noga.", exEn:"My left leg hurts." },
            { pl:"oko / oczy", en:"eye / eyes", hint:"Irregular plural.", ex:"Mam niebieskie oczy.", exEn:"I have blue eyes." },
            { pl:"krew", en:"blood", hint:"Feminine noun.", ex:"Boję się pobierania krwi.", exEn:"I'm afraid of drawing blood." },
            { pl:"gardło", en:"throat", hint:"Neuter. 'ból gardła' = a sore throat - a very common complaint.", ex:"Boli mnie gardło i trudno mi przełykać.", exEn:"My throat hurts and it's hard to swallow." },
            { pl:"ząb / zęby", en:"tooth / teeth", hint:"Irregular plural. 'boli mnie ząb' = I have toothache.", ex:"Myję zęby dwa razy dziennie.", exEn:"I brush my teeth twice a day." },
            { pl:"ucho / uszy", en:"ear / ears", hint:"Irregular plural.", ex:"Od rana boli mnie ucho.", exEn:"My ear has been hurting since morning." },
            { pl:"nos", en:"nose", hint:"Masculine. 'katar' = a runny nose / cold.", ex:"Mam katar i zatkany nos.", exEn:"I have a runny and blocked nose." },
            { pl:"serce", en:"heart", hint:"Neuter. Also the emotional 'heart' in Polish.", ex:"Po bieganiu serce bije mi szybko.", exEn:"After running my heart beats fast." },
            { pl:"żołądek", en:"stomach (the organ)", hint:"The internal organ - vs 'brzuch', the belly area.", ex:"Mam problemy z żołądkiem po tłustym jedzeniu.", exEn:"I have stomach problems after greasy food." },
            { pl:"kość / kości", en:"bone / bones", hint:"Feminine. 'złamać kość' = to break a bone.", ex:"Upadłem, ale nie złamałem żadnej kości.", exEn:"I fell, but I didn't break any bones." },
            { pl:"kolano", en:"knee", hint:"Neuter. Plural 'kolana'.", ex:"Boli mnie kolano, kiedy biegam.", exEn:"My knee hurts when I run." },
            { pl:"stopa", en:"foot", hint:"Feminine. Don't confuse with 'noga' (the whole leg).", ex:"Mam ranę na stopie.", exEn:"I have a cut on my foot." },
            { pl:"palec", en:"finger / toe", hint:"Masculine. 'palec u nogi' = a toe.", ex:"Skaleczyłem się w palec.", exEn:"I cut my finger." },
            { pl:"szyja", en:"neck", hint:"Feminine. 'kark' = the back of the neck.", ex:"Rano bolała mnie szyja.", exEn:"My neck hurt this morning." },
            { pl:"ramię", en:"shoulder", hint:"Neuter, irregular. Plural 'ramiona'.", ex:"Noszę torbę na jednym ramieniu.", exEn:"I carry the bag on one shoulder." },
            { pl:"skóra", en:"skin", hint:"Feminine. Also 'leather'.", ex:"Zimą mam suchą skórę.", exEn:"In winter I have dry skin." },
            { pl:"Jak się pan czuje?", en:"How are you feeling?", hint:"Formal question to a man.", ex:"Jak się pan dzisiaj czuje?", exEn:"How are you feeling today?" },
            { pl:"chorować", en:"to be sick / ill", hint:"Verb. 'Choruję' = I am sick.", ex:"Często choruję zimą.", exEn:"I am often sick in winter." },
            { pl:"zdrowieć", en:"to get well", hint:"Verb.", ex:"Bierz leki i szybko zdrowiej!", exEn:"Take your medicine and get well soon!" }
          ]
        },
        {
          name: "Jedzenie i zakupy",
          emoji: "🥟",
          desc: "Polish dishes, recipes, and shopping for food",
          cards: [
            { pl:"pierogi", en:"dumplings", hint:"Plural noun. Polish classic.", ex:"Pierogi ruskie to moje ulubione danie.", exEn:"Russian dumplings are my favorite dish." },
            { pl:"schabowy", en:"breaded pork cutlet", hint:"Short for 'kotlet schabowy'.", ex:"Na obiad jest schabowy z ziemniakami.", exEn:"For dinner there is pork cutlet with potatoes." },
            { pl:"przepis", en:"recipe", hint:"Masculine noun.", ex:"Masz świetny przepis na to ciasto.", exEn:"You have a great recipe for this cake." },
            { pl:"składniki", en:"ingredients", hint:"Plural noun.", ex:"Muszę kupić wszystkie składniki na zupę.", exEn:"I need to buy all the ingredients for the soup." },
            { pl:"gotować", en:"to cook", hint:"Verb. 'Gotuję' = I cook.", ex:"Uwielbiam gotować w weekendy.", exEn:"I love to cook on weekends." },
            { pl:"smażyć", en:"to fry", hint:"Verb.", ex:"Trzeba usmażyć cebulę na patelni.", exEn:"You need to fry the onion in a pan." },
            { pl:"piec", en:"to bake", hint:"Verb. 'Piekę' = I bake.", ex:"Często piekę chleb w domu.", exEn:"I often bake bread at home." },
            { pl:"targ / rynek", en:"farmer's market", hint:"Masculine noun.", ex:"Kupuję warzywa na targu.", exEn:"I buy vegetables at the market." },
            { pl:"warzywniak", en:"greengrocer's", hint:"Masculine noun.", ex:"Idę do warzywniaka po pomidory.", exEn:"I'm going to the greengrocer for tomatoes." },
            { pl:"piekarnia", en:"bakery", hint:"Feminine noun.", ex:"Świeży chleb z piekarni pachnie pięknie.", exEn:"Fresh bread from the bakery smells beautiful." },
            { pl:"świeży", en:"fresh", hint:"Adjective.", ex:"Te owoce są bardzo świeże.", exEn:"These fruits are very fresh." },
            { pl:"puszka / słoik", en:"can / jar", hint:"Packaging types.", ex:"Kupiłem puszkę fasoli i słoik dżemu.", exEn:"I bought a can of beans and a jar of jam." }
          ]
        },
        {
          name: "Podróże i wakacje",
          emoji: "✈️",
          desc: "Transport, accommodation, and weather",
          cards: [
            { pl:"lotnisko", en:"airport", hint:"Neuter noun.", ex:"Jedziemy taksówką na lotnisko.", exEn:"We are taking a taxi to the airport." },
            { pl:"samolot", en:"airplane", hint:"Masculine noun.", ex:"Samolot startuje o ósmej.", exEn:"The plane takes off at eight." },
            { pl:"pociąg", en:"train", hint:"Masculine noun.", ex:"Wolę podróżować pociągiem niż autobusem.", exEn:"I prefer traveling by train rather than by bus." },
            { pl:"walizka", en:"suitcase", hint:"Feminine noun.", ex:"Moja walizka jest bardzo ciężka.", exEn:"My suitcase is very heavy." },
            { pl:"bagaż", en:"luggage", hint:"Masculine noun.", ex:"Gdzie mogę zostawić mój bagaż?", exEn:"Where can I leave my luggage?" },
            { pl:"bilet lotniczy", en:"flight ticket", hint:"Masculine noun.", ex:"Kupiłem bilety lotnicze do Hiszpanii.", exEn:"I bought flight tickets to Spain." },
            { pl:"rezerwować", en:"to book / reserve", hint:"Verb. 'Rezerwuję' = I book.", ex:"Chcę zarezerwować pokój na dwie noce.", exEn:"I want to book a room for two nights." },
            { pl:"nocleg", en:"accommodation", hint:"Masculine noun.", ex:"Szukamy taniego noclegu w centrum.", exEn:"We are looking for cheap accommodation in the center." },
            { pl:"hotel", en:"hotel", hint:"Masculine noun.", ex:"Ten hotel ma pięć gwiazdek.", exEn:"This hotel has five stars." },
            { pl:"góry", en:"mountains", hint:"Plural noun. 'W górach' = in the mountains.", ex:"Latem jedziemy w góry.", exEn:"In the summer we are going to the mountains." },
            { pl:"morze", en:"sea", hint:"Neuter noun. 'Nad morzem' = by the sea.", ex:"Uwielbiam wakacje nad morzem.", exEn:"I love holidays by the sea." },
            { pl:"upał", en:"heatwave", hint:"Masculine noun.", ex:"Dzisiaj jest straszny upał.", exEn:"There is a terrible heatwave today." },
            { pl:"burza", en:"storm", hint:"Feminine noun.", ex:"Boję się, że będzie burza.", exEn:"I'm afraid there will be a storm." },
            { pl:"wiatr", en:"wind", hint:"Masculine noun.", ex:"Dzisiaj wieje silny wiatr.", exEn:"A strong wind is blowing today." }
          ]
        },
        {
          name: "Praca i edukacja",
          emoji: "🎓",
          desc: "Professions, studying, and the workplace",
          cards: [
            { pl:"nauczyciel / nauczycielka", en:"teacher (m/f)", hint:"Profession.", ex:"Mój brat jest nauczycielem historii.", exEn:"My brother is a history teacher." },
            { pl:"uczeń / student", en:"pupil / university student", hint:"'Student' strictly means uni student in Polish.", ex:"Jestem studentem pierwszego roku.", exEn:"I am a first-year student." },
            { pl:"szkoła", en:"school", hint:"Feminine noun.", ex:"Dzieci są w szkole.", exEn:"The children are at school." },
            { pl:"uniwersytet", en:"university", hint:"Masculine noun.", ex:"Studiuję na uniwersytecie.", exEn:"I study at the university." },
            { pl:"wykład", en:"lecture", hint:"Masculine noun.", ex:"Wykład z ekonomii był bardzo nudny.", exEn:"The economics lecture was very boring." },
            { pl:"egzamin", en:"exam", hint:"Masculine noun.", ex:"Jutro rano mam trudny egzamin.", exEn:"I have a difficult exam tomorrow morning." },
            { pl:"uczyć się", en:"to study / learn", hint:"Verb. 'Uczę się' = I study.", ex:"Muszę się uczyć do egzaminu.", exEn:"I have to study for the exam." },
            { pl:"zawód", en:"profession", hint:"Masculine noun.", ex:"Jaki masz zawód?", exEn:"What is your profession?" },
            { pl:"inżynier", en:"engineer", hint:"Profession.", ex:"Ona pracuje jako inżynier oprogramowania.", exEn:"She works as a software engineer." },
            { pl:"szukać pracy", en:"to look for a job", hint:"Verb phrase.", ex:"Od miesiąca szukam nowej pracy.", exEn:"I have been looking for a new job for a month." },
            { pl:"rozmowa kwalifikacyjna", en:"job interview", hint:"Feminine noun.", ex:"Mam jutro rozmowę kwalifikacyjną.", exEn:"I have a job interview tomorrow." },
            { pl:"doświadczenie", en:"experience", hint:"Neuter noun.", ex:"Wymagane jest doświadczenie w branży.", exEn:"Experience in the industry is required." },
            { pl:"wynagrodzenie", en:"salary", hint:"Neuter noun.", ex:"Oczekuję dobrego wynagrodzenia.", exEn:"I expect a good salary." },
            { pl:"awans", en:"promotion", hint:"Masculine noun.", ex:"Dostałem awans i podwyżkę!", exEn:"I got a promotion and a raise!" }
          ]
        },
        {
          name: "Czas wolny i kultura",
          emoji: "🎭",
          desc: "Hobbies, sports, and going out",
          cards: [
            { pl:"hobby", en:"hobby", hint:"Neuter noun. Does not decline.", ex:"Moje główne hobby to fotografia.", exEn:"My main hobby is photography." },
            { pl:"interesować się", en:"to be interested in", hint:"Reflexive verb + instrumental case.", ex:"Interesuję się polityką i sportem.", exEn:"I am interested in politics and sports." },
            { pl:"kino", en:"cinema", hint:"Neuter noun.", ex:"Idziemy dzisiaj do kina na komedię.", exEn:"We are going to the cinema for a comedy today." },
            { pl:"teatr", en:"theater", hint:"Masculine noun.", ex:"Mam bilety do teatru na sobotę.", exEn:"I have theater tickets for Saturday." },
            { pl:"wystawa", en:"exhibition", hint:"Feminine noun.", ex:"To bardzo ciekawa wystawa sztuki.", exEn:"This is a very interesting art exhibition." },
            { pl:"koncert", en:"concert", hint:"Masculine noun.", ex:"Bilety na ten koncert są wyprzedane.", exEn:"Tickets for this concert are sold out." },
            { pl:"uprawiać sport", en:"to do sports", hint:"Verb phrase.", ex:"Trzeba uprawiać sport, żeby być zdrowym.", exEn:"You need to do sports to be healthy." },
            { pl:"biegać", en:"to run / jog", hint:"Verb. 'Biegam' = I run.", ex:"Biegam w parku trzy razy w tygodniu.", exEn:"I run in the park three times a week." },
            { pl:"siłownia", en:"gym", hint:"Feminine noun.", ex:"Po pracy idę na siłownię.", exEn:"After work, I go to the gym." },
            { pl:"basen", en:"swimming pool", hint:"Masculine noun.", ex:"W niedzielę rano chodzę na basen.", exEn:"I go to the swimming pool on Sunday morning." },
            { pl:"spotykać się", en:"to meet up", hint:"Reflexive verb.", ex:"Często spotykam się z przyjaciółmi w pubie.", exEn:"I often meet with friends at the pub." },
            { pl:"znajomi", en:"acquaintances / friends", hint:"Plural noun. Less intimate than 'przyjaciele'.", ex:"Zaprosiłem kilku znajomych z pracy.", exEn:"I invited a few friends from work." },
            { pl:"spacer", en:"walk / stroll", hint:"Masculine noun. 'Iść na spacer' = go for a walk.", ex:"Chodźmy na długi spacer do lasu.", exEn:"Let's go for a long walk to the forest." }
          ]
        },
        {
          name: "Pogoda i klimat",
          emoji: "⛅",
          desc: "Weather, phenomena and describing the forecast",
          cards: [
            { pl:"upał", en:"heatwave, scorching heat", hint:"rzecz. m. · lm. upały · Often used in plural (upały) for a hot spell.", ex:"Dzisiaj jest straszny upał.", exEn:"Today it's terribly hot." },
            { pl:"powódź", en:"flood", hint:"rzecz. ż. · lm. powodzie", ex:"Po ulewach była powódź.", exEn:"After the downpours there was a flood." },
            { pl:"trąba powietrzna", en:"tornado, whirlwind", hint:"rzecz. ż. · lm. trąby powietrzne · Literally “air trumpet”.", ex:"Trąba powietrzna zniszczyła las.", exEn:"A tornado destroyed the forest." },
            { pl:"susza", en:"drought", hint:"rzecz. ż. · lm. susze", ex:"Latem często jest susza.", exEn:"In summer there is often a drought." },
            { pl:"ulewa", en:"downpour, heavy rain", hint:"rzecz. ż. · lm. ulewy", ex:"Wczoraj była wielka ulewa.", exEn:"Yesterday there was a heavy downpour." },
            { pl:"huragan", en:"hurricane", hint:"rzecz. m. · lm. huragany", ex:"Nadchodzi huragan.", exEn:"A hurricane is coming." },
            { pl:"burza", en:"(thunder)storm", hint:"rzecz. ż.", ex:"Wieczorem będzie burza.", exEn:"In the evening there will be a storm." },
            { pl:"grad", en:"hail", hint:"rzecz. m.", ex:"Podczas burzy padał grad.", exEn:"During the storm it was hailing." },
            { pl:"tornado", en:"tornado", hint:"rzecz. n. · nieodm. · Borrowed word; doesn't decline.", ex:"W USA często są tornada.", exEn:"In the USA there are often tornadoes." },
            { pl:"pogoda", en:"weather", hint:"rzecz. ż.", ex:"Jaka jest dzisiaj pogoda?", exEn:"What's the weather like today?" },
            { pl:"klimat", en:"climate", hint:"rzecz. m.", ex:"Klimat się zmienia.", exEn:"The climate is changing." },
            { pl:"pora roku", en:"season (of the year)", hint:"rzecz. ż. · lm. pory roku · “dwie pory roku” = two seasons.", ex:"Jaka jest twoja ulubiona pora roku?", exEn:"What's your favourite season?" },
            { pl:"opady", en:"precipitation, rainfall", hint:"rzecz. lm. · Plural-only; “opady deszczu” = rainfall.", ex:"Jutro będą opady deszczu.", exEn:"Tomorrow there will be rainfall." },
            { pl:"deszcz", en:"rain", hint:"rzecz. m. · “pada deszcz” = it's raining.", ex:"Weź parasol, bo pada deszcz.", exEn:"Take an umbrella, because it's raining." },
            { pl:"śnieg", en:"snow", hint:"rzecz. m.", ex:"Zimą pada śnieg.", exEn:"In winter it snows." },
            { pl:"wiatr", en:"wind", hint:"rzecz. m. · “wieje wiatr” = the wind is blowing.", ex:"Na dworze wieje silny wiatr.", exEn:"Outside a strong wind is blowing." },
            { pl:"woda", en:"water", hint:"rzecz. ż.", ex:"Latem brakuje wody.", exEn:"In summer there is a shortage of water." },
            { pl:"prędkość", en:"speed", hint:"rzecz. ż. · “z prędkością...” = at a speed of...", ex:"Wiatr wieje z prędkością 100 km/h.", exEn:"The wind blows at a speed of 100 km/h." },
            { pl:"ciepły", en:"warm (warmer)", hint:"przym. · stopień wyższy: cieplejszy · Adverb: ciepło / cieplej.", ex:"Maj będzie cieplejszy niż kwiecień.", exEn:"May will be warmer than April." },
            { pl:"chłodny", en:"cool (cooler)", hint:"przym. · st. wyższy: chłodniejszy · Adverb: chłodno / chłodniej.", ex:"Zimy będą chłodniejsze niż teraz.", exEn:"Winters will be cooler than now." },
            { pl:"zimny", en:"cold (colder)", hint:"przym. · st. wyższy: zimniejszy · Adverb: zimno / zimniej.", ex:"Ta zima jest zimniejsza niż poprzednia.", exEn:"This winter is colder than the previous one." },
            { pl:"suchy", en:"dry", hint:"przym. · st. wyższy: bardziej suchy", ex:"Lato będzie bardziej suche.", exEn:"The summer will be drier." },
            { pl:"mokry", en:"wet", hint:"przym.", ex:"Po deszczu trawa jest mokra.", exEn:"After the rain the grass is wet." },
            { pl:"deszczowy", en:"rainy", hint:"przym.", ex:"Jesień jest deszczowa.", exEn:"Autumn is rainy." },
            { pl:"silny", en:"strong (stronger)", hint:"przym. · st. wyższy: silniejszy · Of wind and storms.", ex:"Burze będą silniejsze niż teraz.", exEn:"Storms will be stronger than now." },
            { pl:"słaby", en:"weak (weaker)", hint:"przym. · st. wyższy: słabszy", ex:"Deszcz będzie słabszy niż wczoraj.", exEn:"The rain will be weaker than yesterday." },
            { pl:"ulewny", en:"torrential", hint:"przym. · “deszcz ulewny” = torrential rain.", ex:"Padał ulewny deszcz.", exEn:"Torrential rain was falling." },
            { pl:"upalny", en:"sweltering, boiling hot", hint:"przym. · Adjective from upał. Adverb: upalnie.", ex:"To był upalny dzień.", exEn:"It was a sweltering day." },
            { pl:"zmiana", en:"change", hint:"rzecz. ż. · “zmiana klimatu” = climate change.", ex:"Zmiana klimatu to wielki problem.", exEn:"Climate change is a big problem." },
            { pl:"rolnictwo", en:"agriculture", hint:"rzecz. n.", ex:"Zmiany klimatu wpływają na rolnictwo.", exEn:"Climate changes affect agriculture." }
          ]
        },
        {
          name: "Cechy charakteru",
          emoji: "🙂",
          desc: "Personality traits - for work and social life",
          cards: [
            { pl:"pracowity", en:"hardworking", hint:"≠ leniwy. A great trait for a CV.", ex:"Moja koleżanka jest bardzo pracowita.", exEn:"My colleague is very hardworking." },
            { pl:"leniwy", en:"lazy", hint:"≠ pracowity.", ex:"W weekend jestem leniwy.", exEn:"At the weekend I'm lazy." },
            { pl:"dokładny", en:"meticulous, accurate", hint:"≈ precyzyjny. Careful and thorough.", ex:"Dobry księgowy jest dokładny.", exEn:"A good accountant is meticulous." },
            { pl:"wytrwały", en:"persistent, persevering", hint:"≈ konsekwentny. Keeps going to the end.", ex:"Musisz być wytrwały, żeby nauczyć się polskiego.", exEn:"You have to be persistent to learn Polish." },
            { pl:"zorganizowany", en:"organized", hint:"≠ roztrzepany.", ex:"Jestem dobrze zorganizowana.", exEn:"I'm well organized." },
            { pl:"roztrzepany", en:"scatterbrained", hint:"≠ (dobrze) zorganizowany. Absent-minded.", ex:"Czasem jestem roztrzepany i gubię klucze.", exEn:"Sometimes I'm scatterbrained and lose my keys." },
            { pl:"ambitny", en:"ambitious", hint:"Wants to achieve a lot.", ex:"To bardzo ambitna osoba.", exEn:"That's a very ambitious person." },
            { pl:"wymagający", en:"demanding", hint:"Expects a lot - of self and others.", ex:"Mój szef jest wymagający.", exEn:"My boss is demanding." },
            { pl:"kreatywny", en:"creative", hint:"≈ twórczy.", ex:"Artyści są kreatywni.", exEn:"Artists are creative." },
            { pl:"szczery", en:"honest, sincere", hint:"Says what they really think.", ex:"Bądź ze mną szczery.", exEn:"Be honest with me." },
            { pl:"gadatliwy", en:"talkative", hint:"Talks a lot (mildly negative).", ex:"Moja sąsiadka jest gadatliwa.", exEn:"My neighbour is talkative." },
            { pl:"bezpośredni", en:"direct, straightforward", hint:"≈ naturalny. Says things straight.", ex:"Wolę ludzi bezpośrednich.", exEn:"I prefer direct people." },
            { pl:"otwarty", en:"open", hint:"≠ zamknięty w sobie.", ex:"Jest otwarty na nowych ludzi.", exEn:"He's open to new people." },
            { pl:"zamknięty w sobie", en:"reserved, withdrawn", hint:"≠ otwarty. Keeps to themselves.", ex:"Jako dziecko był zamknięty w sobie.", exEn:"As a child he was withdrawn." },
            { pl:"nieśmiały", en:"shy", hint:"≠ pewny siebie.", ex:"Nie bądź taki nieśmiały!", exEn:"Don't be so shy!" },
            { pl:"towarzyski", en:"sociable", hint:"Enjoys company and people.", ex:"Jest bardzo towarzyska i ma dużo przyjaciół.", exEn:"She's very sociable and has lots of friends." },
            { pl:"kłótliwy", en:"quarrelsome", hint:"≈ konfliktowy. Picks arguments.", ex:"Nie lubię kłótliwych ludzi.", exEn:"I don't like quarrelsome people." },
            { pl:"opiekuńczy", en:"caring, protective", hint:"Looks after and cares for others.", ex:"Jest opiekuńczym ojcem.", exEn:"He's a caring father." },
            { pl:"miły", en:"nice, kind, pleasant", hint:"One of the most-used compliments in Polish.", ex:"Nasz nowy sąsiad jest bardzo miły.", exEn:"Our new neighbour is very nice." },
            { pl:"spokojny", en:"calm", hint:"≠ nerwowy.", ex:"Po jodze jestem spokojny.", exEn:"After yoga I'm calm." },
            { pl:"nerwowy", en:"nervous, edgy", hint:"≠ spokojny. Easily stressed.", ex:"Przed egzaminem jestem nerwowa.", exEn:"Before an exam I'm nervous." },
            { pl:"pogodny", en:"cheerful", hint:"≈ wesoły; ≠ smutny.", ex:"Ma pogodne usposobienie.", exEn:"She has a cheerful disposition." },
            { pl:"wesoły", en:"merry, happy", hint:"≈ pogodny; ≠ poważny.", ex:"Jest zawsze wesoły.", exEn:"He's always cheerful." },
            { pl:"poważny", en:"serious", hint:"≠ wesoły.", ex:"Dlaczego jesteś taki poważny?", exEn:"Why are you so serious?" },
            { pl:"cierpliwy", en:"patient", hint:"≠ niecierpliwy. Can wait calmly.", ex:"Nauczyciel musi być cierpliwy.", exEn:"A teacher must be patient." },
            { pl:"niecierpliwy", en:"impatient", hint:"≠ cierpliwy.", ex:"Jestem niecierpliwy, kiedy czekam.", exEn:"I'm impatient when I'm waiting." },
            { pl:"chłodny", en:"cold, aloof", hint:"≈ zimny (of a person). Distant.", ex:"Był wobec mnie chłodny.", exEn:"He was cold towards me." },
            { pl:"uparty", en:"stubborn", hint:"Never changes their mind. Idiom: uparty jak osioł.", ex:"Jesteś uparty jak osioł!", exEn:"You're as stubborn as a mule!" },
            { pl:"odważny", en:"brave, courageous", hint:"Afraid of nothing.", ex:"Bądź odważny i spróbuj!", exEn:"Be brave and try!" },
            { pl:"pewny siebie", en:"self-confident", hint:"≠ nieśmiały. Self-assured.", ex:"Na rozmowie o pracę bądź pewny siebie.", exEn:"At a job interview, be self-confident." },
            { pl:"niezależny", en:"independent", hint:"≈ wolny. Doesn't rely on others.", ex:"Jest finansowo niezależna.", exEn:"She's financially independent." },
            { pl:"dominujący", en:"domineering", hint:"≈ despotyczny. Likes to be in control.", ex:"Ma dominujący charakter.", exEn:"He has a domineering character." },
            { pl:"wrażliwy", en:"sensitive", hint:"≈ delikatny. Feels things deeply.", ex:"Jest wrażliwy na krytykę.", exEn:"He's sensitive to criticism." },
            { pl:"oszczędny", en:"thrifty, economical", hint:"≠ rozrzutny. Saves money - the positive word.", ex:"Moi rodzice są oszczędni.", exEn:"My parents are thrifty." },
            { pl:"skąpy", en:"stingy, miserly", hint:"Hates spending - the negative twin of oszczędny.", ex:"Nie bądź skąpy, postaw kawę!", exEn:"Don't be stingy, buy a coffee!" },
            { pl:"rozrzutny", en:"wasteful, extravagant", hint:"≠ oszczędny. Spends too freely.", ex:"Jest rozrzutny i wydaje za dużo.", exEn:"He's wasteful and spends too much." }
          ]
        },
        {
          name: "Ekologia",
          emoji: "🌿",
          desc: "Recycling, waste and saving water and energy",
          cards: [
            { pl:"oddawać / oddać", en:"to give back, return", hint:"czas. niedok. / dok. · oddać coś komuś = give sth back to sb.", ex:"Oddam butelki w sklepie.", exEn:"I'll return the bottles at the shop." },
            { pl:"zwracać / zwrócić", en:"to return, give back", hint:"czas. niedok. / dok. · Close to oddać; often used for refunds.", ex:"Zwrócę butelki i dostanę pieniądze.", exEn:"I'll return the bottles and get money back." },
            { pl:"zbierać / zebrać", en:"to collect, gather", hint:"czas. niedok. / dok.", ex:"Będę zbierać butelki do recyklingu.", exEn:"I will collect bottles for recycling." },
            { pl:"wyrzucać / wyrzucić", en:"to throw out", hint:"czas. niedok. / dok. · wyrzucać śmieci = take out the rubbish.", ex:"Wyrzucę śmieci wieczorem.", exEn:"I'll take out the rubbish in the evening." },
            { pl:"segregować", en:"to sort, segregate", hint:"czas. (niedok.) · segregować śmieci / odpady.", ex:"Będę segregować śmieci w domu.", exEn:"I will sort the rubbish at home." },
            { pl:"system kaucyjny", en:"deposit-return system", hint:"rzecz. m. · kaucja = the deposit you get back.", ex:"W Polsce działa system kaucyjny na butelki.", exEn:"In Poland there's a deposit-return system for bottles." },
            { pl:"butelka zwrotna", en:"returnable (deposit) bottle", hint:"rzecz. ż. · You return it for money.", ex:"To jest butelka zwrotna.", exEn:"This is a returnable bottle." },
            { pl:"opakowanie", en:"packaging", hint:"rzecz. n. · jednorazowe = single-use, wielorazowe = reusable.", ex:"To opakowanie nadaje się do recyklingu.", exEn:"This packaging is recyclable." },
            { pl:"szkło", en:"glass (the material)", hint:"rzecz. n. · The substance, not the cup.", ex:"Szkło wyrzucam do zielonego pojemnika.", exEn:"I throw glass into the green container." },
            { pl:"szklanka", en:"(drinking) glass, tumbler", hint:"rzecz. ż. · The object you drink from.", ex:"Wypiłem szklankę wody.", exEn:"I drank a glass of water." },
            { pl:"śmieci", en:"rubbish, trash", hint:"rzecz. lm. · Everyday word; plural.", ex:"Wyrzuć śmieci, proszę.", exEn:"Take out the rubbish, please." },
            { pl:"odpady", en:"waste", hint:"rzecz. lm. · More formal/technical than śmieci.", ex:"Segregujemy odpady w domu.", exEn:"We sort waste at home." },
            { pl:"oszczędzać / oszczędzić", en:"to save (water, power)", hint:"czas. niedok. / dok. · oszczędzać wodę, prąd.", ex:"Będę oszczędzać wodę i prąd.", exEn:"I will save water and electricity." },
            { pl:"wyłączać / wyłączyć", en:"to switch off, turn off", hint:"czas. niedok. / dok. · Opposite: włączać / włączyć (turn on).", ex:"Wyłączę komputer na noc.", exEn:"I'll switch off the computer for the night." },
            { pl:"zakręcać / zakręcić", en:"to turn off (a tap)", hint:"czas. niedok. / dok. · zakręcać wodę = turn off the water.", ex:"Zakręcaj wodę podczas mycia zębów.", exEn:"Turn off the tap while brushing your teeth." },
            { pl:"marnować / zmarnować", en:"to waste", hint:"czas. niedok. / dok. · marnować wodę, jedzenie, czas.", ex:"Nie będę marnować jedzenia.", exEn:"I won't waste food." },
            { pl:"energooszczędny", en:"energy-efficient", hint:"przym. · sprzęt RTV i AGD = electronics & appliances.", ex:"Kupię energooszczędny sprzęt.", exEn:"I'll buy energy-efficient appliances." },
            { pl:"twarda woda", en:"hard water", hint:"rzecz. ż. · High in minerals; opp. miękka woda.", ex:"W naszym kranie jest twarda woda.", exEn:"Our tap has hard water." },
            { pl:"wanna", en:"bathtub", hint:"rzecz. ż. · kąpiel = a bath; prysznic = a shower.", ex:"Wolę prysznic niż kąpiel w wannie.", exEn:"I prefer a shower to a bath in the tub." },
            { pl:"brać / wziąć prysznic", en:"to take a shower", hint:"czas. niedok. / dok. · zamiast kąpieli = instead of a bath.", ex:"Będę brać prysznic zamiast kąpieli.", exEn:"I'll take a shower instead of a bath." },
            { pl:"kupować / kupić", en:"to buy", hint:"czas. niedok. / dok.", ex:"Nie będę kupować nowych ubrań.", exEn:"I won't buy new clothes." },
            { pl:"wymieniać się / wymienić się", en:"to swap, exchange", hint:"czas. niedok. / dok. + narzędnik · wymieniać się ubraniami = swap clothes.", ex:"Wymieniam się ubraniami z koleżankami.", exEn:"I swap clothes with friends." },
            { pl:"pakować / zapakować", en:"to pack", hint:"czas. niedok. / dok.", ex:"Zapakuję zakupy do własnej torby.", exEn:"I'll pack the shopping into my own bag." },
            { pl:"używać / użyć", en:"to use", hint:"czas. niedok. / dok. + dopełniacz · Takes genitive: używać plastiku.", ex:"Będę używać wielorazowych opakowań.", exEn:"I'll use reusable packaging." },
            { pl:"komunikacja miejska", en:"public transport", hint:"rzecz. ż. · zamiast samochodem = instead of by car.", ex:"Jeżdżę komunikacją miejską zamiast samochodem.", exEn:"I travel by public transport instead of by car." },
            { pl:"inwestować / zainwestować", en:"to invest", hint:"czas. niedok. / dok. · inwestować w zieloną energię.", ex:"Będę inwestować w zieloną energię.", exEn:"I will invest in green energy." },
            { pl:"redukować / zredukować", en:"to reduce", hint:"czas. niedok. / dok. · redukować emisję CO2.", ex:"Musimy redukować emisję CO2.", exEn:"We must reduce CO2 emissions." },
            { pl:"wycinać / wyciąć", en:"to cut down", hint:"czas. niedok. / dok. · wycinać drzewa = cut down trees.", ex:"Nie powinniśmy wycinać drzew.", exEn:"We shouldn't cut down trees." },
            { pl:"globalne ocieplenie", en:"global warming", hint:"rzecz. n. · ocieplenie klimatu = climate warming.", ex:"Globalne ocieplenie to wielki problem.", exEn:"Global warming is a big problem." },
            { pl:"środowisko", en:"environment", hint:"rzecz. n. · chronić środowisko = protect the environment.", ex:"Chcę chronić środowisko.", exEn:"I want to protect the environment." }
          ]
        }
        ,{
          name: "Wygl\u0105d i ubrania",
          emoji: "\uD83D\uDC55",
          desc: "Describing people, clothes, and fashion",
          cards: [
            { pl:"wygl\u0105da\u0107 na", en:"to look (a certain way)", hint:"czas. + biernik \u00b7 wygl\u0105da\u0107 na zm\u0119czonego = to look tired.", ex:"Wygl\u0105dasz na zm\u0119czon\u0105.", exEn:"You look tired." },
            { pl:"by\u0107 podobnym do", en:"to look like / resemble", hint:"+ dope\u0142niacz \u00b7 podobny do ojca = like one's father.", ex:"Jeste\u015b bardzo podobny do brata.", exEn:"You look a lot like your brother." },
            { pl:"mie\u0107 na sobie", en:"to have on / be wearing", hint:"+ biernik \u00b7 the everyday way to say 'wearing'.", ex:"Ona ma na sobie czerwon\u0105 sukienk\u0119.", exEn:"She's wearing a red dress." },
            { pl:"nosi\u0107", en:"to wear (habitually)", hint:"czas. niedok. \u00b7 for what you wear regularly, not right now.", ex:"Zim\u0105 nosz\u0119 ciep\u0142\u0105 czapk\u0119.", exEn:"In winter I wear a warm hat." },
            { pl:"za\u0142o\u017cy\u0107 / zak\u0142ada\u0107", en:"to put on", hint:"dok. / niedok. \u00b7 za\u0142o\u017cy\u0107 kurtk\u0119 = put a jacket on.", ex:"Za\u0142\u00f3\u017c kurtk\u0119, jest zimno.", exEn:"Put a jacket on, it's cold." },
            { pl:"przymierzy\u0107", en:"to try on", hint:"dok. \u00b7 in a shop: Czy mog\u0119 przymierzy\u0107...?", ex:"Chc\u0119 przymierzy\u0107 te buty.", exEn:"I'd like to try on these shoes." },
            { pl:"pasowa\u0107 do", en:"to match / suit", hint:"+ dope\u0142niacz \u00b7 ten szalik pasuje do p\u0142aszcza.", ex:"Ten kolor pasuje do twoich oczu.", exEn:"This colour matches your eyes." },
            { pl:"le\u017ce\u0107 dobrze", en:"to fit well", hint:"o ubraniu \u00b7 t\u0119 sukienk\u0119 le\u017cy idealnie = it fits perfectly.", ex:"Te spodnie le\u017c\u0105 na tobie \u015bwietnie.", exEn:"Those trousers fit you great." },
            { pl:"sukienka", en:"dress", hint:"rzecz. \u017c. \u00b7 letnia sukienka = a summer dress.", ex:"Kupi\u0142am now\u0105 sukienk\u0119 na wesele.", exEn:"I bought a new dress for the wedding." },
            { pl:"koszula", en:"shirt", hint:"rzecz. \u017c. \u00b7 koszula w kratk\u0119 = a checked shirt.", ex:"Do pracy nosz\u0119 bia\u0142\u0105 koszul\u0119.", exEn:"I wear a white shirt to work." },
            { pl:"spodnie", en:"trousers", hint:"rzecz., zawsze l. mnoga (like 'trousers').", ex:"Te spodnie s\u0105 za d\u0142ugie.", exEn:"These trousers are too long." },
            { pl:"kurtka", en:"jacket (outdoor)", hint:"rzecz. \u017c. \u00b7 kurtka przeciwdeszczowa = a rain jacket.", ex:"Zim\u0105 nie wychodz\u0119 bez kurtki.", exEn:"In winter I don't go out without a jacket." },
            { pl:"buty", en:"shoes", hint:"rzecz., l. mnoga \u00b7 para but\u00f3w = a pair of shoes.", ex:"Potrzebuj\u0119 nowych but\u00f3w na zim\u0119.", exEn:"I need new shoes for winter." },
            { pl:"czapka", en:"(winter/casual) hat, cap", hint:"rzecz. \u017c. \u00b7 vs kapelusz (brimmed hat).", ex:"Za\u0142\u00f3\u017c czapk\u0119, bo zmarzniesz.", exEn:"Put a hat on or you'll freeze." },
            { pl:"wzrost", en:"height", hint:"rzecz. m. \u00b7 wysoki / niski wzrost.", ex:"Jest \u015bredniego wzrostu.", exEn:"He's of medium height." },
            { pl:"szczup\u0142y", en:"slim", hint:"przym. \u00b7 a polite word for thin (\u2260 gruby).", ex:"Jest wysoka i szczup\u0142a.", exEn:"She's tall and slim." },
            { pl:"\u0142ysy", en:"bald", hint:"przym. \u00b7 \u0142ysy jak kolano = completely bald (idiom).", ex:"M\u00f3j dziadek jest \u0142ysy.", exEn:"My grandfather is bald." },
            { pl:"broda", en:"beard", hint:"rzecz. \u017c. \u00b7 also means 'chin'. zapu\u015bci\u0107 brod\u0119 = grow a beard.", ex:"Zapu\u015bci\u0142 brod\u0119 na zim\u0119.", exEn:"He grew a beard for the winter." },
            { pl:"blondyn / blondynka", en:"blond man / woman", hint:"rzecz. \u00b7 also brunet(ka), rudy/rude = redhead.", ex:"M\u00f3j brat to blondyn, a ja jestem brunetk\u0105.", exEn:"My brother is blond and I'm a brunette." },
            { pl:"modny", en:"fashionable", hint:"przym. \u00b7 \u2260 niemodny. modne kolory = trendy colours.", ex:"Ta kurtka jest bardzo modna.", exEn:"This jacket is very fashionable." },
            { pl:"wygodny", en:"comfortable", hint:"przym. \u00b7 o ubraniach i butach. \u2260 niewygodny.", ex:"Wol\u0119 wygodne buty od modnych.", exEn:"I prefer comfortable shoes to fashionable ones." },
            { pl:"w kratk\u0119", en:"checked / plaid", hint:"wzory: w kropki (polka dots), w paski (striped), g\u0142adki (plain).", ex:"Lubi\u0119 koszule w kratk\u0119.", exEn:"I like checked shirts." },
            { pl:"rozmiar", en:"size", hint:"rzecz. m. \u00b7 Jaki rozmiar? = What size?", ex:"Jaki rozmiar pan nosi?", exEn:"What size do you wear, sir?" },
            { pl:"Do twarzy ci w tym", en:"That suits you", hint:"idiom \u00b7 lit. 'it's to your face'. A classic compliment.", ex:"Do twarzy ci w tym kolorze!", exEn:"That colour really suits you!" },
            { pl:"elegancki", en:"elegant, smart", hint:"przym. \u00b7 \u2260 sportowy/codzienny (casual).", ex:"Na rozmow\u0119 o prac\u0119 ubra\u0142em si\u0119 elegancko.", exEn:"I dressed smartly for the job interview." }
          ]
        },
        {
          name: "Opisywanie przesz\u0142o\u015bci",
          emoji: "\u23f0",
          desc: "The past tense: what you did, dates, and memories",
          cards: [
            { pl:"by\u0142em / by\u0142am", en:"I was", hint:"czas przesz\u0142y od 'by\u0107' \u00b7 m: by\u0142em, \u017c: by\u0142am. The most important past form.", ex:"Wczoraj by\u0142em w kinie.", exEn:"Yesterday I was at the cinema." },
            { pl:"mia\u0142em / mia\u0142am", en:"I had", hint:"czas przesz\u0142y od 'mie\u0107' \u00b7 mia\u0142em czas = I had time.", ex:"Nie mia\u0142am wczoraj czasu.", exEn:"I didn't have time yesterday." },
            { pl:"robi\u0142em / zrobi\u0142em", en:"I was doing / I did", hint:"niedok. (proces) vs dok. (wynik) \u00b7 the core aspect pair.", ex:"Robi\u0142em zadanie dwie godziny i w ko\u0144cu je zrobi\u0142em.", exEn:"I was doing the task for two hours and finally finished it." },
            { pl:"poszed\u0142em / posz\u0142am", en:"I went (on foot)", hint:"dok. od 'p\u00f3j\u015b\u0107' \u00b7 m: poszed\u0142em (careful: 'posz\u0142em' is colloquial), \u017c: posz\u0142am.", ex:"Rano poszed\u0142em do sklepu.", exEn:"In the morning I went to the shop." },
            { pl:"widzia\u0142em / widzia\u0142am", en:"I saw", hint:"czas przesz\u0142y od 'widzie\u0107'.", ex:"Widzia\u0142am wczoraj twoj\u0105 siostr\u0119.", exEn:"I saw your sister yesterday." },
            { pl:"m\u00f3wi\u0142em / powiedzia\u0142em", en:"I was saying / I said", hint:"niedok. vs dok. \u00b7 different roots, same meaning pair.", ex:"Ju\u017c ci powiedzia\u0142em, \u017ce nie mog\u0119.", exEn:"I already told you I can't." },
            { pl:"chcia\u0142em / chcia\u0142am", en:"I wanted", hint:"czas. modalny \u00b7 chcia\u0142em zapyta\u0107 = I wanted to ask.", ex:"Chcia\u0142am ci\u0119 o co\u015b zapyta\u0107.", exEn:"I wanted to ask you something." },
            { pl:"musia\u0142em / musia\u0142am", en:"I had to", hint:"czas. modalny \u00b7 + bezokolicznik.", ex:"Musia\u0142em wcze\u015bnie wsta\u0107.", exEn:"I had to get up early." },
            { pl:"mog\u0142em / mog\u0142am", en:"I could / was able to", hint:"czas. modalny od 'm\u00f3c'.", ex:"Nie mog\u0142am spa\u0107 ca\u0142\u0105 noc.", exEn:"I couldn't sleep all night." },
            { pl:"wczoraj", en:"yesterday", hint:"okolicznik czasu \u00b7 przedwczoraj = the day before yesterday.", ex:"Wczoraj pada\u0142 deszcz.", exEn:"It rained yesterday." },
            { pl:"w zesz\u0142ym tygodniu", en:"last week", hint:"+ miejscownik \u00b7 also: w zesz\u0142ym roku / miesi\u0105cu.", ex:"W zesz\u0142ym tygodniu by\u0142em chory.", exEn:"Last week I was ill." },
            { pl:"kiedy by\u0142em dzieckiem", en:"when I was a child", hint:"'dziecko' w narz\u0119dniku \u00b7 a set opener for memories.", ex:"Kiedy by\u0142em dzieckiem, mieszkali\u015bmy na wsi.", exEn:"When I was a child, we lived in the countryside." },
            { pl:"urodzi\u0142em si\u0119", en:"I was born", hint:"czas. zwrotny \u00b7 urodzi\u0142em si\u0119 w 1990 roku.", ex:"Urodzi\u0142am si\u0119 w Gruzji.", exEn:"I was born in Georgia." },
            { pl:"sko\u0144czy\u0142em studia", en:"I graduated", hint:"dok. \u00b7 sko\u0144czy\u0107 = to finish. + biernik (studia).", ex:"Sko\u0144czy\u0142em studia dwa lata temu.", exEn:"I graduated two years ago." },
            { pl:"dwa lata temu", en:"two years ago", hint:"'temu' = ago \u00b7 tydzie\u0144 temu, miesi\u0105c temu, dawno temu.", ex:"Przeprowadzi\u0142em si\u0119 tu dwa lata temu.", exEn:"I moved here two years ago." },
            { pl:"pierwszego maja", en:"on the first of May", hint:"daty: liczebnik porz\u0105dkowy + miesi\u0105c w dope\u0142niaczu.", ex:"Pierwszego maja mamy wolne.", exEn:"On the first of May we have a day off." },
            { pl:"w tysi\u0105c dziewi\u0119\u0107set osiemdziesi\u0105tym pi\u0105tym roku", en:"in 1985", hint:"rok w miejscowniku \u00b7 only the last part declines: ...osiemdziesi\u0105tym pi\u0105tym.", ex:"Urodzi\u0142 si\u0119 w tysi\u0105c dziewi\u0119\u0107set osiemdziesi\u0105tym pi\u0105tym roku.", exEn:"He was born in 1985." },
            { pl:"wtedy", en:"then, at that time", hint:"okolicznik \u00b7 pairs naturally with past-tense stories.", ex:"Wtedy jeszcze nie zna\u0142em polskiego.", exEn:"Back then I didn't know Polish yet." },
            { pl:"na pocz\u0105tku", en:"at the beginning / at first", hint:"\u2260 na ko\u0144cu (at the end). Good story connector.", ex:"Na pocz\u0105tku by\u0142o trudno.", exEn:"At first it was hard." },
            { pl:"potem", en:"then, afterwards", hint:"\u2248 p\u00f3\u017aniej \u00b7 sequencing past events: najpierw... potem...", ex:"Zjed\u0142em \u015bniadanie, a potem poszed\u0142em do pracy.", exEn:"I ate breakfast and then went to work." },
            { pl:"nagle", en:"suddenly", hint:"okolicznik \u00b7 adds drama to a past narrative.", ex:"Nagle zacz\u0105\u0142 pada\u0107 deszcz.", exEn:"Suddenly it started to rain." },
            { pl:"uda\u0142o mi si\u0119", en:"I managed to", hint:"konstrukcja nieosobowa + celownik \u00b7 udało mi się + bezokolicznik.", ex:"W ko\u0144cu uda\u0142o mi si\u0119 znale\u017a\u0107 mieszkanie.", exEn:"I finally managed to find a flat." },
            { pl:"pami\u0119tam, jak", en:"I remember how / when", hint:"'pami\u0119ta\u0107' vs 'pami\u0105tka' (souvenir). Opener for anecdotes.", ex:"Pami\u0119tam, jak pierwszy raz przyjecha\u0142em do Polski.", exEn:"I remember when I first came to Poland." },
            { pl:"zapomnia\u0142em / zapomnia\u0142am", en:"I forgot", hint:"dok. \u00b7 zapomnie\u0107 o czym\u015b = to forget about something.", ex:"Przepraszam, zapomnia\u0142em o spotkaniu.", exEn:"Sorry, I forgot about the meeting." }
          ]
        },
        {
          name: "Ilo\u015bci i pieni\u0105dze",
          emoji: "\uD83D\uDCB0",
          desc: "Quantities, weights, prices, and counting things",
          cards: [
            { pl:"ile kosztuje?", en:"how much does it cost?", hint:"l. poj.; dla l. mnogiej: ile kosztuj\u0105?", ex:"Ile kosztuje ten bilet?", exEn:"How much does this ticket cost?" },
            { pl:"kosztowa\u0107", en:"to cost", hint:"czas. \u00b7 to kosztuje dziesi\u0119\u0107 z\u0142otych.", ex:"Kawa kosztuje pi\u0119tna\u015bcie z\u0142otych.", exEn:"The coffee costs fifteen zloty." },
            { pl:"z\u0142oty (z\u0142)", en:"zloty (Polish currency)", hint:"2-4: z\u0142ote (dwa z\u0142ote); 5+: z\u0142otych (pi\u0119\u0107 z\u0142otych).", ex:"To b\u0119dzie dwadzie\u015bcia z\u0142otych.", exEn:"That'll be twenty zloty." },
            { pl:"grosz", en:"grosz (1/100 of a zloty)", hint:"2-4: grosze; 5+: groszy \u00b7 like cents.", ex:"To kosztuje pi\u0119\u0107 z\u0142otych i pi\u0119\u0107dziesi\u0105t groszy.", exEn:"It costs five zloty fifty." },
            { pl:"drogi", en:"expensive", hint:"przym. \u00b7 \u2260 tani. dro\u017cej = more expensive.", ex:"Ta restauracja jest za droga.", exEn:"This restaurant is too expensive." },
            { pl:"tani", en:"cheap", hint:"przym. \u00b7 \u2260 drogi. taniej = cheaper.", ex:"Na targu owoce s\u0105 ta\u0144sze.", exEn:"At the market fruit is cheaper." },
            { pl:"kilogram (kilo)", en:"kilogram", hint:"+ dope\u0142niacz \u00b7 kilo jab\u0142ek = a kilo of apples.", ex:"Poprosz\u0119 kilo pomidor\u00f3w.", exEn:"A kilo of tomatoes, please." },
            { pl:"deko(gram)", en:"10 grams (Polish 'deka')", hint:"used at the deli: dwadzie\u015bcia deko sera = 200g of cheese.", ex:"Poprosz\u0119 dwadzie\u015bcia deko szynki.", exEn:"200 grams of ham, please." },
            { pl:"litr", en:"litre", hint:"+ dope\u0142niacz \u00b7 litr mleka = a litre of milk.", ex:"Kupi\u0142em dwa litry wody.", exEn:"I bought two litres of water." },
            { pl:"paczka", en:"packet, pack", hint:"+ dope\u0142niacz \u00b7 paczka herbaty = a pack of tea.", ex:"Poprosz\u0119 paczk\u0119 mas\u0142a.", exEn:"A pack of butter, please." },
            { pl:"butelka", en:"bottle", hint:"+ dope\u0142niacz \u00b7 butelka wina = a bottle of wine.", ex:"Wypili\u015bmy ca\u0142\u0105 butelk\u0119 wody.", exEn:"We drank the whole bottle of water." },
            { pl:"s\u0142oik", en:"jar", hint:"+ dope\u0142niacz \u00b7 s\u0142oik miodu = a jar of honey.", ex:"W lod\u00f3wce jest s\u0142oik ogórk\u00f3w.", exEn:"There's a jar of pickles in the fridge." },
            { pl:"kawa\u0142ek", en:"a piece / slice", hint:"+ dope\u0142niacz \u00b7 kawa\u0142ek ciasta = a piece of cake.", ex:"Zjem jeszcze kawa\u0142ek pizzy.", exEn:"I'll have one more slice of pizza." },
            { pl:"para", en:"a pair", hint:"+ dope\u0142niacz l. mnogiej \u00b7 para but\u00f3w, para skarpetek.", ex:"Kupi\u0142am dwie pary but\u00f3w.", exEn:"I bought two pairs of shoes." },
            { pl:"du\u017co / ma\u0142o", en:"a lot / a little", hint:"oba + dope\u0142niacz \u00b7 du\u017co czasu, ma\u0142o pieni\u0119dzy.", ex:"Mam ma\u0142o czasu i du\u017co pracy.", exEn:"I have little time and a lot of work." },
            { pl:"kilka", en:"a few, several", hint:"+ dope\u0142niacz l. mnogiej \u00b7 kilka dni = a few days.", ex:"Zosta\u0142o kilka jab\u0142ek.", exEn:"A few apples are left." },
            { pl:"troch\u0119", en:"a bit, some", hint:"+ dope\u0142niacz \u00b7 troch\u0119 cukru = a bit of sugar.", ex:"Dodaj troch\u0119 soli.", exEn:"Add a bit of salt." },
            { pl:"po\u0142owa", en:"half", hint:"+ dope\u0142niacz \u00b7 po\u0142owa grupy = half the group.", ex:"Zjad\u0142em po\u0142ow\u0119 tortu.", exEn:"I ate half the cake." },
            { pl:"jedno jab\u0142ko, dwa jab\u0142ka, pi\u0119\u0107 jab\u0142ek", en:"1 apple, 2 apples, 5 apples", hint:"the counting pattern: 1 poj. \u00b7 2-4 mianownik mn. \u00b7 5+ dope\u0142niacz mn.", ex:"Mam pi\u0119\u0107 jab\u0142ek i trzy banany.", exEn:"I have five apples and three bananas." },
            { pl:"z\u0142ot\u00f3wka", en:"one-zloty coin / 'a zloty' (colloq.)", hint:"potoczne \u00b7 nie mam ani z\u0142ot\u00f3wki = I don't have a penny.", ex:"Masz mo\u017ce z\u0142ot\u00f3wk\u0119?", exEn:"Do you have a zloty by any chance?" },
            { pl:"reszta", en:"change (money returned)", hint:"rzecz. \u017c. \u00b7 prosz\u0119 zatrzyma\u0107 reszt\u0119 = keep the change.", ex:"Zapomnia\u0142 wyda\u0107 mi reszt\u0119.", exEn:"He forgot to give me the change." },
            { pl:"p\u0142aci\u0107 kart\u0105 / got\u00f3wk\u0105", en:"to pay by card / in cash", hint:"narz\u0119dnik \u00b7 Czy mog\u0119 zap\u0142aci\u0107 kart\u0105?", ex:"Wol\u0119 p\u0142aci\u0107 kart\u0105 ni\u017c got\u00f3wk\u0105.", exEn:"I prefer to pay by card than in cash." },
            { pl:"przecena / wyprzeda\u017c", en:"markdown / sale", hint:"na wyprzeda\u017cy = on sale. -50% = pi\u0119\u0107dziesi\u0105t procent taniej.", ex:"Kupi\u0142am t\u0119 kurtk\u0119 na wyprzeda\u017cy.", exEn:"I bought this jacket on sale." },
            { pl:"drobne", en:"small change / coins", hint:"rzecz., l. mnoga \u00b7 nie mam drobnych = I have no change.", ex:"Przepraszam, nie mam drobnych.", exEn:"Sorry, I don't have any change." }
          ]
        },
        {
          name: "Kierunki i orientacja",
          emoji: "\uD83E\uDDED",
          desc: "Asking for directions and finding your way in a city",
          cards: [
            { pl:"Jak dojecha\u0107 do...?", en:"How do I get to...? (by transport)", hint:"+ dope\u0142niacz \u00b7 Jak dojecha\u0107 do centrum?", ex:"Przepraszam, jak dojecha\u0107 do dworca?", exEn:"Excuse me, how do I get to the station?" },
            { pl:"Jak doj\u015b\u0107 do...?", en:"How do I get to...? (on foot)", hint:"+ dope\u0142niacz \u00b7 doj\u015b\u0107 = reach on foot, dojecha\u0107 = by vehicle.", ex:"Jak doj\u015b\u0107 do muzeum st\u0105d?", exEn:"How do I walk to the museum from here?" },
            { pl:"Gdzie jest...?", en:"Where is...?", hint:"the simplest opener \u00b7 Gdzie jest najbli\u017cszy bankomat?", ex:"Gdzie jest najbli\u017csza apteka?", exEn:"Where is the nearest pharmacy?" },
            { pl:"prosto", en:"straight ahead", hint:"okolicznik \u00b7 id\u017a prosto = go straight.", ex:"Prosz\u0119 i\u015b\u0107 prosto do \u015bwiate\u0142.", exEn:"Go straight ahead to the traffic lights." },
            { pl:"skr\u0119ci\u0107 w lewo / w prawo", en:"to turn left / right", hint:"dok. + biernik \u00b7 w lewo = to the left.", ex:"Na rogu prosz\u0119 skr\u0119ci\u0107 w prawo.", exEn:"At the corner, turn right." },
            { pl:"i\u015b\u0107 wzd\u0142u\u017c", en:"to go along", hint:"+ dope\u0142niacz \u00b7 wzd\u0142u\u017c ulicy = along the street.", ex:"Prosz\u0119 i\u015b\u0107 wzd\u0142u\u017c rzeki.", exEn:"Go along the river." },
            { pl:"min\u0105\u0107", en:"to pass / go past", hint:"dok. + biernik \u00b7 min\u0105\u0107 ko\u015bci\u00f3\u0142 = pass the church.", ex:"Prosz\u0119 min\u0105\u0107 park i skr\u0119ci\u0107 w lewo.", exEn:"Go past the park and turn left." },
            { pl:"obok", en:"next to, beside", hint:"+ dope\u0142niacz \u00b7 obok poczty = next to the post office.", ex:"Sklep jest obok apteki.", exEn:"The shop is next to the pharmacy." },
            { pl:"naprzeciwko", en:"opposite, across from", hint:"+ dope\u0142niacz \u00b7 naprzeciwko dworca.", ex:"Hotel jest naprzeciwko parku.", exEn:"The hotel is opposite the park." },
            { pl:"mi\u0119dzy", en:"between", hint:"+ narz\u0119dnik \u00b7 mi\u0119dzy bankiem a poczt\u0105.", ex:"Kawiarnia jest mi\u0119dzy bankiem a ksi\u0119garni\u0105.", exEn:"The cafe is between the bank and the bookshop." },
            { pl:"za", en:"behind / beyond", hint:"+ narz\u0119dnik (miejsce) \u00b7 za rogiem = around the corner.", ex:"Parking jest za budynkiem.", exEn:"The car park is behind the building." },
            { pl:"przed", en:"in front of", hint:"+ narz\u0119dnik \u00b7 przed wej\u015bciem = in front of the entrance.", ex:"Spotkajmy si\u0119 przed kinem.", exEn:"Let's meet in front of the cinema." },
            { pl:"na rogu", en:"on the corner", hint:"miejscownik \u00b7 na rogu ulicy = on the street corner.", ex:"Kwiaciarnia jest na rogu.", exEn:"The florist is on the corner." },
            { pl:"skrzy\u017cowanie", en:"intersection, crossroads", hint:"rzecz. n. \u00b7 na skrzy\u017cowaniu = at the intersection.", ex:"Na skrzy\u017cowaniu prosz\u0119 skr\u0119ci\u0107 w lewo.", exEn:"At the intersection, turn left." },
            { pl:"\u015bwiat\u0142a", en:"traffic lights", hint:"rzecz., l. mnoga \u00b7 na \u015bwiat\u0142ach = at the lights.", ex:"Prosz\u0119 skr\u0119ci\u0107 na drugich \u015bwiat\u0142ach.", exEn:"Turn at the second set of lights." },
            { pl:"przej\u015bcie dla pieszych", en:"pedestrian crossing", hint:"rzecz. \u00b7 pieszy = pedestrian.", ex:"Przejd\u017a przez przej\u015bcie dla pieszych.", exEn:"Cross at the pedestrian crossing." },
            { pl:"blisko / daleko", en:"near / far", hint:"oba + dope\u0142niacz \u00b7 blisko centrum, daleko st\u0105d.", ex:"To bardzo blisko, pi\u0119\u0107 minut st\u0105d.", exEn:"It's very close, five minutes from here." },
            { pl:"po lewej / prawej stronie", en:"on the left / right side", hint:"miejscownik \u00b7 sklep b\u0119dzie po prawej stronie.", ex:"Restauracja jest po lewej stronie.", exEn:"The restaurant is on the left side." },
            { pl:"st\u0105d", en:"from here", hint:"okolicznik \u00b7 \u2260 dot\u0105d (up to here), tam (there).", ex:"Jak daleko st\u0105d do centrum?", exEn:"How far is it from here to the centre?" },
            { pl:"zab\u0142\u0105dzi\u0107", en:"to get lost", hint:"dok. \u00b7 zab\u0142\u0105dzi\u0142em = I've got lost.", ex:"Chyba zab\u0142\u0105dzi\u0142em, gdzie jestem?", exEn:"I think I'm lost - where am I?" },
            { pl:"pieszo / na piechot\u0119", en:"on foot", hint:"i\u015b\u0107 pieszo \u00b7 both mean 'walking'.", ex:"Wol\u0119 i\u015b\u0107 pieszo ni\u017c jecha\u0107 autobusem.", exEn:"I prefer to walk than take the bus." },
            { pl:"mapa / nawigacja", en:"map / (GPS) navigation", hint:"rzecz. \u017c. \u00b7 w\u0142\u0105czy\u0107 nawigacj\u0119 = turn on the GPS.", ex:"Bez nawigacji na pewno bym zab\u0142\u0105dzi\u0142.", exEn:"Without the GPS I'd definitely get lost." }
          ]
        }
      ]
    }
  );
})();
