/* Po polsku - lesson data: B1
   Registered onto window.PP_LEVELS by index.html (loaded in order).
   Safe to edit this file alone; a syntax error here shows a load
   message instead of breaking the app engine. */
(function(){
  window.PP_LEVELS = window.PP_LEVELS || [];
  window.PP_LEVELS.push(
  { id:"b1",
      level: "B1",
      blurb: "Everyday life",
      topics: [
        { id:"b1-getting-things-done",
          name: "Załatwianie spraw",
          emoji: "📋",
          desc: "Adulting: errands, services, and solving problems",
          cards: [
            { id:"b1-getting-things-done-001", pl:"załatwiać sprawy", en:"to run errands", pair:"za\u0142atwia\u0107 / za\u0142atwi\u0107 sprawy", hint:"Verb phrase.", ex:"Muszę dzisiaj załatwić kilka spraw na mieście.", exEn:"I have to run a few errands in town today." },
            { id:"b1-getting-things-done-002", pl:"awaria", en:"breakdown / malfunction", hint:"Feminine noun.", ex:"Mamy awarię prądu w całym budynku.", exEn:"We have a power outage in the whole building." },
            { id:"b1-getting-things-done-003", pl:"reklamacja", en:"complaint / return", hint:"'Złożyć reklamację' = to make a complaint. A woman says: Chciałabym.", ex:"Chciałbym złożyć reklamację, te buty są wadliwe.", exEn:"I'd like to make a complaint, these shoes are faulty." },
            { id:"b1-getting-things-done-004", pl:"dowód zakupu", en:"proof of purchase", hint:"Usually a receipt (paragon) or invoice (faktura).", ex:"Czy ma pan dowód zakupu?", exEn:"Do you have proof of purchase?" },
            { id:"b1-getting-things-done-005", pl:"gwarancja", en:"warranty", hint:"Feminine noun.", ex:"Ten telewizor jest jeszcze na gwarancji.", exEn:"This TV is still under warranty." },
            { id:"b1-getting-things-done-006", pl:"przegląd", en:"inspection / service", hint:"Often used for cars.", ex:"Muszę umówić się na przegląd samochodu.", exEn:"I need to book a car service." },
            { id:"b1-getting-things-done-007", pl:"mechanik", en:"mechanic", hint:"Masculine noun.", ex:"Samochód wydaje dziwne dźwięki, jadę do mechanika.", exEn:"The car is making weird noises, I'm going to the mechanic." },
            { id:"b1-getting-things-done-008", pl:"hydraulik", en:"plumber", hint:"Masculine noun.", ex:"Kran przecieka, musimy wezwać hydraulika.", exEn:"The tap is leaking, we need to call a plumber." },
            { id:"b1-getting-things-done-009", pl:"ubezpieczenie", en:"insurance", hint:"Neuter noun.", ex:"Czy to ubezpieczenie pokrywa koszty leczenia?", exEn:"Does this insurance cover medical costs?" },
            { id:"b1-getting-things-done-010", pl:"podpisać umowę", en:"to sign a contract", pair:"podpisywa\u0107 / podpisa\u0107 umow\u0119", hint:"Verb phrase.", ex:"Zanim wynajmiesz mieszkanie, musisz podpisać umowę.", exEn:"Before you rent the flat, you must sign a contract." },
            { id:"b1-getting-things-done-011", pl:"obciąć włosy", en:"to get a haircut", pair:"obcina\u0107 / obci\u0105\u0107 w\u0142osy", hint:"Literally 'to cut hair'.", ex:"Idę do fryzjera obciąć włosy.", exEn:"I'm going to the hairdresser to get a haircut." },
            { id:"b1-getting-things-done-012", pl:"odebrać", en:"to pick up / collect", pair:"odbiera\u0107 / odebra\u0107", hint:"Verb. 'Odbieram' = I pick up.", ex:"Muszę odebrać paczkę z paczkomatu.", exEn:"I have to pick up a parcel from the locker." },
            { id:"b1-getting-things-done-013", pl:"termin ważności", en:"expiration date", hint:"Masculine phrase.", ex:"Sprawdź termin ważności na opakowaniu.", exEn:"Check the expiration date on the packaging." },
            { id:"b1-getting-things-done-014", pl:"opłata", en:"fee / charge", hint:"Feminine noun.", ex:"Czy jest jakaś dodatkowa opłata za dostawę?", exEn:"Is there any additional fee for delivery?" },
            { id:"b1-getting-things-done-015", pl:"odwołać wizytę", en:"to cancel an appointment", pair:"odwo\u0142ywa\u0107 / odwo\u0142a\u0107 wizyt\u0119", hint:"Verb phrase.", ex:"Niestety muszę odwołać naszą dzisiejszą wizytę.", exEn:"Unfortunately, I have to cancel our appointment today." }
          ]
        },
        { id:"b1-expressing-opinions",
          name: "Wyrażanie opinii",
          emoji: "🗣️",
          desc: "Debating, agreeing, and polite disagreement",
          cards: [
            { id:"b1-expressing-opinions-001", cardType:"template", pl:"Moim zdaniem...", en:"In my opinion...", hint:"The standard way to introduce your view.", ex:"Moim zdaniem to nie jest dobry pomysł.", exEn:"In my opinion, this is not a good idea.", pattern:"Moim zdaniem {opinia}." },
            { id:"b1-expressing-opinions-002", pl:"Zgadzam się z tobą", en:"I agree with you", pair:"zgadza\u0107 si\u0119 / zgodzi\u0107 si\u0119", hint:"Verb: 'Zgadzać się'.", ex:"Zgadzam się z tobą w stu procentach.", exEn:"I agree with you one hundred percent." },
            { id:"b1-expressing-opinions-003", pl:"Nie masz racji", en:"You are wrong", hint:"Literally: 'You do not have rightness'.", ex:"Przepraszam, ale zupełnie nie masz racji.", exEn:"Sorry, but you are completely wrong." },
            { id:"b1-expressing-opinions-004", cardType:"template", pl:"Szczerze mówiąc...", en:"To be honest...", hint:"Very common filler phrase.", ex:"Szczerze mówiąc, nie podoba mi się ten film.", exEn:"To be honest, I don't like this movie.", pattern:"Szczerze mówiąc, {opinia}." },
            { id:"b1-expressing-opinions-005", cardType:"template", pl:"Z jednej strony...", en:"On one hand...", hint:"Usually followed by 'Z drugiej strony...'", ex:"Z jednej strony to fajne, ale z drugiej za drogie.", exEn:"On one hand it's cool, but on the other it's too expensive.", pattern:"Z jednej strony {A}, z drugiej strony {B}." },
            { id:"b1-expressing-opinions-006", cardType:"template", pl:"Uważam, że...", en:"I believe / consider that...", hint:"More formal than 'Myślę, że'.", ex:"Uważam, że powinniśmy poczekać.", exEn:"I believe that we should wait.", pattern:"Uważam, że {opinia}." },
            { id:"b1-expressing-opinions-007", pl:"Dokładnie!", en:"Exactly!", hint:"Used to strongly agree with someone.", ex:"Dokładnie! O to mi właśnie chodziło.", exEn:"Exactly! That's exactly what I meant." },
            { id:"b1-expressing-opinions-008", pl:"W żadnym wypadku", en:"No way / Under no circumstances", hint:"Strong disagreement.", ex:"W żadnym wypadku się na to nie zgodzę.", exEn:"Under no circumstances will I agree to this." },
            { id:"b1-expressing-opinions-009", pl:"Co o tym myślisz?", en:"What do you think about it?", hint:"Asking for someone's opinion.", ex:"Mam nowy plan. Co o tym myślisz?", exEn:"I have a new plan. What do you think about it?" },
            { id:"b1-expressing-opinions-010", pl:"Punkt widzenia", en:"Point of view", hint:"Masculine phrase.", ex:"Rozumiem twój punkt widzenia, ale się nie zgadzam.", exEn:"I understand your point of view, but I disagree." },
            { id:"b1-expressing-opinions-011", pl:"Wątpię", en:"I doubt it", hint:"Verb: 'Wątpić'.", ex:"Wątpię, czy zdążymy na czas.", exEn:"I doubt we will make it on time." },
            { id:"b1-expressing-opinions-012", pl:"Przekonać", en:"To convince", pair:"przekonywa\u0107 / przekona\u0107", hint:"Verb.", ex:"Spróbuję go do tego przekonać.", exEn:"I will try to convince him to do it." },
            { id:"b1-expressing-opinions-013", pl:"Zależy", en:"It depends", hint:"Often 'To zależy'.", ex:"Czy pójdziemy na spacer? To zależy od pogody.", exEn:"Will we go for a walk? It depends on the weather." },
            { id:"b1-expressing-opinions-014", pl:"Według mnie", en:"The way I see it", hint:"Alternative to 'Moim zdaniem'.", ex:"Według mnie ten projekt ma duży potencjał.", exEn:"The way I see it, this project has great potential." },
            { id:"b1-expressing-opinions-015", pl:"Nie mam zdania", en:"I don't have an opinion", hint:"When you want to stay neutral.", ex:"Szczerze mówiąc, nie mam zdania na ten temat.", exEn:"To be honest, I don't have an opinion on this topic." }
          ]
        },
        { id:"b1-money-finance",
          name: "Pieniądze i finanse",
          emoji: "💰",
          desc: "Budgets, banking, and managing your money",
          cards: [
            { id:"b1-money-finance-001", pl:"konto bankowe", en:"bank account", hint:"Neuter phrase.", ex:"Chcę otworzyć nowe konto bankowe.", exEn:"I want to open a new bank account." },
            { id:"b1-money-finance-002", pl:"przelew", en:"bank transfer", hint:"Masculine noun. BLIK is Poland's mobile payment system; 'przelew na telefon BLIK' is the standard name for a transfer to a phone number.", ex:"Zrobię ci przelew na telefon BLIK.", exEn:"I'll send you a BLIK transfer to your phone number." },
            { id:"b1-money-finance-003", pl:"kredyt hipoteczny", en:"mortgage", hint:"Masculine phrase.", ex:"Mamy kredyt hipoteczny na 30 lat.", exEn:"We have a 30-year mortgage." },
            { id:"b1-money-finance-004", pl:"oszczędzać", en:"to save money", pair:"oszcz\u0119dza\u0107 / zaoszcz\u0119dzi\u0107", hint:"Verb.", ex:"Staram się oszczędzać na wakacje.", exEn:"I'm trying to save up for a holiday." },
            { id:"b1-money-finance-005", pl:"budżet", en:"budget", hint:"Masculine noun.", ex:"Musimy zaplanować nasz miesięczny budżet.", exEn:"We need to plan our monthly budget." },
            { id:"b1-money-finance-006", pl:"zarabiać", en:"to earn", pair:"zarabia\u0107 / zarobi\u0107", hint:"Verb. 'Zarabiam' = I earn. A woman says: Chciałabym.", ex:"Chciałbym zarabiać więcej pieniędzy.", exEn:"I would like to earn more money." },
            { id:"b1-money-finance-007", pl:"wydawać", en:"to spend (money)", pair:"wydawa\u0107 / wyda\u0107", hint:"Verb. 'Wydaję' = I spend.", ex:"Ona wydaje dużo na ubrania.", exEn:"She spends a lot on clothes." },
            { id:"b1-money-finance-008", pl:"dług", en:"debt", hint:"Masculine noun. When the owner is the subject, Polish uses 'swój', not 'mój'. A woman says: Spłaciłam.", ex:"Spłaciłem wczoraj cały swój dług.", exEn:"I paid off my entire debt yesterday." },
            { id:"b1-money-finance-009", pl:"pożyczyć", en:"to borrow / to lend", pair:"po\u017cycza\u0107 / po\u017cyczy\u0107", hint:"Context determines which one it is.", ex:"Czy możesz mi pożyczyć stówę?", exEn:"Can you lend me a hundred (zlotys)?" },
            { id:"b1-money-finance-010", pl:"rata", en:"installment", hint:"Feminine noun.", ex:"Moja miesięczna rata za samochód jest wysoka.", exEn:"My monthly car installment is high." },
            { id:"b1-money-finance-011", pl:"wypłacić gotówkę", en:"to withdraw cash", pair:"wyp\u0142aca\u0107 / wyp\u0142aci\u0107 got\u00f3wk\u0119", hint:"Verb phrase.", ex:"Muszę wypłacić gotówkę z bankomatu.", exEn:"I need to withdraw cash from the ATM." },
            { id:"b1-money-finance-012", pl:"odsetki", en:"interest (financial)", hint:"Plural noun. For a loan's rate the precise word is 'oprocentowanie'.", ex:"Kredyt ma bardzo wysokie odsetki.", exEn:"The loan has very high interest." },
            { id:"b1-money-finance-013", pl:"płacić rachunki", en:"to pay bills", pair:"p\u0142aci\u0107 / zap\u0142aci\u0107 rachunki", hint:"Verb phrase.", ex:"Nienawidzę płacić rachunków na początku miesiąca.", exEn:"I hate paying bills at the beginning of the month." },
            { id:"b1-money-finance-014", pl:"inwestować", en:"to invest", pair:"inwestowa\u0107 / zainwestowa\u0107", hint:"Verb. A woman says: Zaczęłam.", ex:"Zacząłem inwestować na giełdzie.", exEn:"I started investing in the stock market." },
            { id:"b1-money-finance-015", pl:"prowizja", en:"commission / fee", hint:"Feminine noun.", ex:"Bank pobiera prowizję za każdą transakcję.", exEn:"The bank charges a fee for every transaction." }
          ]
        },
        { id:"b1-career",
          name: "Życie zawodowe i kariera",
          emoji: "💼",
          desc: "Advanced corporate Polish and job interviews",
          cards: [
            { id:"b1-career-001", pl:"Przejdźmy do rzeczy", en:"Let's get to the point", hint:"Very useful for leading meetings.", ex:"Nie mamy dużo czasu, przejdźmy do rzeczy.", exEn:"We don't have much time, let's get to the point." },
            { id:"b1-career-002", pl:"stanowisko", en:"position / role", hint:"Neuter noun.", ex:"Aplikuję na stanowisko menedżera.", exEn:"I am applying for a manager position." },
            { id:"b1-career-003", pl:"wymagania", en:"requirements", hint:"Plural noun.", ex:"Spełniam wszystkie wymagania z ogłoszenia.", exEn:"I meet all the requirements from the job ad." },
            { id:"b1-career-004", pl:"zakres obowiązków", en:"scope of duties", hint:"Masculine phrase.", ex:"Jaki jest dokładny zakres moich obowiązków?", exEn:"What is the exact scope of my duties?" },
            { id:"b1-career-005", pl:"awans", en:"promotion", hint:"Masculine noun. A woman says: Pracowałam / dostałam.", ex:"Pracowałem ciężko i dostałem awans.", exEn:"I worked hard and got a promotion." },
            { id:"b1-career-006", pl:"podwyżka", en:"raise / pay rise", hint:"Feminine noun.", ex:"Będę prosić szefa o podwyżkę.", exEn:"I will ask my boss for a raise." },
            { id:"b1-career-007", pl:"nadgodziny", en:"overtime", hint:"Plural noun.", ex:"W tym tygodniu robię nadgodziny.", exEn:"I'm doing overtime this week." },
            { id:"b1-career-008", pl:"zatrudnić", en:"to hire", pair:"zatrudnia\u0107 / zatrudni\u0107", hint:"Verb.", ex:"Firma planuje zatrudnić nowe osoby.", exEn:"The company plans to hire new people." },
            { id:"b1-career-009", pl:"zwolnić się", en:"to quit / resign", pair:"zwalnia\u0107 si\u0119 / zwolni\u0107 si\u0119", hint:"Reflexive verb.", ex:"Nie lubię tej pracy, chyba się zwolnię.", exEn:"I don't like this job, I think I'll quit." },
            { id:"b1-career-010", pl:"bezrobocie", en:"unemployment", hint:"Neuter noun.", ex:"Bezrobocie w tym regionie jest niskie.", exEn:"Unemployment in this region is low." },
            { id:"b1-career-011", pl:"CV", en:"CV / résumé", acceptedAnswers:["życiorys"], variants:[{form:"życiorys",label:"synonym"}], hint:"CV is usually pronounced the English way: 'si-wi'. Polish drops the possessive here - 'Wysłałem CV', not 'moje CV'. A woman says: Wysłałam.", ex:"Wysłałem CV do trzech firm.", exEn:"I sent my CV to three companies." },
            { id:"b1-career-012", pl:"list motywacyjny", en:"cover letter", hint:"Masculine phrase.", ex:"Czy muszę pisać list motywacyjny?", exEn:"Do I have to write a cover letter?" },
            { id:"b1-career-013", pl:"negocjować", en:"to negotiate", pair:"negocjowa\u0107 / wynegocjowa\u0107", hint:"Verb.", ex:"Chcę negocjować warunki umowy.", exEn:"I want to negotiate the terms of the contract." },
            { id:"b1-career-014", pl:"cel zawodowy", en:"career goal", hint:"Masculine phrase.", ex:"Moim celem zawodowym jest zostać ekspertem w swojej dziedzinie.", exEn:"My career goal is to become an expert in my field." },
            { id:"b1-career-015", pl:"współpraca", en:"cooperation", hint:"Feminine noun.", ex:"Dziękuję wszystkim za owocną współpracę.", exEn:"Thank you all for the fruitful cooperation." }
          ]
        },
        { id:"b1-character-emotions",
          name: "Charakter i emocje",
          emoji: "🎭",
          desc: "Describing personality traits and complex feelings",
          cards: [
            { id:"b1-character-emotions-001", pl:"zmienić zdanie", en:"to change one's mind", pair:"zmienia\u0107 / zmieni\u0107 zdanie", hint:"Verb phrase. A woman says: Miałam / zmieniłam.", ex:"Miałem tam iść, ale zmieniłem zdanie.", exEn:"I was going to go there, but I changed my mind." },
            { id:"b1-character-emotions-002", pl:"mieć poczucie humoru", en:"to have a sense of humour", hint:"Verb phrase.", ex:"On ma świetne poczucie humoru.", exEn:"He has a great sense of humour." },
            { id:"b1-character-emotions-003", pl:"uparty", en:"stubborn", hint:"Adjective.", ex:"Mój brat jest bardzo uparty i nigdy nie słucha.", exEn:"My brother is very stubborn and never listens." },
            { id:"b1-character-emotions-004", pl:"szczery", en:"honest / sincere", hint:"Adjective.", ex:"Będę z tobą całkowicie szczery.", exEn:"I will be completely honest with you." },
            { id:"b1-character-emotions-005", pl:"leniwy", en:"lazy", hint:"Adjective.", ex:"Dzisiaj czuję się bardzo leniwy.", exEn:"Today I feel very lazy." },
            { id:"b1-character-emotions-006", pl:"pracowity", en:"hardworking", hint:"Adjective.", ex:"To jest nasz najbardziej pracowity pracownik.", exEn:"This is our most hardworking employee." },
            { id:"b1-character-emotions-007", pl:"cierpliwy", en:"patient", hint:"Adjective.", ex:"Musisz być cierpliwy, to wymaga czasu.", exEn:"You must be patient, this requires time." },
            { id:"b1-character-emotions-008", pl:"denerwować się", en:"to get nervous / angry", pair:"denerwowa\u0107 si\u0119 / zdenerwowa\u0107 si\u0119", hint:"Reflexive verb.", ex:"Proszę się nie denerwować, wszystko naprawimy.", exEn:"Please don't get nervous, we will fix everything." },
            { id:"b1-character-emotions-009", pl:"stres", en:"stress", hint:"Masculine noun.", ex:"Mam za dużo stresu w pracy.", exEn:"I have too much stress at work." },
            { id:"b1-character-emotions-010", pl:"bać się", en:"to be afraid", pair:"ba\u0107 si\u0119 (impf only)", hint:"Verb. Followed by Genitive case.", ex:"Boję się pająków i latania samolotem.", exEn:"I am afraid of spiders and flying in planes." },
            { id:"b1-character-emotions-011", pl:"cieszyć się", en:"to be glad / happy", pair:"cieszy\u0107 si\u0119 / ucieszy\u0107 si\u0119", hint:"Reflexive verb.", ex:"Bardzo się cieszę, że cię widzę.", exEn:"I am very glad to see you." },
            { id:"b1-character-emotions-012", pl:"być z siebie dumnym", en:"to be proud of oneself", hint:"Verb phrase. A woman says: Zdałam / dumna.", ex:"Zdałem ten trudny egzamin, jestem z siebie dumny.", exEn:"I passed this difficult exam, I'm proud of myself." },
            { id:"b1-character-emotions-013", pl:"zadowolony", en:"satisfied / pleased", hint:"Adjective.", ex:"Jestem bardzo zadowolony z wyników.", exEn:"I am very pleased with the results." },
            { id:"b1-character-emotions-014", pl:"wrażliwy", en:"sensitive", hint:"Adjective.", ex:"Ona jest bardzo wrażliwa na krytykę.", exEn:"She is very sensitive to criticism." },
            { id:"b1-character-emotions-015", pl:"pewny siebie", en:"self-confident", hint:"Adjective phrase.", ex:"Dobry lider powinien być pewny siebie.", exEn:"A good leader should be self-confident." },
            { id:"b1-character-emotions-016", pl:"frustracja", en:"frustration", hint:"Feminine noun. 'sfrustrowany' = frustrated.", ex:"Czuję ogromną frustrację w tej pracy.", exEn:"I feel enormous frustration at this job." },
            { id:"b1-character-emotions-017", pl:"rozczarowanie", en:"disappointment", hint:"Neuter noun. 'rozczarowany' = disappointed.", ex:"Nie kryła rozczarowania wynikiem.", exEn:"She didn't hide her disappointment at the result." },
            { id:"b1-character-emotions-018", pl:"podekscytowany", en:"excited", hint:"Adjective. 'ekscytować się czymś' = to be excited about.", ex:"Jestem podekscytowany nową pracą.", exEn:"I'm excited about the new job. A woman: podekscytowana." },
            { id:"b1-character-emotions-019", pl:"zazdrość", en:"jealousy / envy", hint:"Feminine noun. 'zazdrosny o kogoś' = jealous of someone.", ex:"Zazdrość niszczy wiele związków.", exEn:"Jealousy destroys many relationships." },
            { id:"b1-character-emotions-020", pl:"ulga", en:"relief", hint:"Feminine noun. 'z ulgą' = with relief.", ex:"Odetchnąłem z ulgą, gdy to się skończyło.", exEn:"I breathed a sigh of relief when it ended. A woman: odetchnęłam." },
            { id:"b1-character-emotions-021", pl:"wzruszony", en:"moved / touched", hint:"Adjective. 'wzruszyć się' = to be moved (to tears).", ex:"Byłam wzruszona jego przemową.", exEn:"I was moved by his speech. A man: byłem wzruszony." },
            { id:"b1-character-emotions-022", pl:"zdenerwowany", en:"upset / annoyed / nervous", hint:"Adjective. Covers a wide band of agitation.", ex:"Wyglądasz na zdenerwowanego, co się stało?", exEn:"You look upset, what happened?" },
            { id:"b1-character-emotions-023", pl:"tęsknota", en:"longing / yearning", hint:"Feminine noun - a deep, often bittersweet missing. Verb: 'tęsknić'.", ex:"Poczułem tęsknotę za domem.", exEn:"I felt a longing for home. A woman: poczułam." }
          ]
        },
        { id:"b1-media-technology",
          name: "Media i technologia",
          emoji: "📱",
          desc: "Digital life, internet, and social media",
          cards: [
            { id:"b1-media-technology-001", pl:"aplikacja", en:"app / application", hint:"Feminine noun.", ex:"Używam tej aplikacji do nauki języków.", exEn:"I use this app for learning languages." },
            { id:"b1-media-technology-002", pl:"ściągnąć", en:"to download", pair:"\u015bci\u0105ga\u0107 / \u015bci\u0105gn\u0105\u0107", hint:"Informal, very common.", ex:"Musisz ściągnąć nowy plik z internetu.", exEn:"You have to download a new file from the internet." },
            { id:"b1-media-technology-003", pl:"wyszukiwarka", en:"search engine", hint:"Feminine noun.", ex:"Najpopularniejsza wyszukiwarka to Google.", exEn:"The most popular search engine is Google." },
            { id:"b1-media-technology-004", pl:"źródło informacji", en:"source of information", hint:"Neuter phrase.", ex:"Internet to potężne źródło informacji.", exEn:"The internet is a powerful source of information." },
            { id:"b1-media-technology-005", pl:"hasło", en:"password", hint:"Neuter noun. A woman says: Zapomniałam.", ex:"Zapomniałem hasła do mojego konta.", exEn:"I forgot the password to my account." },
            { id:"b1-media-technology-006", pl:"zalogować się", en:"to log in", pair:"logowa\u0107 si\u0119 / zalogowa\u0107 si\u0119", hint:"Reflexive verb.", ex:"Musisz się zalogować, żeby zobaczyć zdjęcia.", exEn:"You must log in to see the photos." },
            { id:"b1-media-technology-007", pl:"wylogować się", en:"to log out", pair:"wylogowywa\u0107 si\u0119 / wylogowa\u0107 si\u0119", hint:"Reflexive verb.", ex:"Pamiętaj, żeby się wylogować z aplikacji bankowej.", exEn:"Remember to log out of the banking app." },
            { id:"b1-media-technology-008", pl:"udostępnić", en:"to share (online)", pair:"udost\u0119pnia\u0107 / udost\u0119pni\u0107", hint:"Verb.", ex:"Udostępnij ten artykuł na swoim profilu.", exEn:"Share this article on your profile." },
            { id:"b1-media-technology-009", pl:"ekran", en:"screen", hint:"Masculine noun.", ex:"Mój telefon ma pęknięty ekran.", exEn:"My phone has a cracked screen." },
            { id:"b1-media-technology-010", pl:"plik", en:"file", hint:"Masculine noun. A woman says: Wysłałam.", ex:"Wysłałem ci plik na maila.", exEn:"I sent you the file via email." },
            { id:"b1-media-technology-011", pl:"link", en:"link", hint:"Masculine noun.", ex:"Kliknij w ten link, żeby otworzyć stronę.", exEn:"Click this link to open the page." },
            { id:"b1-media-technology-012", pl:"wiadomość", en:"message", hint:"Feminine noun. A woman says: Dostałam.", ex:"Dostałem od niej dziwną wiadomość.", exEn:"I received a weird message from her." },
            { id:"b1-media-technology-013", pl:"powiadomienie", en:"notification", hint:"Neuter noun. A woman says: Wyłączyłam.", ex:"Wyłączyłem powiadomienia w telefonie.", exEn:"I turned off notifications on my phone." },
            { id:"b1-media-technology-014", pl:"sieć", en:"network / the web", hint:"Feminine noun. 'W sieci' = on the web.", ex:"W sieci można znaleźć wszystko.", exEn:"You can find everything on the web." },
            { id:"b1-media-technology-015", pl:"urządzenie", en:"device", hint:"Neuter noun.", ex:"Możesz podłączyć dwa urządzenia naraz.", exEn:"You can connect two devices at once." }
          ]
        },
        { id:"b1-healthy-lifestyle",
          name: "Zdrowy styl życia",
          emoji: "🥗",
          desc: "Diet, fitness, and looking after your mind",
          cards: [
            { id:"b1-healthy-lifestyle-001", pl:"zdrowy styl życia", en:"healthy lifestyle", hint:"Masculine phrase. The topic in a nutshell.", ex:"Coraz więcej osób prowadzi zdrowy styl życia.", exEn:"More and more people live a healthy lifestyle." },
            { id:"b1-healthy-lifestyle-002", pl:"dieta", en:"diet", hint:"Feminine noun. 'być na diecie' = to be on a diet.", ex:"Jestem na diecie od miesiąca.", exEn:"I've been on a diet for a month." },
            { id:"b1-healthy-lifestyle-003", pl:"odżywiać się", en:"to eat / to nourish oneself", pair:"odżywiać się (impf only)", hint:"'zdrowo się odżywiać' = to eat healthily.", ex:"Staram się zdrowo odżywiać.", exEn:"I try to eat healthily." },
            { id:"b1-healthy-lifestyle-004", pl:"zdrowe jedzenie", en:"healthy food", hint:"Neuter phrase. Opposite: 'niezdrowe jedzenie'.", ex:"Zdrowe jedzenie nie musi być drogie.", exEn:"Healthy food doesn't have to be expensive." },
            { id:"b1-healthy-lifestyle-005", pl:"kalorie", en:"calories", hint:"Plural. 'liczyć kalorie' = to count calories.", ex:"Nie liczę kalorii, ale uważam, co jem.", exEn:"I don't count calories, but I watch what I eat." },
            { id:"b1-healthy-lifestyle-006", pl:"schudnąć", en:"to lose weight", pair:"chudnąć / schudnąć", hint:"Opposite: 'przytyć' (to gain weight).", ex:"Chcę schudnąć pięć kilogramów.", exEn:"I want to lose five kilograms." },
            { id:"b1-healthy-lifestyle-007", pl:"ćwiczyć", en:"to exercise / to work out", pair:"ćwiczyć / poćwiczyć", hint:"ćwiczę, ćwiczysz. Also 'to practise'.", ex:"Ćwiczę trzy razy w tygodniu.", exEn:"I work out three times a week." },
            { id:"b1-healthy-lifestyle-008", pl:"trening", en:"workout / training", hint:"Masculine noun. 'trenować' = to train.", ex:"Po treningu jestem wykończony.", exEn:"After a workout I'm exhausted. A woman: wykończona." },
            { id:"b1-healthy-lifestyle-009", pl:"siłownia", en:"gym", hint:"Feminine noun. 'karnet na siłownię' = a gym pass.", ex:"Zapisałem się na siłownię.", exEn:"I signed up for the gym. A woman: zapisałam." },
            { id:"b1-healthy-lifestyle-010", pl:"kondycja", en:"fitness / stamina", hint:"Feminine noun. 'poprawić kondycję' = to get fitter.", ex:"Bieganie poprawiło moją kondycję.", exEn:"Running improved my fitness." },
            { id:"b1-healthy-lifestyle-011", pl:"zdrowie", en:"health", hint:"Neuter noun. 'dbać o zdrowie' = to look after your health.", ex:"Zdrowie jest najważniejsze.", exEn:"Health is the most important thing." },
            { id:"b1-healthy-lifestyle-012", pl:"dbać o siebie", en:"to take care of oneself", pair:"dbać / zadbać", hint:"'dbać o' + accusative.", ex:"Warto dbać o siebie każdego dnia.", exEn:"It's worth taking care of yourself every day." },
            { id:"b1-healthy-lifestyle-013", pl:"sen", en:"sleep", hint:"Masculine noun. 'wysypiać się' = to get enough sleep.", ex:"Dobry sen jest podstawą zdrowia.", exEn:"Good sleep is the basis of health." },
            { id:"b1-healthy-lifestyle-014", pl:"stres", en:"stress", hint:"Masculine noun. 'radzić sobie ze stresem' = to cope with stress.", ex:"Muszę nauczyć się radzić sobie ze stresem.", exEn:"I need to learn to cope with stress." },
            { id:"b1-healthy-lifestyle-015", pl:"zdrowie psychiczne", en:"mental health", hint:"Neuter phrase. Increasingly openly discussed in Poland.", ex:"Zdrowie psychiczne jest równie ważne jak fizyczne.", exEn:"Mental health is just as important as physical health." },
            { id:"b1-healthy-lifestyle-016", pl:"odpoczywać", en:"to rest", pair:"odpoczywać / odpocząć", hint:"odpoczywam, odpoczywasz.", ex:"Musisz czasem odpocząć.", exEn:"You need to rest sometimes." },
            { id:"b1-healthy-lifestyle-017", pl:"relaksować się", en:"to relax", pair:"relaksować się / zrelaksować się", hint:"'zrelaksowany' = relaxed.", ex:"Relaksuję się, słuchając muzyki.", exEn:"I relax by listening to music." },
            { id:"b1-healthy-lifestyle-018", pl:"nałóg", en:"addiction / bad habit", hint:"Masculine noun. Natural collocations: 'wyjść z nałogu', 'walczyć z nałogiem'; for one specific habit Poles say 'rzucić palenie'.", ex:"Wyjście z nałogu wymaga silnej woli.", exEn:"Getting out of an addiction takes willpower." },
            { id:"b1-healthy-lifestyle-019", pl:"równowaga", en:"balance", hint:"Feminine noun. 'równowaga między pracą a życiem' = work-life balance.", ex:"Szukam równowagi między pracą a odpoczynkiem.", exEn:"I'm looking for a balance between work and rest." },
            { id:"b1-healthy-lifestyle-020", pl:"nawyk", en:"habit", hint:"Masculine noun. 'wyrobić nawyk' = to build a habit.", ex:"Picie wody to dobry nawyk.", exEn:"Drinking water is a good habit." }
          ]
        },
        { id:"b1-relationships",
          name: "Relacje i związki",
          emoji: "❤️",
          desc: "Dating, relationships, conflict, and making up",
          cards: [
            { id:"b1-relationships-001", pl:"związek", en:"relationship", hint:"Masculine noun. 'być w związku' = to be in a relationship.", ex:"Jesteśmy w związku od dwóch lat.", exEn:"We've been in a relationship for two years." },
            { id:"b1-relationships-002", pl:"randka", en:"date", hint:"Feminine noun. 'pierwsza randka' = first date.", ex:"Idę dziś na pierwszą randkę.", exEn:"I'm going on a first date today." },
            { id:"b1-relationships-003", pl:"umówić się na randkę", en:"to arrange a date", pair:"umawiać się / umówić się", hint:"'umówić się z kimś' = to make a date with someone.", ex:"Umówiłem się z nią na kawę.", exEn:"I arranged to meet her for coffee. A woman: umówiłam." },
            { id:"b1-relationships-004", pl:"zakochać się", en:"to fall in love", pair:"zakochiwać się / zakochać się", hint:"'zakochać się w kimś' + locative.", ex:"Zakochałem się w niej od pierwszego wejrzenia.", exEn:"I fell in love with her at first sight. A woman: zakochałam." },
            { id:"b1-relationships-005", pl:"kochać", en:"to love", relatedIds:["b1-relationships-022"], relationType:"contrast", hint:"Strong and romantic.", ex:"Kocham cię.", exEn:"I love you." },
            { id:"b1-relationships-022", pl:"lubić", en:"to like", relatedIds:["b1-relationships-005"], relationType:"contrast", hint:"Weaker than 'kochać'.", ex:"Lubię cię.", exEn:"I like you." },
            { id:"b1-relationships-006", pl:"para", en:"couple / pair", hint:"Feminine noun. 'młoda para' = the newlyweds.", ex:"Jesteśmy razem, jesteśmy parą.", exEn:"We're together, we're a couple." },
            { id:"b1-relationships-007", pl:"chłopak", en:"boyfriend (also: boy)", relatedIds:["b1-relationships-023"], relationType:"contrast", hint:"Context decides.", ex:"Poznaj mojego chłopaka.", exEn:"Meet my boyfriend." },
            { id:"b1-relationships-023", pl:"dziewczyna", en:"girlfriend (also: girl)", relatedIds:["b1-relationships-007"], relationType:"contrast", hint:"Context decides.", ex:"To jest moja dziewczyna.", exEn:"This is my girlfriend." },
            { id:"b1-relationships-008", pl:"narzeczony", en:"fiancé", relatedIds:["b1-relationships-024"], relationType:"gender-variant", hint:"After the engagement, before the wedding.", ex:"To jest mój narzeczony.", exEn:"This is my fiancé." },
            { id:"b1-relationships-024", pl:"narzeczona", en:"fiancée", relatedIds:["b1-relationships-008"], relationType:"gender-variant", hint:"The feminine form of 'narzeczony'.", ex:"To jest moja narzeczona, bierzemy ślub latem.", exEn:"This is my fiancée, we're getting married in summer." },
            { id:"b1-relationships-009", pl:"ślub", en:"wedding", hint:"Masculine noun. 'brać ślub' = to get married.", ex:"Bierzemy ślub we wrześniu.", exEn:"We're getting married in September." },
            { id:"b1-relationships-010", pl:"małżeństwo", en:"marriage", hint:"Neuter noun. Also means 'a married couple'.", ex:"Ich małżeństwo jest bardzo szczęśliwe.", exEn:"Their marriage is very happy." },
            { id:"b1-relationships-011", pl:"rozstać się", en:"to break up", pair:"rozstawać się / rozstać się", hint:"'rozstać się z kimś' + instrumental.", ex:"Rozstali się po pięciu latach.", exEn:"They broke up after five years." },
            { id:"b1-relationships-012", pl:"tęsknić", en:"to miss (someone)", pair:"tęsknić / zatęsknić", hint:"'tęsknić za kimś' + instrumental.", ex:"Tęsknię za tobą, kiedy wyjeżdżasz.", exEn:"I miss you when you go away." },
            { id:"b1-relationships-013", pl:"kłótnia", en:"argument / quarrel", hint:"Feminine noun. 'pokłócić się' = to have a row.", ex:"Mieliśmy wczoraj poważną kłótnię.", exEn:"We had a serious argument yesterday." },
            { id:"b1-relationships-014", pl:"pokłócić się", en:"to have an argument", pair:"kłócić się / pokłócić się", hint:"'pokłócić się z kimś o coś'.", ex:"Pokłóciliśmy się o pieniądze.", exEn:"We argued about money." },
            { id:"b1-relationships-015", pl:"pogodzić się", en:"to make up / reconcile", pair:"godzić się / pogodzić się", hint:"The happy ending after a kłótnia.", ex:"Na szczęście szybko się pogodziliśmy.", exEn:"Luckily we made up quickly." },
            { id:"b1-relationships-016", pl:"przepraszać", en:"to apologise", pair:"przepraszać / przeprosić", hint:"'Przepraszam' is also just 'excuse me / sorry'.", ex:"Przepraszam, że tak powiedziałem.", exEn:"I'm sorry I said that. A woman: powiedziałam." },
            { id:"b1-relationships-017", pl:"wybaczyć", en:"to forgive", pair:"wybaczać / wybaczyć", hint:"'wybaczyć komuś' + dative.", ex:"Czy możesz mi wybaczyć?", exEn:"Can you forgive me?" },
            { id:"b1-relationships-018", pl:"zaufanie", en:"trust", hint:"Neuter noun. 'stracić zaufanie' = to lose trust.", ex:"Zaufanie to podstawa każdego związku.", exEn:"Trust is the foundation of every relationship." },
            { id:"b1-relationships-019", pl:"zdradzić", en:"to cheat / betray", pair:"zdradzać / zdradzić", hint:"Strong word. 'zdrada' = betrayal / an affair.", ex:"Nie mógł jej wybaczyć, że go zdradziła.", exEn:"He couldn't forgive her for cheating on him." },
            { id:"b1-relationships-020", pl:"komplement", en:"compliment", hint:"Masculine noun. 'prawić komplementy' = to pay compliments.", ex:"Zrobił mi miły komplement.", exEn:"He paid me a nice compliment." },
            { id:"b1-relationships-021", pl:"zgadzać się", en:"to agree", pair:"zgadzać się / zgodzić się", hint:"'zgadzać się z kimś' + instrumental. Opposite: 'nie zgadzać się'.", ex:"Zgadzam się z tobą w tej sprawie.", exEn:"I agree with you on this matter." }
          ]
        },
        { id:"b1-culture-entertainment",
          name: "Kultura i rozrywka",
          emoji: "🎬",
          desc: "Films, music, books, and giving your verdict",
          cards: [
            { id:"b1-culture-entertainment-001", pl:"kultura", en:"culture", hint:"Feminine noun.", ex:"Interesuję się polską kulturą.", exEn:"I'm interested in Polish culture." },
            { id:"b1-culture-entertainment-002", pl:"rozrywka", en:"entertainment", hint:"Feminine noun.", ex:"Kino to moja ulubiona rozrywka.", exEn:"Cinema is my favourite entertainment." },
            { id:"b1-culture-entertainment-003", pl:"film", en:"film / movie", hint:"Masculine noun. 'kręcić film' = to shoot a film.", ex:"Ten film dostał wiele nagród.", exEn:"This film won many awards." },
            { id:"b1-culture-entertainment-004", pl:"serial", en:"TV series", hint:"Masculine noun. 'odcinek' = an episode.", ex:"Oglądam teraz świetny serial.", exEn:"I'm watching a great series right now." },
            { id:"b1-culture-entertainment-005", pl:"komedia", en:"comedy", hint:"Feminine noun. A film genre ('gatunek').", ex:"Wolę komedie od horrorów.", exEn:"I prefer comedies to horror films." },
            { id:"b1-culture-entertainment-006", pl:"dramat", en:"drama", hint:"Masculine noun.", ex:"To poruszający dramat o wojnie.", exEn:"It's a moving drama about the war." },
            { id:"b1-culture-entertainment-007", pl:"horror", en:"horror", hint:"Masculine noun. 'thriller' is also used.", ex:"Nie lubię horrorów, za bardzo się boję.", exEn:"I don't like horror films, I get too scared." },
            { id:"b1-culture-entertainment-008", pl:"muzyka", en:"music", hint:"Feminine noun. 'gatunek muzyczny' = a music genre.", ex:"Słucham różnej muzyki.", exEn:"I listen to all kinds of music." },
            { id:"b1-culture-entertainment-009", pl:"koncert", en:"concert", hint:"Masculine noun. 'iść na koncert'.", ex:"Byłem wczoraj na świetnym koncercie.", exEn:"I was at a great concert yesterday. A woman: byłam." },
            { id:"b1-culture-entertainment-010", pl:"zespół", en:"band / group", hint:"Masculine noun. Also 'a team'.", ex:"Mój ulubiony zespół gra dziś w Warszawie.", exEn:"My favourite band is playing in Warsaw today." },
            { id:"b1-culture-entertainment-011", pl:"książka", en:"book", hint:"Feminine noun. 'powieść' = a novel.", ex:"Ta książka jest oparta na faktach.", exEn:"This book is based on true events." },
            { id:"b1-culture-entertainment-012", pl:"autor", en:"author (m)", relatedIds:["b1-culture-entertainment-022"], relationType:"gender-variant", hint:"'pisarz' = writer specifically.", ex:"Kto jest autorem tej książki?", exEn:"Who is the author of this book?" },
            { id:"b1-culture-entertainment-022", pl:"autorka", en:"author (f)", relatedIds:["b1-culture-entertainment-012"], relationType:"gender-variant", hint:"The feminine form of 'autor'.", ex:"Ona jest autorką tej książki.", exEn:"She is the author of this book." },
            { id:"b1-culture-entertainment-013", pl:"teatr", en:"theatre", hint:"Masculine noun. 'sztuka' = a play.", ex:"Raz w miesiącu chodzimy do teatru.", exEn:"Once a month we go to the theatre." },
            { id:"b1-culture-entertainment-014", pl:"wystawa", en:"exhibition", hint:"Feminine noun. In a 'galeria' or 'muzeum'.", ex:"W muzeum jest ciekawa wystawa.", exEn:"There's an interesting exhibition at the museum." },
            { id:"b1-culture-entertainment-015", pl:"bilet", en:"ticket", hint:"Masculine noun. 'zarezerwować bilet' = to book a ticket.", ex:"Kupiłem dwa bilety na film.", exEn:"I bought two tickets for the film. A woman: kupiłam." },
            { id:"b1-culture-entertainment-016", pl:"widz", en:"viewer / member of the audience", hint:"Masculine noun. 'publiczność' = the audience as a whole.", ex:"Film spodobał się widzom.", exEn:"The audience liked the film." },
            { id:"b1-culture-entertainment-017", pl:"recenzja", en:"review", hint:"Feminine noun. 'napisać recenzję' = to write a review.", ex:"Przeczytałem recenzję przed seansem.", exEn:"I read a review before the screening. A woman: przeczytałam." },
            { id:"b1-culture-entertainment-018", pl:"polecać", en:"to recommend", pair:"polecać / polecić", hint:"'Polecam!' = I recommend it! Very common.", ex:"Gorąco polecam tę książkę.", exEn:"I highly recommend this book." },
            { id:"b1-culture-entertainment-019", pl:"Warto obejrzeć", en:"It's worth watching", hint:"'warto' + infinitive = it's worth doing.", ex:"Ten serial naprawdę warto obejrzeć.", exEn:"This series is really worth watching." },
            { id:"b1-culture-entertainment-020", pl:"nudny", en:"boring", relatedIds:["b1-culture-entertainment-023"], relationType:"contrast", hint:"A common verdict.", ex:"Ten film jest nudny.", exEn:"This film is boring." },
            { id:"b1-culture-entertainment-023", pl:"wciągający", en:"gripping", relatedIds:["b1-culture-entertainment-020"], relationType:"contrast", hint:"The opposite verdict.", ex:"Ta książka jest wciągająca.", exEn:"This book is gripping." },
            { id:"b1-culture-entertainment-021", pl:"Jak ci się podobało?", en:"How did you like it?", hint:"'podobać się' + dative. The go-to question after a film.", ex:"Byłeś w kinie? Jak ci się podobało?", exEn:"Were you at the cinema? How did you like it?" }
          ]
        },
        { id:"b1-travel-problems",
          name: "Problemy w podróży",
          emoji: "🧳",
          desc: "Lost luggage, delays, and travel emergencies",
          cards: [
            { id:"b1-travel-problems-001", pl:"opóźnienie", en:"delay", hint:"Neuter noun. 'mieć opóźnienie' = to be delayed.", ex:"Nasz lot ma dwie godziny opóźnienia.", exEn:"Our flight has a two-hour delay." },
            { id:"b1-travel-problems-002", pl:"odwołany", en:"cancelled", hint:"Adjective. 'odwołać' = to cancel.", ex:"Pociąg został odwołany.", exEn:"The train has been cancelled." },
            { id:"b1-travel-problems-003", pl:"zgubić", en:"to lose", pair:"gubić / zgubić", hint:"'zgubić się' = to get lost (yourself).", ex:"Zgubiłem paszport na lotnisku.", exEn:"I lost my passport at the airport. A woman: zgubiłam." },
            { id:"b1-travel-problems-004", pl:"zgubiony bagaż", en:"lost luggage", hint:"'bagaż' (masculine) = luggage. This is the everyday phrase; airline and complaint paperwork usually says 'bagaż zagubiony' / 'zagubiony bagaż'.", ex:"Linia lotnicza zgubiła mój bagaż.", exEn:"The airline lost my luggage." },
            { id:"b1-travel-problems-005", pl:"walizka", en:"suitcase", hint:"Feminine noun. 'spakować walizkę' = to pack a suitcase.", ex:"Moja walizka nie dotarła.", exEn:"My suitcase didn't arrive." },
            { id:"b1-travel-problems-006", pl:"ukraść", en:"to steal", pair:"kraść / ukraść", hint:"'kradzież' = theft.", ex:"Ktoś ukradł mi portfel w metrze.", exEn:"Someone stole my wallet on the metro." },
            { id:"b1-travel-problems-007", pl:"okradziony", en:"robbed", hint:"Adjective. 'Zostałem okradziony' = I was robbed.", ex:"Zostałam okradziona na dworcu.", exEn:"I was robbed at the station. A man: zostałem." },
            { id:"b1-travel-problems-008", pl:"zgłosić", en:"to report", pair:"zgłaszać / zgłosić", hint:"'zgłosić coś na policji' = to report something to the police.", ex:"Muszę zgłosić kradzież na policji.", exEn:"I need to report the theft to the police." },
            { id:"b1-travel-problems-009", pl:"policja", en:"police", hint:"Feminine noun. Emergency number in Poland: 112.", ex:"Proszę zadzwonić na policję!", exEn:"Please call the police!" },
            { id:"b1-travel-problems-010", pl:"pogotowie", en:"ambulance / emergency service", hint:"Neuter noun. 'wezwać pogotowie' = to call an ambulance.", ex:"Wezwałem pogotowie, bo zasłabła.", exEn:"I called an ambulance because she fainted. A woman: wezwałam." },
            { id:"b1-travel-problems-011", pl:"wypadek", en:"accident", hint:"Masculine noun. 'mieć wypadek' = to have an accident.", ex:"Na drodze był wypadek.", exEn:"There was an accident on the road." },
            { id:"b1-travel-problems-012", pl:"pomocy!", en:"help!", hint:"The genitive form used as a cry for help.", ex:"Pomocy! Ktoś ukradł mi torbę!", exEn:"Help! Someone stole my bag!" },
            { id:"b1-travel-problems-013", pl:"ambasada", en:"embassy", hint:"Feminine noun. Where to go if you lose your passport.", ex:"Muszę iść do ambasady po nowy paszport.", exEn:"I need to go to the embassy for a new passport." },
            { id:"b1-travel-problems-014", pl:"ubezpieczenie", en:"insurance", hint:"Neuter noun. 'ubezpieczenie podróżne' = travel insurance.", ex:"Na szczęście mam ubezpieczenie podróżne.", exEn:"Luckily I have travel insurance." },
            { id:"b1-travel-problems-015", pl:"reklamacja", en:"complaint / claim", hint:"Feminine noun. 'złożyć reklamację' = to file a claim.", ex:"Złożyłem reklamację w sprawie zagubionego bagażu.", exEn:"I filed a claim about the lost luggage. A woman: złożyłam." },
            { id:"b1-travel-problems-016", pl:"zwrot pieniędzy", en:"refund", hint:"Masculine phrase. 'domagać się zwrotu' = to demand a refund.", ex:"Chcę zwrot pieniędzy za odwołany lot.", exEn:"I want a refund for the cancelled flight." },
            { id:"b1-travel-problems-017", pl:"utknąć", en:"to get stuck / stranded", pair:"utykać / utknąć", hint:"'utknąć na lotnisku' = to be stranded at the airport.", ex:"Utknęliśmy na lotnisku na całą noc.", exEn:"We got stranded at the airport all night." },
            { id:"b1-travel-problems-018", pl:"awaria", en:"breakdown / failure", hint:"Feminine noun. Of a car, a system, the power.", ex:"Mieliśmy awarię samochodu na autostradzie.", exEn:"We had a car breakdown on the motorway." },
            { id:"b1-travel-problems-019", pl:"Czy może mi pan pomóc?", en:"Can you help me?", hint:"To a woman: 'Czy może mi pani...'. Polite and essential.", ex:"Przepraszam, czy może mi pani pomóc? Zgubiłem się.", exEn:"Excuse me, can you help me? I'm lost." },
            { id:"b1-travel-problems-020", pl:"Co się stało?", en:"What happened?", hint:"'stać się' = to happen. The first thing anyone will ask.", ex:"Wyglądasz na zdenerwowanego. Co się stało?", exEn:"You look upset. What happened?" }
          ]
        },
        { id:"b1-idioms",
          name: "Idiomy",
          emoji: "💎",
          desc: "Vivid, common Polish idioms for describing people and situations.",
          cards: [
            { id:"b1-idioms-001", pl:"bułka z masłem", en:"a piece of cake / dead easy", hint:"Literally: a roll with butter.", ex:"Ten egzamin to była bułka z masłem.", exEn:"That exam was a piece of cake." },
            { id:"b1-idioms-002", pl:"nie mój cyrk, nie moje małpy", en:"not my problem", hint:"Literally: not my circus, not my monkeys.", ex:"Sami sobie narobili kłopotów - nie mój cyrk, nie moje małpy.", exEn:"They made trouble for themselves - not my circus, not my monkeys." },
            { id:"b1-idioms-003", pl:"robić z igły widły", en:"to make a mountain out of a molehill", hint:"Literally: to make a pitchfork out of a needle. Under negation the object takes the genitive: nie rób wideł.", ex:"Nie rób z igły wideł, to naprawdę drobiazg.", exEn:"Don't make a mountain out of a molehill, it's really nothing." },
            { id:"b1-idioms-004", pl:"musztarda po obiedzie", en:"too little, too late", hint:"Literally: mustard after dinner.", ex:"Teraz przeprosiny? Musztarda po obiedzie.", exEn:"An apology now? Too little, too late." },
            { id:"b1-idioms-005", pl:"co ma piernik do wiatraka", en:"what does that have to do with anything?", hint:"Literally: what does gingerbread have to do with a windmill.", ex:"Co ma piernik do wiatraka? Mówiliśmy o czymś innym.", exEn:"What does that have to do with anything? We were talking about something else." },
            { id:"b1-idioms-006", pl:"czuć do kogoś miętę", en:"to have a crush on someone", hint:"Literally: to feel mint towards someone.", ex:"Chyba czuje do niej miętę.", exEn:"I think he has a crush on her." },
            { id:"b1-idioms-007", pl:"rzucać grochem o ścianę", en:"to talk to a brick wall", hint:"Literally: to throw peas against a wall.", ex:"Tłumaczę mu to od godziny, ale to jak rzucanie grochem o ścianę.", exEn:"I've been explaining it for an hour, but it's like talking to a brick wall." },
            { id:"b1-idioms-008", pl:"wiercić komuś dziurę w brzuchu", en:"to nag someone relentlessly", hint:"Literally: to drill a hole in someone's belly.", ex:"Dzieci wierciły mi dziurę w brzuchu, żebym kupił im psa.", exEn:"The kids kept nagging me to buy a dog." },
            { id:"b1-idioms-009", pl:"pierwsze koty za płoty", en:"the hardest part is over", hint:"Literally: the first cats over the fence.", ex:"Pierwszy dzień w nowej pracy minął - pierwsze koty za płoty.", exEn:"The first day at the new job is over - the hardest part is behind us." },
            { id:"b1-idioms-010", pl:"mieć muchy w nosie", en:"to be grumpy / in a huff", hint:"Literally: to have flies in one's nose.", ex:"Nie zaczepiaj go, ma dziś muchy w nosie.", exEn:"Don't bother him, he's in a huff today." },
            { id:"b1-idioms-011", pl:"rzucać słowa na wiatr", en:"to make empty promises", hint:"Literally: to throw words to the wind.", ex:"On nie rzuca słów na wiatr - jak coś obieca, to zrobi.", exEn:"He doesn't make empty promises - if he promises something, he does it." },
            { id:"b1-idioms-012", pl:"być nie w sosie", en:"to be out of sorts", hint:"Literally: to be not in the sauce.", ex:"Coś jesteś dzisiaj nie w sosie.", exEn:"You seem a bit out of sorts today." },
            { id:"b1-idioms-013", pl:"urwać się z choinki", en:"to be clueless / out of touch", hint:"Literally: to have fallen off the Christmas tree. A woman says: urwałaś.", ex:"Ty chyba urwałeś się z choinki - to już dawno nieaktualne.", exEn:"You must be out of touch - that's long out of date." },
            { id:"b1-idioms-014", pl:"wpaść jak śliwka w kompot", en:"to land in a fine mess", hint:"Literally: to fall in like a plum into compote. A woman says: Wpadłam.", ex:"Wpadłem jak śliwka w kompot z tym projektem.", exEn:"I landed myself in a fine mess with this project." },
            { id:"b1-idioms-015", pl:"trzymać kciuki", en:"to keep one's fingers crossed", hint:"Literally: to hold thumbs.", ex:"Trzymam kciuki za twój jutrzejszy egzamin.", exEn:"I'm keeping my fingers crossed for your exam tomorrow." },
            { id:"b1-idioms-016", pl:"wypisz wymaluj", en:"the spitting image", hint:"A perfect likeness or exact match.", ex:"Twoja córka to wypisz wymaluj ty z młodości.", exEn:"Your daughter is the spitting image of you when you were young." },
            { id:"b1-idioms-017", pl:"siedzieć jak na szpilkach", en:"to be on pins and needles", hint:"To wait in nervous anticipation.", ex:"Czekam na wyniki i siedzę jak na szpilkach.", exEn:"I'm waiting for the results, on pins and needles." },
            { id:"b1-idioms-018", pl:"odwracać kota ogonem", en:"to twist the facts", hint:"Literally: to turn the cat around by its tail. A woman says: powiedziałaś.", ex:"Nie odwracaj kota ogonem, wiesz, co powiedziałeś.", exEn:"Don't twist the facts, you know what you said." },
            { id:"b1-idioms-019", pl:"wieszać na kimś psy", en:"to drag someone's name through the mud", hint:"Literally: to hang dogs on someone.", ex:"Wszyscy wieszają na nim psy, a on nic nie zrobił.", exEn:"Everyone's slandering him and he did nothing." },
            { id:"b1-idioms-020", pl:"wywoływać wilka z lasu", en:"to tempt fate", hint:"Literally: to call the wolf out of the woods.", ex:"Nie mówmy o awariach, żeby nie wywoływać wilka z lasu.", exEn:"Let's not talk about breakdowns, so we don't tempt fate." },
            { id:"b1-idioms-021", pl:"kupować kota w worku", en:"to buy a pig in a poke", hint:"Literally: to buy a cat in a bag. Buying blind.", ex:"Sprawdź auto przed zakupem, nie kupuj kota w worku.", exEn:"Check the car before buying, don't buy a pig in a poke." },
            { id:"b1-idioms-022", pl:"pasować jak wół do karety", en:"to stick out like a sore thumb", hint:"Literally: to fit like an ox to a carriage. Total clash.", ex:"Ten budynek pasuje tu jak wół do karety.", exEn:"That building fits in here like a sore thumb." },
            { id:"b1-idioms-023", pl:"mieć węża w kieszeni", en:"to be stingy", hint:"Literally: to have a snake in one's pocket, so you fear reaching for your wallet.", ex:"On nigdy nie stawia kolejki, ma węża w kieszeni.", exEn:"He never buys a round, he's stingy." },
            { id:"b1-idioms-024", pl:"nudne jak flaki z olejem", en:"deadly boring", hint:"Literally: boring as tripe with oil.", ex:"Ten wykład był nudny jak flaki z olejem.", exEn:"That lecture was deadly boring." },
            { id:"b1-idioms-025", pl:"francuski piesek", en:"a fussy person", hint:"Literally: a French poodle. Someone who complains about trifles.", ex:"Nie bądź takim francuskim pieskiem, jedz co dają.", exEn:"Don't be so fussy, eat what you're given." },
            { id:"b1-idioms-026", pl:"szukać dziury w całym", en:"to nitpick", hint:"Literally: to look for a hole in the whole.", ex:"Wszystko gra, przestań szukać dziury w całym.", exEn:"Everything's fine, stop nitpicking." },
            { id:"b1-idioms-027", pl:"wziąć się w garść", en:"to pull yourself together", hint:"Literally: to take yourself in a fist.", ex:"Przestań narzekać i weź się w garść.", exEn:"Stop complaining and pull yourself together." }
          ]
        },
        { id:"b1-proverbs",
          name: "Przysłowia",
          emoji: "🦉",
          desc: "Classic Polish proverbs. Drop one of these and you'll sound like you grew up here.",
          cards: [
            { id:"b1-proverbs-001", pl:"jak sobie pościelisz, tak się wyśpisz", en:"you reap what you sow", hint:"Literally: as you make your bed, so you'll sleep. A woman says: Sama podjęłaś.", ex:"Sam podjąłeś tę decyzję. Jak sobie pościelisz, tak się wyśpisz.", exEn:"You made this call yourself. You reap what you sow." },
            { id:"b1-proverbs-002", pl:"z deszczu pod rynnę", en:"out of the frying pan into the fire", hint:"Literally: from the rain under the gutter. From bad to worse. A woman says: Zmieniłam.", ex:"Zmieniłem pracę na gorszą, z deszczu pod rynnę.", exEn:"I changed jobs for a worse one, out of the frying pan into the fire." },
            { id:"b1-proverbs-003", pl:"kiedy wejdziesz między wrony, musisz krakać jak one", en:"when in Rome, do as the Romans do", hint:"Literally: among crows you must caw like them.", ex:"Dostosuj się. Kiedy wejdziesz między wrony, musisz krakać jak one.", exEn:"Fit in. When in Rome, do as the Romans do." },
            { id:"b1-proverbs-004", pl:"leje jak z cebra", en:"it's raining cats and dogs", hint:"Literally: it's pouring as from a bucket.", ex:"Zostańmy w domu, leje jak z cebra.", exEn:"Let's stay home, it's raining cats and dogs." },
            { id:"b1-proverbs-005", pl:"po ptakach", en:"too late / it's over", hint:"Literally: after the birds. The chance has passed.", ex:"Sklep już zamknięty, i po ptakach.", exEn:"The shop's already closed, and that's that." },
            { id:"b1-proverbs-006", pl:"co za dużo, to niezdrowo", en:"too much of a good thing", hint:"Literally: what's too much is unhealthy. Moderation. A woman says: Zjadłam.", ex:"Zjadłem cały tort. Co za dużo, to niezdrowo.", exEn:"I ate the whole cake. Too much of a good thing." },
            { id:"b1-proverbs-007", pl:"bez pracy nie ma kołaczy", en:"no pain, no gain", hint:"Literally: without work there are no kołacz cakes.", ex:"Chcesz zdać? Ucz się. Bez pracy nie ma kołaczy.", exEn:"Want to pass? Study. No pain, no gain." },
            { id:"b1-proverbs-008", pl:"kto rano wstaje, temu Pan Bóg daje", en:"the early bird catches the worm", hint:"Literally: to the one who rises early, God gives. A woman says: Wstałam / zdążyłam.", ex:"Wstałem o szóstej i zdążyłem ze wszystkim. Kto rano wstaje, temu Pan Bóg daje.", exEn:"I got up at six and got everything done. The early bird catches the worm." },
            { id:"b1-proverbs-009", pl:"co nagle, to po diable", en:"haste makes waste", hint:"Literally: what's done in haste is of the devil.", ex:"Nie spiesz się tak, co nagle, to po diable.", exEn:"Don't rush so much, haste makes waste." },
            { id:"b1-proverbs-010", pl:"nie chwal dnia przed zachodem słońca", en:"don't count your chickens", hint:"Literally: don't praise the day before sunset.", ex:"Jeszcze nie wygraliśmy. Nie chwal dnia przed zachodem słońca.", exEn:"We haven't won yet. Don't count your chickens." },
            { id:"b1-proverbs-011", pl:"mądry Polak po szkodzie", en:"hindsight is 20/20", hint:"A self-ironic classic. Literally: a Pole is wise after the damage.", ex:"Trzeba było zrobić kopię wcześniej. Mądry Polak po szkodzie.", exEn:"Should've backed it up earlier. Hindsight is 20/20." },
            { id:"b1-proverbs-012", pl:"apetyt rośnie w miarę jedzenia", en:"appetite comes with eating", hint:"The more you get, the more you want.", ex:"Najpierw chciał jeden, teraz pięć. Apetyt rośnie w miarę jedzenia.", exEn:"First he wanted one, now five. Appetite comes with eating." },
            { id:"b1-proverbs-013", pl:"gdzie kucharek sześć, tam nie ma co jeść", en:"too many cooks spoil the broth", hint:"Literally: where there are six cooks, there's nothing to eat.", ex:"Za dużo osób nad tym pracuje. Gdzie kucharek sześć, tam nie ma co jeść.", exEn:"Too many people on this. Too many cooks spoil the broth." }
          ]
        },
        { id:"b1-everyday-slang",
          name: "Codzienny slang",
          emoji: "💬",
          desc: "The everyday slang Poles actually use, so you stop sounding like a textbook.",
          cards: [
            { id:"b1-everyday-slang-001", pl:"spoko", en:"cool / okay", hint:"The Swiss-army-knife reaction. Works as 'sure', 'fine', 'no worries'.", ex:"Spoko, nic się nie stało.", exEn:"No worries, nothing happened." },
            { id:"b1-everyday-slang-002", pl:"git", en:"all good / okay", hint:"Short, upbeat 'it's fine'. Often 'wszystko git'.", ex:"Wszystko git, ogarnięte.", exEn:"All good, it's sorted." },
            { id:"b1-everyday-slang-003", pl:"luz", en:"chill / relaxed", hint:"Describes an easy vibe or a laid-back person. 'Na luzie' = relaxed.", ex:"Bez stresu, pełen luz.", exEn:"No stress, totally chill." },
            { id:"b1-everyday-slang-004", pl:"mega", en:"super / really", hint:"Amplifier you can bolt onto almost any adjective.", ex:"Ten koncert był mega dobry.", exEn:"That concert was super good." },
            { id:"b1-everyday-slang-005", pl:"wypas", en:"top-notch / awesome", register:"slang", hint:"For an object or situation that impresses you. Adjective: 'wypasiony', which is the form you will hear most. Slang, and some speakers now find it a bit dated.", ex:"Ten hotel to totalny wypas.", exEn:"This hotel is totally top-notch." },
            { id:"b1-everyday-slang-006", pl:"hajs", en:"dough / money", hint:"Younger, playful word for 'kasa'.", ex:"Nie mam hajsu na nowy telefon.", exEn:"I don't have the dough for a new phone." },
            { id:"b1-everyday-slang-007", pl:"siano", en:"cash / money", hint:"Literally 'hay'. Makes money sound less serious.", ex:"Muszę zarobić trochę siana przed wakacjami.", exEn:"I need to earn some cash before the holidays." },
            { id:"b1-everyday-slang-008", pl:"fura", en:"ride / car", hint:"Any vehicle, from a banger to a supercar. A woman says: kupiłaś.", ex:"Ale kupiłeś sobie furę!", exEn:"What a ride you bought yourself!" },
            { id:"b1-everyday-slang-009", pl:"ziomek", en:"buddy / dude", hint:"Warm word for a male friend. Diminutive: 'ziomuś'.", ex:"Idę na piwo z ziomkami.", exEn:"I'm going for a beer with my buddies." },
            { id:"b1-everyday-slang-010", pl:"typ", en:"guy / dude", hint:"Neutral word for some man. Tone decides if it's friendly or not.", ex:"Jakiś typ o ciebie pytał.", exEn:"Some guy was asking about you." },
            { id:"b1-everyday-slang-011", pl:"siema", en:"hey / what's up", hint:"The go-to casual greeting. Short for 'jak się masz'.", ex:"Siema, co tam słychać?", exEn:"Hey, how's it going?" },
            { id:"b1-everyday-slang-012", pl:"nara", en:"see ya / bye", hint:"The most popular informal goodbye. Short for 'na razie'.", ex:"Muszę lecieć, nara!", exEn:"Gotta run, see ya!" },
            { id:"b1-everyday-slang-013", pl:"ściema", en:"a lie / bull", hint:"When someone is making things up or exaggerating.", ex:"Nie wierz w to, to jedna wielka ściema.", exEn:"Don't believe it, it's one big lie." },
            { id:"b1-everyday-slang-014", pl:"kminić", en:"to think / figure out", pair:"kmini\u0107 / rozkmini\u0107", hint:"Casual 'to ponder / puzzle over'. Perfective: rozkminić.", ex:"Kminię nad tym już godzinę.", exEn:"I've been puzzling over this for an hour." },
            { id:"b1-everyday-slang-015", pl:"obczaić", en:"to check out", pair:"obczaja\u0107 / obczai\u0107", hint:"To look something over or scope it out. Also 'obczaj to'.", ex:"Musisz obczaić ten nowy lokal w centrum.", exEn:"You have to check out this new place downtown." },
            { id:"b1-everyday-slang-016", pl:"ogarnąć", en:"to sort out / handle", pair:"ogarnia\u0107 / ogarn\u0105\u0107", hint:"To get a grip on something. 'Ogarnij się' = pull yourself together.", ex:"Spokojnie, ogarnę to do jutra.", exEn:"Relax, I'll sort it out by tomorrow." },
            { id:"b1-everyday-slang-017", pl:"czaić", en:"to get it / to catch on", pair:"czai\u0107 / zaczai\u0107", hint:"'Czaisz?' = 'you follow?'. 'Nie czaję' = 'I don't get it'.", ex:"Zupełnie nie czaję, o co mu chodzi.", exEn:"I totally don't get what he means." },
            { id:"b1-everyday-slang-018", pl:"kombinować", en:"to wangle / to find a workaround", pair:"kombinowa\u0107 / wykombinowa\u0107", hint:"A very Polish idea of hustling around the rules to get things done.", ex:"Nie kombinuj, tylko zrób to normalnie.", exEn:"Don't overcomplicate it, just do it the normal way." },
            { id:"b1-everyday-slang-019", pl:"dzban", en:"a doofus / a dimwit", hint:"A light, popular insult - not really offensive. Literally 'a jug'.", ex:"Ale z niego dzban, znowu zapomniał hasła.", exEn:"What a doofus, he forgot his password again." },
            { id:"b1-everyday-slang-020", pl:"olać to", en:"to blow it off / to not bother", pair:"olewa\u0107 / ola\u0107", hint:"To deliberately not care about something. 'Olej to' = 'let it go / forget it'.", ex:"Olej to, nie warto się stresować.", exEn:"Let it go, it's not worth stressing over." }
          ]
        },
        { id:"b1-exclamations",
          name: "Reakcje (Ale masakra!)",
          emoji: "🤯",
          desc: "Everyday exclamations - the mild, clean cousins of Polish swearing.",
          cards: [
            { id:"b1-exclamations-001", pl:"masakra", en:"brutal! / insane!", register:"informal", hint:"Reaction to anything overwhelming, bad or just intense. 'Ale masakra!' Colloquial but widely used across ages.", ex:"Egzamin to była totalna masakra.", exEn:"The exam was an absolute nightmare." },
            { id:"b1-exclamations-002", pl:"tragedia", en:"a disaster", hint:"Often an over-reaction to something minor. 'Robić tragedię' = overdramatize.", ex:"Nie rób tragedii z drobiazgu.", exEn:"Don't make a disaster out of a trifle." },
            { id:"b1-exclamations-003", pl:"dramat", en:"total drama / awful", hint:"Same energy as 'tragedia', very common among younger speakers.", ex:"Spóźnił się pięć minut, a ona robi dramat.", exEn:"He was five minutes late and she's making a drama." },
            { id:"b1-exclamations-004", pl:"żenada", en:"cringe / embarrassing", hint:"For an embarrassing moment or person. Adjective: 'żenujące'.", ex:"Ale żenada, pomylił wszystkie imiona.", exEn:"So cringe, he mixed up everyone's names." },
            { id:"b1-exclamations-005", pl:"beka", en:"a laugh / hilarious", register:"slang", hint:"When something is genuinely funny. 'Ale beka!' Casual slang, mostly younger speakers - not for work or formal settings.", ex:"Ale była beka na wczorajszej imprezie.", exEn:"It was such a laugh at yesterday's party." },
            { id:"b1-exclamations-006", pl:"sztos", en:"awesome / fire", register:"slang", hint:"Pure excitement about news, plans or things. Casual slang, mostly younger speakers.", ex:"Nowa płyta tego zespołu to sztos.", exEn:"This band's new album is fire." },
            { id:"b1-exclamations-007", pl:"lipa", en:"lame / rubbish", hint:"Something weak, disappointing or low quality.", ex:"Ten film to totalna lipa.", exEn:"That movie is total rubbish." },
            { id:"b1-exclamations-008", pl:"kicha", en:"a bummer / flop", hint:"When plans fall through. An expressive form related to 'kiszka' (gut, sausage); it also means a puncture - 'złapać kichę' = to get a flat tyre.", ex:"Plany się zmieniły, kicha.", exEn:"Plans changed, what a bummer." },
            { id:"b1-exclamations-009", pl:"porażka", en:"epic fail", hint:"Slang for a fail or an embarrassing mishap. A woman says: Zapomniałam.", ex:"Zapomniałem kluczy w domu, porażka.", exEn:"Left my keys at home, epic fail." },
            { id:"b1-exclamations-010", pl:"kurczę", en:"shoot / darn", hint:"A soft, polite stand-in for stronger words. Totally family-friendly.", ex:"Kurczę, znowu pada.", exEn:"Darn, it's raining again." },
            { id:"b1-exclamations-011", pl:"kurde", en:"dang / darn", hint:"Mild minced oath - a socially safe substitute for a harder curse. A woman says: zapomniałam.", ex:"Kurde, zapomniałem parasola.", exEn:"Dang, I forgot my umbrella." },
            { id:"b1-exclamations-012", pl:"no weź", en:"come on / give me a break", hint:"Playful protest or disbelief. Tone carries the meaning.", ex:"No weź, przecież to nie moja wina.", exEn:"Come on, it's not even my fault." },
            { id:"b1-exclamations-013", pl:"ale jazda", en:"what a ride / wild", hint:"Reaction to something crazy or intense, good or bad. A woman says: spodziewałam się.", ex:"Ale jazda, nie spodziewałem się tego.", exEn:"What a ride, I didn't see that coming." },
            { id:"b1-exclamations-014", pl:"serio?", en:"seriously? / for real?", hint:"Ubiquitous reaction of surprise or doubt.", ex:"Serio? Nie wierzę własnym uszom.", exEn:"Seriously? I can't believe my ears." },
            { id:"b1-exclamations-015", pl:"wiocha", en:"cringe / tacky / how embarrassing", register:"slang", warning:"Built on 'village' as an insult, so it can sound classist about people from the countryside.", hint:"Literally 'a village'. Covers something embarrassing, tacky or 'provincial' - which is exactly why it can land as an insult about where someone is from.", ex:"Zrobił mi straszną wiochę przy znajomych.", exEn:"He totally embarrassed me in front of my friends." },
            { id:"b1-exclamations-016", pl:"ja cię kręcę", en:"wow / holy smokes", hint:"A mild, friendly cry of surprise. Literally 'I'm spinning you'.", ex:"Ja cię kręcę, ale tu dzisiaj tłum!", exEn:"Holy smokes, what a crowd today!" },
            { id:"b1-exclamations-017", pl:"w mordę jeża", en:"good grief / holy cow", hint:"A jokey exclamation. Literally 'in the hedgehog's snout'.", ex:"W mordę jeża, ale tu drogo!", exEn:"Holy cow, it's expensive here!" }
          ]
        },
        { id:"b1-corporate-slang",
          name: "Korpo-slang",
          emoji: "🏢",
          desc: "Office and corporate slang for open-space life and team projects.",
          cards: [
            { id:"b1-corporate-slang-001", pl:"korpo", en:"the corporate world", register:"informal", hint:"A big corporation or corporate life in general. Slightly weary tone. Office slang - it would not appear in formal writing.", ex:"Pracuję w korpo od pięciu lat.", exEn:"I've worked in the corporate world for five years." },
            { id:"b1-corporate-slang-002", pl:"fakap", en:"a screw-up", register:"slang", warning:"Built on an English obscenity. Fine among peers, not with clients, management or in writing.", hint:"From English 'f-up', declined like a normal Polish noun. Office slang only - and it still carries the original obscenity.", ex:"Mieliśmy wczoraj niezły fakap na produkcji.", exEn:"We had a pretty big screw-up in production yesterday." },
            { id:"b1-corporate-slang-003", pl:"dedlajn", en:"deadline", register:"slang", hint:"The English word, respelled Polish-style. Office jargon; in neutral Polish say 'termin'.", ex:"Dedlajn jest jutro o dwunastej.", exEn:"The deadline is tomorrow at noon." },
            { id:"b1-corporate-slang-004", pl:"asapem", en:"ASAP", register:"slang", hint:"English acronym bent into a Polish adverb (instrumental case). Office jargon; neutral Polish would be 'jak najszybciej'.", ex:"Wyślij mi ten plik asapem.", exEn:"Send me that file ASAP." },
            { id:"b1-corporate-slang-005", pl:"mityng", en:"a meeting", register:"slang", hint:"Respelled 'meeting'. 'Wskoczyć na mityng' = jump on a call. Office jargon; the ordinary word is 'spotkanie'.", ex:"Mam mityng o dziesiątej.", exEn:"I've got a meeting at ten." },
            { id:"b1-corporate-slang-006", pl:"ficzer", en:"a feature", register:"slang", hint:"Product/dev slang from English 'feature'. Team jargon; neutral Polish is 'funkcja'.", ex:"Wypuszczamy nowy ficzer w przyszłym tygodniu.", exEn:"We're shipping a new feature next week." },
            { id:"b1-corporate-slang-007", pl:"harować", en:"to slave away", pair:"harowa\u0107 (impf only)", hint:"To work exhaustingly hard.", ex:"Haruję nad tym raportem od rana.", exEn:"I've been slaving over this report since morning." },
            { id:"b1-corporate-slang-008", pl:"tyrać", en:"to toil", pair:"tyra\u0107 (impf only)", hint:"Near-synonym of 'harować', equally casual. A woman says: Tyrałam.", ex:"Tyrałem nad tym przez cały weekend.", exEn:"I toiled over this all weekend." },
            { id:"b1-corporate-slang-009", pl:"ogarnąć temat", en:"to handle it", pair:"ogarnia\u0107 / ogarn\u0105\u0107 temat", hint:"To take care of a task or get on top of an issue.", ex:"Spokojnie, ogarnę ten temat do piątku.", exEn:"Relax, I'll handle this by Friday." },
            { id:"b1-corporate-slang-010", pl:"Mordor", en:"Mordor (Warsaw's Służewiec office district)", register:"slang", region:"warsaw", hint:"The office-tower zone around Domaniewska in Warsaw's Służewiec, named after Tolkien's Mordor for its traffic and crowds. It names that district - it is not a general Polish word for any business district.", ex:"Znowu straszne korki w drodze do Mordoru.", exEn:"Terrible traffic on the way to Mordor again." },
            { id:"b1-corporate-slang-011", pl:"L4", en:"sick leave", hint:"Pronounced 'el-cztery'. Colloquial name for a doctor's sick note.", ex:"Czuję się fatalnie, biorę L4.", exEn:"I feel awful, I'm taking sick leave." },
            { id:"b1-corporate-slang-012", pl:"urlop na żądanie", en:"leave on demand", hint:"A real labour-law entitlement, in slang just 'użet' (UŻ). A woman says: Zaspałam.", ex:"Zaspałem, biorę urlop na żądanie.", exEn:"I overslept, I'm taking leave on demand." }
          ]
        },
        { id:"b1-urban-party-slang",
          name: "Slang miejski i imprezowy",
          emoji: "🎉",
          desc: "Urban and party slang for nights out and the day after.",
          cards: [
            { id:"b1-urban-party-slang-001", pl:"słoik", en:"out-of-towner (dismissive)", register:"slang", region:"warsaw", production:"recognition-only", warning:"Dismissive and class-coded - it labels people who moved to the city from smaller towns. Worth understanding, best not used.", hint:"Literally 'a jar', from the jars of home food people bring back from their parents'. Especially associated with Warsaw, though understood more broadly. It is dismissive and class-coded - a put-down rather than a joke - so it is better recognised than actively used.", ex:"W weekend miasto jest puste, słoiki wyjechały do domu.", exEn:"On weekends the city empties out, the 'jars' went home." },
            { id:"b1-urban-party-slang-002", pl:"wbić", en:"to drop by / roll up", pair:"wbija\u0107 / wbi\u0107", hint:"Literally 'to hammer in'. Arriving somewhere casually.", ex:"Mogę do ciebie wbić po pracy?", exEn:"Can I drop by yours after work?" },
            { id:"b1-urban-party-slang-003", pl:"ustawka", en:"an arranged fight / a staged set-up", register:"slang", production:"recognition-only", warning:"Strongly associated with a pre-arranged fight between football hooligans. Understand it, but do not use it for an ordinary get-together.", hint:"Careful: for most Poles 'ustawka' first means an arranged fight between rival football fans. Outside that sense it describes something staged or rigged - a media or political set-up. It is never a neutral word for meeting friends: for that say 'umawiamy się', 'spotykamy się' or 'spotkanie'.", ex:"Policja spodziewała się ustawki kibiców.", exEn:"The police expected an arranged fight between football fans." },
            { id:"b1-urban-party-slang-004", pl:"melanż", en:"a wild party", hint:"A heavy night out or big party.", ex:"To był niezły melanż, nic nie pamiętam.", exEn:"That was a wild party, I remember nothing." },
            { id:"b1-urban-party-slang-005", pl:"domówka", en:"house party", hint:"A party at someone's flat rather than a club.", ex:"Robimy domówkę w sobotę, wpadniesz?", exEn:"We're throwing a house party Saturday, coming?" },
            { id:"b1-urban-party-slang-006", pl:"kac", en:"a hangover", hint:"The base word. Pairs with 'mieć' - 'mam kaca'.", ex:"Mam dziś straszliwego kaca.", exEn:"I've got a terrible hangover today." },
            { id:"b1-urban-party-slang-007", pl:"kac morderca", en:"a killer hangover", hint:"The day after a 'melanż'. Peak suffering.", ex:"Nie krzycz, mam kaca mordercę.", exEn:"Don't shout, I've got a killer hangover." },
            { id:"b1-urban-party-slang-008", pl:"na mieście", en:"out in town", hint:"Out and about in the city. 'Spotkajmy się na mieście.'", ex:"Zjedzmy coś na mieście.", exEn:"Let's grab something to eat out in town." },
            { id:"b1-urban-party-slang-009", pl:"lecieć", en:"to dash off", pair:"lecie\u0107 / polecie\u0107", hint:"To head out quickly. 'Muszę lecieć' = gotta run.", ex:"Muszę lecieć, mam autobus.", exEn:"I've got to run, my bus is coming." },
            { id:"b1-urban-party-slang-010", pl:"spadać", en:"to bounce / head off", hint:"To leave. 'Spadam' = I'm out of here.", ex:"Spadam, robi się późno.", exEn:"I'm off, it's getting late." }
          ]
        },
        { id:"b1-swearing",
          name: "Przekleństwa",
          emoji: "🤬",
          mature: true,
          desc: "Polish swearing by strength, from mild curses to the truly vulgar. (18+)",
          cards: [
            { id:"b1-swearing-001", pl:"motyla noga", en:"for crying out loud", strength:"mild", register:"informal", hint:"A jokey minced oath. Literally 'butterfly's leg'. A woman says: zgubiłam.", ex:"Motyla noga, znowu to zgubiłem.", exEn:"For crying out loud, I lost it again." },
            { id:"b1-swearing-002", pl:"jasny gwint", en:"good grief / blimey", strength:"mild", register:"informal", hint:"Old-school, harmless cry of surprise. Literally 'bright screw-thread'. A woman says: zapomniałam.", ex:"Jasny gwint, znowu zapomniałem portfela.", exEn:"Good grief, I forgot my wallet again." },
            { id:"b1-swearing-003", pl:"cholera", en:"damn / bloody hell", strength:"mild", register:"informal", hint:"A classic mild curse of frustration; literally the disease 'cholera'.", ex:"Cholera, znowu korek na obwodnicy.", exEn:"Damn, another jam on the ring road." },
            { id:"b1-swearing-004", pl:"do diabła", en:"the hell / dammit", strength:"mild", register:"informal", hint:"'To the devil' - used like 'what the hell'.", ex:"Co, do diabła, tu się stało?", exEn:"What the hell happened here?" },
            { id:"b1-swearing-005", pl:"do cholery", en:"for God's sake / the hell", strength:"medium", register:"informal", hint:"A step up from 'cholera'; a frustration intensifier. A woman says: byłaś.", ex:"Gdzie ty, do cholery, byłeś?", exEn:"Where the hell were you?" },
            { id:"b1-swearing-006", pl:"gówno", en:"shit / crap", strength:"medium", register:"vulgar", warning:"Vulgar. Out of place at work, in shops and offices, and in any formal conversation.", hint:"Literally 'excrement'. Also means 'nonsense' or 'nothing' ('gówno prawda', 'gówno mnie to obchodzi'). Vulgar - fine among close friends, not in a shop, an office or with strangers.", ex:"Ten telewizor to gówno, w ogóle nie działa.", exEn:"This TV is crap, it doesn't work at all." },
            { id:"b1-swearing-007", pl:"dupa", en:"ass / bum", strength:"medium", register:"vulgar", hint:"'Butt'. In 'do dupy' it means 'rubbish / it sucks'.", ex:"Ten nowy film jest całkowicie do dupy.", exEn:"This new movie completely sucks." },
            { id:"b1-swearing-008", pl:"zawracać dupę", en:"to pester / to bug", strength:"medium", register:"vulgar", hint:"'Nie zawracaj mi dupy' = 'stop bothering me'.", ex:"Nie zawracaj mi teraz dupy, pracuję.", exEn:"Don't bug me right now, I'm working." },
            { id:"b1-swearing-009", pl:"mieć ból dupy", en:"to be butthurt", strength:"medium", register:"vulgar", hint:"To sulk out of petty jealousy. Literally 'to have an ass-ache'.", ex:"Ma ból dupy, bo nie dostał zaproszenia.", exEn:"He's butthurt because he didn't get an invite." },
            { id:"b1-swearing-010", pl:"wkurzać się", en:"to get annoyed", pair:"wkurza\u0107 si\u0119 / wkurzy\u0107 si\u0119", strength:"medium", register:"informal", hint:"The clean, everyday form of the vulgar 'wkurwić się'.", ex:"Przestań, bo zaczynam się wkurzać.", exEn:"Stop it, I'm starting to get annoyed." },
            { id:"b1-swearing-011", pl:"chrzanić", en:"to screw it / to talk rubbish", strength:"medium", register:"informal", hint:"A softened 'pierdolić'. 'Chrzań to' = 'forget it'. Literally 'to horseradish'.", ex:"Chrzanię to, nie robię tego dłużej.", exEn:"Screw it, I'm not doing this anymore." },
            { id:"b1-swearing-012", pl:"pieprzyć", en:"to talk rubbish / to screw (something)", strength:"medium", register:"informal", hint:"Another polite stand-in for 'pierdolić'. 'Nie pieprz' = 'don't talk rubbish'. Literally 'to pepper'.", ex:"Nie pieprz, przecież to nieprawda.", exEn:"Don't talk rubbish, that's not even true." },
            { id:"b1-swearing-013", pl:"kurwa", en:"f*** / f***ing hell", strength:"strong", register:"vulgar", hint:"The all-purpose Polish f-bomb: exclamation, filler or intensifier. Literally 'whore'. Very offensive in formal settings.", ex:"Kurwa, spóźnię się na pociąg.", exEn:"F***, I'm going to miss the train." },
            { id:"b1-swearing-014", pl:"kurwa mać", en:"for f***'s sake / goddammit", strength:"strong", register:"vulgar", hint:"An intensified 'kurwa'; a pure cry of anger.", ex:"Kurwa mać, znowu się zepsuło!", exEn:"For f***'s sake, it broke again!" },
            { id:"b1-swearing-015", pl:"skurwysyn", en:"son of a b***h / motherf***er", strength:"vulgar", register:"vulgar", hint:"Highly offensive when aimed at a person.", ex:"Ten skurwysyn porysował mi samochód.", exEn:"That son of a b***h scratched my car." },
            { id:"b1-swearing-016", pl:"chuj", en:"d*** / prick", strength:"strong", register:"vulgar", hint:"Literally the male organ. 'Chuj wie' = 'who the hell knows'.", ex:"Chuj wie, gdzie on teraz jest.", exEn:"Who the hell knows where he is now." },
            { id:"b1-swearing-017", pl:"chujowy", en:"shitty / crappy", strength:"strong", register:"vulgar", hint:"Adjective: lousy, terrible quality.", ex:"Pogoda na weekend ma być chujowa.", exEn:"The weekend weather is supposed to be shitty." },
            { id:"b1-swearing-018", pl:"pierdolić", en:"to not give a f*** / to screw it", strength:"strong", register:"vulgar", hint:"'Pierdolę to' = 'f*** it, I don't care'. Also 'to talk crap'.", ex:"Pierdolę to, idę do domu.", exEn:"F*** this, I'm going home." },
            { id:"b1-swearing-019", pl:"spierdalać", en:"to f*** off", strength:"strong", register:"vulgar", hint:"'Spierdalaj!' = 'f*** off / get lost!'.", ex:"Spierdalaj stąd, zanim wezwę policję.", exEn:"F*** off before I call the police." },
            { id:"b1-swearing-020", pl:"odpierdalać", en:"to act up / to mess around", strength:"strong", register:"vulgar", hint:"'Co ty odpierdalasz?' = 'what the hell are you doing?!'.", ex:"Co ci dzisiaj odpierdala?", exEn:"What's gotten into you today?" },
            { id:"b1-swearing-021", pl:"wpierdol", en:"a beating / a hiding", strength:"strong", register:"vulgar", hint:"'Dostać wpierdol' = to get beaten up.", ex:"Uważaj, bo zaraz dostaniesz wpierdol.", exEn:"Watch it, or you'll get a hiding." },
            { id:"b1-swearing-022", pl:"przypierdolić się", en:"to pick on / to nitpick", strength:"strong", register:"vulgar", hint:"To nag or provoke unfairly. 'Przypierdolić się do kogoś' = to pick on someone.", ex:"Szef znowu się do mnie przypierdolił.", exEn:"The boss picked on me again." },
            { id:"b1-swearing-023", pl:"jebać", en:"to f*** (very vulgar, all-purpose)", strength:"vulgar", register:"vulgar", hint:"The most vulgar all-purpose verb. 'Jebać to' = 'f*** it'. Avoid in polite company.", ex:"Jebać to, robimy po swojemu.", exEn:"F*** it, we'll do it our own way." },
            { id:"b1-swearing-024", pl:"wkurwić się", en:"to get pissed off", strength:"strong", register:"vulgar", hint:"The vulgar form of 'wkurzać się' - seriously angry. A woman says: wkurwiłam / usłyszałam.", ex:"Strasznie się wkurwiłem, kiedy to usłyszałem.", exEn:"I got seriously pissed off when I heard that." },
            { id:"b1-swearing-025", pl:"zjebać", en:"to mess up / to f*** up", strength:"strong", register:"vulgar", hint:"To botch something badly. 'Zjebałem to' = 'I f***ed it up'. A woman says: zjebałam.", ex:"Całkowicie zjebałem ten egzamin.", exEn:"I completely f***ed up that exam." },
            { id:"b1-swearing-026", pl:"mieć wyjebane", en:"to not give a f***", strength:"strong", register:"vulgar", hint:"Total indifference. 'Mam to wyjebane' = 'I couldn't care less'.", ex:"Mam na to wyjebane, róbcie co chcecie.", exEn:"I don't give a f*** about it, do what you want." },
            { id:"b1-swearing-027", pl:"pojebany", en:"crazy / f***ed up", strength:"strong", register:"vulgar", hint:"Adjective for a wild situation or an unstable person.", ex:"Ten pomysł jest całkowicie pojebany.", exEn:"This idea is completely f***ed up." },
            { id:"b1-swearing-028", pl:"zajebiście", en:"awesome / bloody brilliant", strength:"strong", register:"vulgar", hint:"Positive! Strong root, but means 'fantastic'. Adjective form: 'zajebisty'.", ex:"Na koncercie było zajebiście, najlepszy w życiu.", exEn:"The concert was bloody brilliant, the best ever." }
          ]
        }
      ]
    }
  );
})();
