/* Po polsku - lesson data: A1
   Registered onto window.PP_LEVELS by index.html (loaded in order).
   Safe to edit this file alone; a syntax error here shows a load
   message instead of breaking the app engine. */
(function(){
  window.PP_LEVELS = window.PP_LEVELS || [];
  window.PP_LEVELS.push(
  { id:"a1",
      level: "A1",
      blurb: "Survival basics",
      topics: [
        { id:"a1-first-phrases",
          name: "Pierwsze zwroty",
          emoji: "👋",
          desc: "Greetings and the phrases you need in week one",
          cards: [
            { id:"a1-first-phrases-001", pl:"Dzień dobry", en:"Good morning / Hello", hint:"Formal - use any time of day until evening.", ex:"Dzień dobry, poproszę bilet.", exEn:"Hello, one ticket please." },
            { id:"a1-first-phrases-002", pl:"Dobry wieczór", en:"Good evening", hint:"Swap in for dzień dobry once it gets dark.", ex:"Dobry wieczór, stolik dla dwóch osób.", exEn:"Good evening, a table for two." },
            { id:"a1-first-phrases-003", pl:"Cześć", en:"Hi / Bye", hint:"Informal - for friends, not officials.", ex:"Cześć, dawno się nie widzieliśmy!", exEn:"Hi, long time no see!" },
            { id:"a1-first-phrases-004", pl:"Do widzenia", en:"Goodbye", hint:"The polite, all-purpose goodbye.", ex:"Do widzenia, do jutra!", exEn:"Goodbye, see you tomorrow!" },
            { id:"a1-first-phrases-005", pl:"Na razie", en:"See you / Bye for now", senseGroups:["farewell-see-you"], hint:"Casual, between friends.", ex:"Na razie, muszę już iść.", exEn:"See you, I have to go now." },
            { id:"a1-first-phrases-006", pl:"Dziękuję", en:"Thank you", hint:"'Dzięki' is the casual short form.", ex:"Dziękuję za pomoc.", exEn:"Thank you for your help." },
            { id:"a1-first-phrases-007", pl:"Proszę", en:"Please / Here you go / You're welcome", senseGroups:["response-youre-welcome"], hint:"One word, several jobs.", ex:"Proszę, to dla ciebie.", exEn:"Here you go, this is for you." },
            { id:"a1-first-phrases-008", pl:"Przepraszam", en:"Sorry / Excuse me", hint:"Also to get someone's attention.", ex:"Przepraszam, gdzie jest wyjście?", exEn:"Excuse me, where is the exit?" },
            { id:"a1-first-phrases-009", pl:"Tak", en:"Yes", relatedIds:["a1-first-phrases-028"], relationType:"contrast", hint:"One of the two you'll say most often.", ex:"Tak, poproszę.", exEn:"Yes, please." },
            { id:"a1-first-phrases-028", pl:"Nie", en:"No", relatedIds:["a1-first-phrases-009"], relationType:"contrast", hint:"The other one you'll say most often.", ex:"Nie, dziękuję.", exEn:"No, thank you." },
            { id:"a1-first-phrases-010", pl:"Nie rozumiem", en:"I don't understand", hint:"Add 'po polsku' for 'in Polish'.", ex:"Przepraszam, nie rozumiem.", exEn:"Sorry, I don't understand." },
            { id:"a1-first-phrases-011", pl:"Nie wiem", en:"I don't know", hint:"Very handy, very common.", ex:"Nie wiem, gdzie to jest.", exEn:"I don't know where it is." },
            { id:"a1-first-phrases-012", pl:"Czy mówi pan po angielsku?", en:"Do you speak English?", hint:"To a man. To a woman say 'pani' instead of 'pan'.", ex:"Przepraszam, czy mówi pan po angielsku?", exEn:"Excuse me, do you speak English?" },
            { id:"a1-first-phrases-013", pl:"Jak masz na imię?", en:"What's your name?", hint:"Informal. Formal: 'Jak się pan/pani nazywa?'", ex:"Cześć, jak masz na imię?", exEn:"Hi, what's your name?" },
            { id:"a1-first-phrases-014", cardType:"template", pl:"Mam na imię...", en:"My name is...", hint:"Follow with your first name.", ex:"Mam na imię Anna.", exEn:"My name is Anna.", pattern:"Mam na imię {imię}." },
            { id:"a1-first-phrases-015", pl:"Miło mi", en:"Nice to meet you", hint:"Short and natural when introduced.", ex:"Miło mi cię poznać.", exEn:"Nice to meet you." },
            { id:"a1-first-phrases-016", pl:"Jak się masz?", en:"How are you?", hint:"Informal. In Poland this is a real question, not a passing hello - ask it when you actually want to know, and expect a real answer. A common reply: 'dobrze' - good.", ex:"Cześć Marek, jak się masz?", exEn:"Hi Marek, how are you?" },
            { id:"a1-first-phrases-017", pl:"Co słychać?", en:"What's up? / How's it going?", senseGroups:["greeting-whats-up"], hint:"Casual and friendly. Reply lightly: 'wszystko dobrze' or 'po staremu' (same as always).", ex:"Hej, co słychać u ciebie?", exEn:"Hey, how's it going with you?" },
            { id:"a1-first-phrases-018", pl:"Co tam?", en:"What's up? (very casual)", senseGroups:["greeting-whats-up"], hint:"Breezy, among friends - lighter than 'jak się masz?'. Often answered with a shrug: 'nic nowego' (nothing new).", ex:"Co tam, Kasia?", exEn:"What's up, Kasia?" },
            { id:"a1-first-phrases-019", pl:"Wszystko w porządku", en:"Everything's fine / All good", senseGroups:["response-all-good"], hint:"Also asked as a question to check on someone.", ex:"Wszystko w porządku, dziękuję.", exEn:"Everything's fine, thanks." },
            { id:"a1-first-phrases-020", cardType:"template", pl:"Poproszę...", en:"I'd like... (ordering)", hint:"Softer than 'chcę'. 'Poproszę kawę' - a coffee, please.", ex:"Poproszę kawę i wodę.", exEn:"A coffee and a water, please.", pattern:"Poproszę {coś}." },
            { id:"a1-first-phrases-021", pl:"Ile to kosztuje?", en:"How much is it?", hint:"Your everyday shopping question.", ex:"Przepraszam, ile to kosztuje?", exEn:"Excuse me, how much is it?" },
            { id:"a1-first-phrases-022", pl:"Gdzie jest toaleta?", en:"Where is the toilet?", hint:"'Gdzie jest...' = where is... for anything.", ex:"Przepraszam, gdzie jest toaleta?", exEn:"Excuse me, where is the toilet?" },
            { id:"a1-first-phrases-023", pl:"Nie ma za co", en:"You're welcome / Don't mention it", senseGroups:["response-youre-welcome"], hint:"The natural reply when someone thanks you.", ex:"Dziękuję! - Nie ma za co.", exEn:"Thank you! - You're welcome." },
            { id:"a1-first-phrases-024", pl:"Smacznego!", en:"Enjoy your meal!", hint:"Said before eating - by staff, hosts, or anyone at the table.", ex:"Proszę bardzo, smacznego!", exEn:"Here you are, enjoy your meal!" },
            { id:"a1-first-phrases-025", pl:"Na zdrowie!", en:"Cheers! / Bless you!", hint:"A toast when drinking - and also what you say when someone sneezes.", ex:"Na zdrowie! Za nasze spotkanie!", exEn:"Cheers! To our meeting!" },
            { id:"a1-first-phrases-026", pl:"Powodzenia!", en:"Good luck!", hint:"For an exam, a trip, anything ahead.", ex:"Powodzenia na egzaminie!", exEn:"Good luck on the exam!" },
            { id:"a1-first-phrases-027", pl:"Do zobaczenia", en:"See you (soon)", senseGroups:["farewell-see-you"], hint:"Warmer than 'do widzenia'; you expect to meet again.", ex:"Dziękuję za dziś, do zobaczenia!", exEn:"Thanks for today, see you!" }
          ]
        },
        { id:"a1-numbers-prices",
          name: "Liczby i ceny",
          emoji: "🔢",
          desc: "Numbers, money and paying for things",
          cards: [
            { id:"a1-numbers-prices-001", pl:"jeden", en:"one", hint:"The number 1.", ex:"Poproszę jeden bilet.", exEn:"One ticket, please." },
            { id:"a1-numbers-prices-002", pl:"dwa", en:"two", hint:"The number 2.", ex:"Mam dwa koty.", exEn:"I have two cats." },
            { id:"a1-numbers-prices-003", pl:"trzy", en:"three", hint:"The number 3.", ex:"Trzy kawy poproszę.", exEn:"Three coffees, please." },
            { id:"a1-numbers-prices-004", pl:"cztery", en:"four", hint:"The number 4.", ex:"Stolik na cztery osoby.", exEn:"A table for four." },
            { id:"a1-numbers-prices-005", pl:"pięć", en:"five", hint:"The number 5.", ex:"To kosztuje pięć złotych.", exEn:"It costs five zloty." },
            { id:"a1-numbers-prices-006", pl:"sześć", en:"six", hint:"The number 6.", ex:"Mam sześć jabłek.", exEn:"I have six apples." },
            { id:"a1-numbers-prices-007", pl:"siedem", en:"seven", hint:"The number 7.", ex:"Autobus numer siedem.", exEn:"Bus number seven." },
            { id:"a1-numbers-prices-008", pl:"osiem", en:"eight", hint:"The number 8.", ex:"Pracuję osiem godzin.", exEn:"I work eight hours." },
            { id:"a1-numbers-prices-009", pl:"dziewięć", en:"nine", hint:"The number 9.", ex:"Dziewięć złotych za bilet.", exEn:"Nine zloty for a ticket." },
            { id:"a1-numbers-prices-010", pl:"dziesięć", en:"ten", hint:"The number 10.", ex:"Tramwaj przyjedzie za dziesięć minut.", exEn:"The tram arrives in ten minutes." },
            { id:"a1-numbers-prices-011", pl:"dwadzieścia", en:"twenty", hint:"The number 20.", ex:"To kosztuje dwadzieścia złotych.", exEn:"It costs twenty zloty." },
            { id:"a1-numbers-prices-012", pl:"sto", en:"a hundred", hint:"The number 100.", ex:"Sto złotych, proszę.", exEn:"A hundred zloty, please." },
            { id:"a1-numbers-prices-013", pl:"złoty", en:"zloty (the currency)", hint:"PLN. Plural forms: złote / złotych.", ex:"Płacę pięćdziesiąt złotych.", exEn:"I'm paying fifty zloty." },
            { id:"a1-numbers-prices-014", pl:"grosz", en:"grosz (a penny)", hint:"1/100 of a złoty.", ex:"To kosztuje dwa złote pięćdziesiąt groszy.", exEn:"It costs two zloty fifty." },
            { id:"a1-numbers-prices-015", pl:"Ile płacę?", en:"How much do I pay?", hint:"Ask this at the till.", ex:"Ile płacę za wszystko?", exEn:"How much do I pay for everything?" },
            { id:"a1-numbers-prices-016", pl:"Czy mogę zapłacić kartą?", en:"Can I pay by card?", hint:"Card is accepted almost everywhere.", ex:"Czy mogę zapłacić kartą?", exEn:"Can I pay by card?" },
            { id:"a1-numbers-prices-017", pl:"gotówka", en:"cash", senseGroups:["money-cash"], hint:"'gotówką' = in cash.", ex:"Płacę gotówką.", exEn:"I'm paying in cash." },
            { id:"a1-numbers-prices-018", pl:"razem", en:"together / in total", hint:"Useful when splitting or totalling.", ex:"Ile razem?", exEn:"How much in total?" },
            { id:"a1-numbers-prices-019", pl:"reszta", en:"change (money back)", hint:"Feminine noun. 'Reszty nie trzeba' uses the genitive of negation.", ex:"Reszty nie trzeba.", exEn:"Keep the change." },
            { id:"a1-numbers-prices-020", pl:"drogo", en:"expensive", typeItCue:"adverb: how much it costs", relatedIds:["a1-numbers-prices-021"], relationType:"contrast", hint:"Adverb: 'za drogo' = too expensive.", ex:"To za drogo!", exEn:"That's too expensive!" },
            { id:"a1-numbers-prices-021", pl:"tanio", en:"cheap", typeItCue:"adverb: how much it costs", relatedIds:["a1-numbers-prices-020"], relationType:"contrast", hint:"Adverb: the opposite of 'drogo'.", ex:"Tutaj jest tanio.", exEn:"It's cheap here." }
          ]
        },
        { id:"a1-cafe",
          name: "W kawiarni",
          emoji: "☕",
          desc: "Ordering coffee, snacks and drinks",
          cards: [
            { id:"a1-cafe-001", pl:"kawa", en:"coffee", hint:"Feminine noun.", ex:"Poproszę kawę z mlekiem.", exEn:"A coffee with milk, please." },
            { id:"a1-cafe-002", pl:"herbata", en:"tea", hint:"Feminine noun.", ex:"Wolę herbatę niż kawę.", exEn:"I prefer tea to coffee." },
            { id:"a1-cafe-003", pl:"woda", en:"water", hint:"gazowana = sparkling, niegazowana = still.", ex:"Poproszę wodę niegazowaną.", exEn:"Still water, please." },
            { id:"a1-cafe-004", pl:"mleko", en:"milk", hint:"Neuter noun.", ex:"Kawa z mlekiem, proszę.", exEn:"Coffee with milk, please." },
            { id:"a1-cafe-005", pl:"cukier", en:"sugar", hint:"Masculine noun.", ex:"Bez cukru, dziękuję.", exEn:"No sugar, thank you." },
            { id:"a1-cafe-006", pl:"sok", en:"juice", hint:"'sok pomarańczowy' = orange juice.", ex:"Poproszę sok pomarańczowy.", exEn:"An orange juice, please." },
            { id:"a1-cafe-007", pl:"ciasto", en:"cake", hint:"A slice = 'kawałek'.", ex:"Kawałek ciasta poproszę.", exEn:"A slice of cake, please." },
            { id:"a1-cafe-008", pl:"kanapka", en:"sandwich", hint:"'z serem' = with cheese.", ex:"Poproszę kanapkę z serem.", exEn:"A cheese sandwich, please." },
            { id:"a1-cafe-009", pl:"Co pan poleca?", en:"What do you recommend?", hint:"To a woman: 'Co pani poleca?'", ex:"Nie wiem, co wybrać. Co pan poleca?", exEn:"I don't know what to pick. What do you recommend?" },
            { id:"a1-cafe-010", cardType:"template", pl:"Dla mnie...", en:"For me... (ordering)", hint:"Point and name your choice.", ex:"Dla mnie herbata, proszę.", exEn:"A tea for me, please.", pattern:"Dla mnie {coś}." },
            { id:"a1-cafe-011", pl:"na wynos", en:"to take away", hint:"'na miejscu' = to have here.", ex:"Na wynos, proszę.", exEn:"To take away, please." },
            { id:"a1-cafe-012", pl:"na miejscu", en:"to have here / dine in", hint:"The opposite of na wynos.", ex:"Na miejscu czy na wynos?", exEn:"To have here or take away?" },
            { id:"a1-cafe-013", pl:"Smacznego!", en:"Enjoy your meal!", hint:"Said before eating. The usual reply is 'Dziękuję'. If the other person is also eating, you can add 'nawzajem' (you too).", ex:"Smacznego!", exEn:"Enjoy your meal!" },
            { id:"a1-cafe-014", pl:"stolik", en:"table", typeItCue:"small or café table", hint:"Diminutive of 'stół'.", ex:"Czy ten stolik jest wolny?", exEn:"Is this table free?" },
            { id:"a1-cafe-015", pl:"karta", en:"menu", acceptedAnswers:["menu"], variants:[{form:"menu",label:"synonym"}], hint:"Both are used.", ex:"Poproszę kartę.", exEn:"The menu, please." },
            { id:"a1-cafe-016", pl:"Czy jest wi-fi?", en:"Is there wi-fi?", hint:"Ask for the 'hasło' - password.", ex:"Przepraszam, czy jest tu wi-fi?", exEn:"Excuse me, is there wi-fi here?" },
            { id:"a1-cafe-017", pl:"gorący", en:"hot", relatedIds:["a1-cafe-021"], relationType:"contrast", hint:"Adjective - endings change by gender.", ex:"Kawa jest gorąca.", exEn:"The coffee is hot." },
            { id:"a1-cafe-021", pl:"zimny", en:"cold", relatedIds:["a1-cafe-017"], relationType:"contrast", hint:"Adjective - the opposite of 'gorący'.", ex:"Poproszę zimną wodę.", exEn:"Cold water, please." },
            { id:"a1-cafe-018", pl:"duży", en:"big", relatedIds:["a1-cafe-022"], relationType:"contrast", hint:"For sizes.", ex:"Dużą kawę poproszę.", exEn:"A large coffee, please." },
            { id:"a1-cafe-022", pl:"mały", en:"small", relatedIds:["a1-cafe-018"], relationType:"contrast", hint:"The opposite of 'duży'.", ex:"Poproszę małą kawę.", exEn:"A small coffee, please." },
            { id:"a1-cafe-019", pl:"Coś jeszcze?", en:"Anything else?", hint:"What staff often ask you. You'll hear both 'Coś jeszcze?' and 'Jeszcze coś?'.", ex:"Coś jeszcze do picia?", exEn:"Anything else to drink?" },
            { id:"a1-cafe-020", pl:"To wszystko", en:"That's all", hint:"To close your order.", ex:"Nie, dziękuję, to wszystko.", exEn:"No thanks, that's all." }
          ]
        },
        { id:"a1-directions",
          name: "Orientacja",
          emoji: "🧭",
          desc: "Finding your way and asking directions",
          cards: [
            { id:"a1-directions-001", cardType:"template", pl:"Gdzie jest...?", en:"Where is...?", hint:"The key question for anything.", ex:"Gdzie jest apteka?", exEn:"Where is the pharmacy?", pattern:"Gdzie jest {miejsce}?" },
            { id:"a1-directions-002", pl:"na lewo", en:"to the left", hint:"For turning use 'w lewo': skręcić w lewo.", ex:"Toaleta jest na lewo.", exEn:"The toilet is to the left." },
            { id:"a1-directions-003", pl:"na prawo", en:"to the right", hint:"Also 'w prawo'.", ex:"Sklep jest na prawo.", exEn:"The shop is on the right." },
            { id:"a1-directions-004", pl:"prosto", en:"straight ahead", hint:"Direction, not 'simple' here.", ex:"Proszę iść prosto.", exEn:"Go straight ahead." },
            { id:"a1-directions-005", pl:"blisko", en:"near / close", hint:"Opposite of daleko.", ex:"To jest bardzo blisko.", exEn:"It's very close." },
            { id:"a1-directions-006", pl:"daleko", en:"far", hint:"'Czy to daleko?' = Is it far?", ex:"Czy to daleko stąd?", exEn:"Is it far from here?" },
            { id:"a1-directions-007", pl:"tutaj", en:"here", acceptedAnswers:["tu"], variants:[{form:"tu",label:"synonym"}], hint:"Both are common.", ex:"Proszę się zatrzymać tutaj.", exEn:"Please stop here." },
            { id:"a1-directions-008", pl:"tam", en:"there", hint:"Point as you say it.", ex:"Sklep jest tam.", exEn:"The shop is over there." },
            { id:"a1-directions-009", pl:"obok", en:"next to / beside", hint:"Followed by the genitive.", ex:"Apteka jest obok banku.", exEn:"The pharmacy is next to the bank." },
            { id:"a1-directions-010", pl:"za rogiem", en:"around the corner", hint:"'róg' = corner.", ex:"Piekarnia jest za rogiem.", exEn:"The bakery is around the corner." },
            { id:"a1-directions-011", pl:"ulica", en:"street", hint:"Shortened to 'ul.' in addresses.", ex:"Mieszkam na ulicy Długiej.", exEn:"I live on Długa Street." },
            { id:"a1-directions-012", pl:"centrum", en:"the centre / downtown", hint:"City centre.", ex:"Idę do centrum.", exEn:"I'm going to the centre." },
            { id:"a1-directions-013", pl:"sklep", en:"shop", hint:"'sklep spożywczy' = grocery shop.", ex:"Gdzie jest najbliższy sklep?", exEn:"Where's the nearest shop?" },
            { id:"a1-directions-014", pl:"dworzec", en:"station (train / bus)", hint:"'dworzec kolejowy' = train station.", ex:"Jak dojść na dworzec?", exEn:"How do I get to the station?" },
            { id:"a1-directions-015", pl:"bank", en:"bank", hint:"'bankomat' = ATM.", ex:"Szukam banku.", exEn:"I'm looking for a bank." },
            { id:"a1-directions-016", cardType:"template", pl:"Jak dojść do...?", en:"How do I get to...? (on foot)", hint:"For walking directions.", ex:"Jak dojść do rynku?", exEn:"How do I get to the market square?", pattern:"Jak dojść do {miejsce (dopełniacz)}?" },
            { id:"a1-directions-017", pl:"mapa", en:"map", hint:"Feminine noun.", ex:"Mam mapę w telefonie.", exEn:"I have a map on my phone." },
            { id:"a1-directions-018", pl:"skręcić", en:"to turn", pair:"skręcać / skręcić", hint:"'skręcić w prawo/lewo'.", ex:"Proszę skręcić w prawo.", exEn:"Turn right, please." },
            { id:"a1-directions-019", pl:"róg", en:"corner", hint:"'na rogu' = on the corner.", ex:"Na rogu jest kawiarnia.", exEn:"There's a café on the corner." },
            { id:"a1-directions-020", pl:"w pobliżu", en:"nearby / in the area", hint:"'niedaleko' works too.", ex:"Czy jest tu w pobliżu bankomat?", exEn:"Is there an ATM nearby?" }
          ]
        },
        { id:"a1-about-me",
          name: "O mnie",
          emoji: "🙋",
          desc: "Introducing yourself and getting understood",
          cards: [
            { id:"a1-about-me-001", cardType:"template", pl:"Nazywam się...", en:"My name is... (full name)", hint:"Use with your surname.", ex:"Nazywam się Jan Kowalski.", exEn:"My name is Jan Kowalski.", pattern:"Nazywam się {imię i nazwisko}." },
            { id:"a1-about-me-002", cardType:"template", pl:"Jestem z...", en:"I'm from...", hint:"Country takes the genitive.", ex:"Jestem z Hiszpanii.", exEn:"I'm from Spain.", pattern:"Jestem z {miejsce (dopełniacz)}." },
            { id:"a1-about-me-003", cardType:"template", pl:"Mieszkam w...", en:"I live in...", hint:"City takes the locative.", ex:"Mieszkam w Krakowie.", exEn:"I live in Kraków.", pattern:"Mieszkam w {miejsce (miejscownik)}." },
            { id:"a1-about-me-004", pl:"Uczę się polskiego", en:"I'm learning Polish", hint:"'uczyć się' + genitive.", ex:"Uczę się polskiego od roku.", exEn:"I've been learning Polish for a year." },
            { id:"a1-about-me-005", cardType:"template", pl:"Pracuję jako...", en:"I work as...", hint:"Add your job after 'jako'.", ex:"Pracuję jako programista.", exEn:"I work as a programmer.", pattern:"Pracuję jako {zawód}." },
            { id:"a1-about-me-006", cardType:"template", pl:"Mam... lat", en:"I'm ... years old", hint:"'Mam trzydzieści lat.'", ex:"Mam trzydzieści lat.", exEn:"I'm thirty years old.", pattern:"Mam {liczba} lat." },
            { id:"a1-about-me-007", pl:"Nie mówię dobrze po polsku", en:"I don't speak Polish well", hint:"Buys you patience.", ex:"Przepraszam, nie mówię dobrze po polsku.", exEn:"Sorry, I don't speak Polish well." },
            { id:"a1-about-me-008", pl:"Mówię trochę po polsku", en:"I speak a little Polish", hint:"'trochę' = a little.", ex:"Mówię trochę po polsku.", exEn:"I speak a little Polish." },
            { id:"a1-about-me-009", pl:"Czy może pan powtórzyć?", en:"Can you repeat that?", hint:"To a woman: 'pani'.", ex:"Przepraszam, czy może pan powtórzyć?", exEn:"Sorry, can you repeat that?" },
            { id:"a1-about-me-010", pl:"Proszę mówić wolniej", en:"Please speak more slowly", hint:"A lifesaver early on.", ex:"Proszę mówić wolniej.", exEn:"Please speak more slowly." },
            { id:"a1-about-me-011", pl:"Nie jestem stąd", en:"I'm not from here", hint:"'stąd' = from here.", ex:"Nie jestem stąd, jestem turystą.", exEn:"I'm not from here, I'm a tourist." },
            { id:"a1-about-me-012", pl:"Jak się to pisze?", en:"How do you spell it?", hint:"For names and addresses.", ex:"Jak się pisze pana nazwisko?", exEn:"How do you spell your surname?" },
            { id:"a1-about-me-013", pl:"Mam pytanie", en:"I have a question", hint:"Polite way to start.", ex:"Przepraszam, mam pytanie.", exEn:"Excuse me, I have a question." },
            { id:"a1-about-me-014", pl:"Rozumiem", en:"I understand", hint:"'Nie rozumiem' = I don't.", ex:"Tak, teraz rozumiem.", exEn:"Yes, now I understand." },
            { id:"a1-about-me-015", pl:"Czy może mi pan pomóc?", en:"Can you help me?", hint:"To a woman: 'Czy może mi pani...'", ex:"Przepraszam, czy może mi pan pomóc?", exEn:"Excuse me, can you help me?" },
            { id:"a1-about-me-016", pl:"Skąd pan jest?", en:"Where are you from?", hint:"To a woman: 'Skąd pani jest?'", ex:"A skąd pan jest?", exEn:"And where are you from?" },
            { id:"a1-about-me-017", pl:"mój", en:"my (m / f)", acceptedAnswers:["moja"], variants:[{form:"mój",label:"m"},{form:"moja",label:"f"}], relationType:"gender-variant", hint:"Agrees with the noun's gender.", ex:"To jest mój telefon.", exEn:"This is my phone." },
            { id:"a1-about-me-018", pl:"Miłego dnia!", en:"Have a nice day!", hint:"Warm way to end a chat.", ex:"Dziękuję, miłego dnia!", exEn:"Thanks, have a nice day!" },
            { id:"a1-about-me-019", pl:"Do zobaczenia", en:"See you (later)", senseGroups:["farewell-see-you"], hint:"Friendlier than 'do widzenia'.", ex:"Do zobaczenia jutro.", exEn:"See you tomorrow." },
            { id:"a1-about-me-020", pl:"Nie ma problemu", en:"No problem", hint:"Very common reassurance.", ex:"Nie ma problemu!", exEn:"No problem!" },
            { id:"a1-about-me-021", pl:"numer telefonu", en:"phone number", hint:"Masculine phrase. 'Jaki masz numer?' = what's your number?", ex:"Zapiszę twój numer telefonu.", exEn:"I'll save your phone number." },
            { id:"a1-about-me-022", pl:"adres e-mail", en:"e-mail address", hint:"'małpa' (@) = the at sign, literally 'monkey'.", ex:"Podaj mi swój adres e-mail.", exEn:"Give me your e-mail address." },
            { id:"a1-about-me-023", pl:"adres", en:"address", hint:"Masculine noun. 'Pod jakim adresem?' = at what address?", ex:"Jaki jest twój adres?", exEn:"What's your address?" },
            { id:"a1-about-me-024", pl:"żonaty", en:"married (man / woman)", acceptedAnswers:["mężatka"], variants:[{form:"żonaty",label:"m"},{form:"mężatka",label:"f"}], relationType:"gender-variant", hint:"A man is 'żonaty', a woman is 'mężatka'.", ex:"Jestem żonaty od pięciu lat.", exEn:"I've been married for five years. A woman: Jestem mężatką." },
            { id:"a1-about-me-025", pl:"kawaler", en:"single / unmarried (man / woman)", acceptedAnswers:["panna"], variants:[{form:"kawaler",label:"m"},{form:"panna",label:"f"}], relationType:"gender-variant", register:"formal", hint:"These are the official marital-status words you tick on forms, and they sound old-fashioned as everyday labels. In conversation Poles say 'jestem singlem' / 'jestem singielką', or simply 'nie jestem w związku'.", ex:"W rubryce stan cywilny wpisałem: kawaler.", exEn:"In the marital-status box I wrote: kawaler (single). A woman: panna." },
            { id:"a1-about-me-026", pl:"nauczyciel", en:"teacher (m)", relatedIds:["a1-about-me-029"], relationType:"gender-variant", hint:"'Pracuję jako nauczyciel'.", ex:"On jest nauczycielem.", exEn:"He is a teacher." },
            { id:"a1-about-me-029", pl:"nauczycielka", en:"teacher (f)", relatedIds:["a1-about-me-026"], relationType:"gender-variant", hint:"The feminine form of 'nauczyciel'.", ex:"Moja mama jest nauczycielką.", exEn:"My mum is a teacher." },
            { id:"a1-about-me-027", pl:"lekarz", en:"doctor (m)", relatedIds:["a1-about-me-030"], relationType:"gender-variant", hint:"'iść do lekarza' = to go to the doctor.", ex:"On jest lekarzem w szpitalu.", exEn:"He is a doctor at the hospital." },
            { id:"a1-about-me-030", pl:"lekarka", en:"doctor (f)", relatedIds:["a1-about-me-027"], relationType:"gender-variant", senseGroups:["profession-doctor"], hint:"The feminine form of 'lekarz'.", ex:"Moja siostra jest lekarką.", exEn:"My sister is a doctor." },
            { id:"a1-about-me-028", pl:"kierowca", en:"driver", hint:"Masculine, but ends in -a. Same form for a woman.", ex:"Mój brat jest kierowcą autobusu.", exEn:"My brother is a bus driver." }
          ]
        },
        { id:"a1-morning-routine",
          name: "Poranna rutyna",
          emoji: "⏰",
          desc: "Getting up, showering, getting dressed, and having breakfast",
          cards: [
            { id:"a1-morning-routine-001", pl:"budzik", en:"alarm clock", hint:"Masculine noun.", ex:"Mój budzik dzwoni o siódmej rano.", exEn:"My alarm clock rings at seven in the morning." },
            { id:"a1-morning-routine-002", pl:"budzić się", en:"to wake up", pair:"budzić się / obudzić się", hint:"Verb. 'Budzę się' = I wake up.", ex:"Budzę się wcześnie rano.", exEn:"I wake up early in the morning." },
            { id:"a1-morning-routine-003", pl:"wstawać", en:"to get up", pair:"wstawać / wstać", hint:"Verb. 'Wstaję' = I get up.", ex:"Budzę się o szóstej, ale wstaję o wpół do siódmej.", exEn:"I wake up at six, but I get up at half past six." },
            { id:"a1-morning-routine-004", pl:"łazienka", en:"bathroom", hint:"Feminine noun.", ex:"Najpierw idę do łazienki.", exEn:"First, I go to the bathroom." },
            { id:"a1-morning-routine-005", pl:"brać prysznic", en:"to take a shower", pair:"brać / wziąć prysznic", hint:"Verb. 'Biorę prysznic' = I take a shower.", ex:"Rano zazwyczaj biorę szybki prysznic.", exEn:"In the morning, I usually take a quick shower." },
            { id:"a1-morning-routine-006", pl:"myć zęby", en:"to brush teeth", pair:"myć / umyć zęby", hint:"Literally 'to wash teeth'. 'Myję zęby' = I brush my teeth.", ex:"Po śniadaniu myję zęby.", exEn:"I brush my teeth after breakfast." },
            { id:"a1-morning-routine-007", pl:"ręcznik", en:"towel", hint:"Masculine noun.", ex:"Gdzie jest mój czysty ręcznik?", exEn:"Where is my clean towel?" },
            { id:"a1-morning-routine-008", pl:"ubierać się", en:"to get dressed", pair:"ubierać się / ubrać się", hint:"Verb. 'Ubieram się' = I get dressed.", ex:"Biorę prysznic i szybko się ubieram.", exEn:"I take a shower and get dressed quickly." },
            { id:"a1-morning-routine-009", pl:"ubranie", en:"clothes", hint:"Neuter noun. Often used in singular.", ex:"Zakładam czyste ubranie.", exEn:"I put on clean clothes." },
            { id:"a1-morning-routine-010", pl:"śniadanie", en:"breakfast", hint:"Neuter noun. 'Na śniadanie' = for breakfast.", ex:"Co jesz na śniadanie?", exEn:"What do you eat for breakfast?" },
            { id:"a1-morning-routine-011", pl:"robić śniadanie", en:"to make breakfast", pair:"robić / zrobić śniadanie", hint:"Verb. 'Robię' = I make/do.", ex:"Robię śniadanie dla mojej rodziny.", exEn:"I am making breakfast for my family." },
            { id:"a1-morning-routine-012", pl:"jeść śniadanie", en:"to eat breakfast", pair:"jeść / zjeść śniadanie", hint:"Verb. 'Jem' = I eat.", ex:"Codziennie jem śniadanie w domu.", exEn:"I eat breakfast at home every day." },
            { id:"a1-morning-routine-013", pl:"Jestem głodny", en:"I am hungry", hint:"A woman says 'Jestem głodna'.", ex:"Rano zawsze jestem bardzo głodny.", exEn:"I am always very hungry in the morning." },
            { id:"a1-morning-routine-014", pl:"najpierw", en:"first", hint:"Used for sequencing actions.", ex:"Najpierw piję kawę, a potem jem.", exEn:"First I drink coffee, and then I eat." },
            { id:"a1-morning-routine-015", pl:"potem", en:"then / later", senseGroups:["time-later"], hint:"Used to describe what happens next.", ex:"Jem śniadanie, a potem ubieram się.", exEn:"I eat breakfast, and then I get dressed." },
            { id:"a1-morning-routine-016", pl:"spieszyć się", en:"to be in a hurry", pair:"spieszyć się / pospieszyć się", hint:"Verb. 'Spieszę się' = I am in a hurry (a state). The perfective 'pospieszyć się' means to hurry up on one particular occasion: 'Pospiesz się!' = Hurry up!", ex:"Nie mam czasu na śniadanie, spieszę się do pracy.", exEn:"I don't have time for breakfast, I am in a hurry to work." },
            { id:"a1-morning-routine-017", pl:"wychodzić z domu", en:"to leave the house", pair:"wychodzić / wyjść z domu", hint:"Verb. 'Wychodzę' = I am leaving.", ex:"Wychodzę z domu o ósmej piętnaście.", exEn:"I leave the house at eight fifteen." }
          ]
        },
        { id:"a1-family-people",
          name: "Rodzina i ludzie",
          emoji: "👨‍👩‍👧",
          desc: "Family members and the people in your life",
          cards: [
            { id:"a1-family-people-001", pl:"rodzina", en:"family", hint:"Feminine noun.", ex:"Moja rodzina mieszka daleko.", exEn:"My family lives far away." },
            { id:"a1-family-people-002", pl:"mama", en:"mum", hint:"Everyday word; formal: 'matka'.", ex:"Moja mama świetnie gotuje.", exEn:"My mum cooks really well." },
            { id:"a1-family-people-003", pl:"tata", en:"dad", hint:"Everyday word; formal: 'ojciec'. Masculine despite the -a ending.", ex:"Mój tata pracuje w banku.", exEn:"My dad works at a bank." },
            { id:"a1-family-people-004", pl:"brat", en:"brother", hint:"Plural: 'bracia'.", ex:"Mam starszego brata.", exEn:"I have an older brother." },
            { id:"a1-family-people-005", pl:"siostra", en:"sister", hint:"Plural: 'siostry'.", ex:"Moja siostra ma na imię Ewa.", exEn:"My sister's name is Ewa." },
            { id:"a1-family-people-006", pl:"syn", en:"son", relatedIds:["a1-family-people-019"], relationType:"contrast", hint:"Your male child.", ex:"Mam syna.", exEn:"I have a son." },
            { id:"a1-family-people-019", pl:"córka", en:"daughter", relatedIds:["a1-family-people-006"], relationType:"contrast", hint:"Your female child.", ex:"Mam córkę.", exEn:"I have a daughter." },
            { id:"a1-family-people-007", pl:"mąż", en:"husband", relatedIds:["a1-family-people-020"], relationType:"contrast", hint:"'mój mąż' = my husband.", ex:"Mój mąż ma na imię Marek.", exEn:"My husband's name is Marek." },
            { id:"a1-family-people-020", pl:"żona", en:"wife", relatedIds:["a1-family-people-007"], relationType:"contrast", hint:"'moja żona' = my wife.", ex:"To jest moja żona, Anna.", exEn:"This is my wife, Anna." },
            { id:"a1-family-people-008", pl:"dziecko", en:"child", relatedIds:["a1-family-people-021"], relationType:"number-variant", hint:"Neuter noun.", ex:"To jest małe dziecko.", exEn:"This is a small child." },
            { id:"a1-family-people-021", pl:"dzieci", en:"children", relatedIds:["a1-family-people-008"], relationType:"number-variant", hint:"Irregular plural of 'dziecko'.", ex:"Czy masz dzieci?", exEn:"Do you have children?" },
            { id:"a1-family-people-009", pl:"babcia", en:"grandma", hint:"Grandfather: 'dziadek'.", ex:"Moja babcia mieszka w Krakowie.", exEn:"My grandma lives in Krakow." },
            { id:"a1-family-people-010", pl:"dziadek", en:"grandpa", hint:"Grandparents together: 'dziadkowie'.", ex:"Mój dziadek ma osiemdziesiąt lat.", exEn:"My grandpa is eighty years old." },
            { id:"a1-family-people-011", pl:"przyjaciel", en:"close friend (m)", relatedIds:["a1-family-people-022"], relationType:"gender-variant", hint:"A close friend; a casual one is 'znajomy'.", ex:"To jest mój przyjaciel Marek.", exEn:"This is my close friend Marek." },
            { id:"a1-family-people-022", pl:"przyjaciółka", en:"close friend (f)", relatedIds:["a1-family-people-011"], relationType:"gender-variant", hint:"The feminine form of 'przyjaciel'.", ex:"To jest moja przyjaciółka Kasia.", exEn:"This is my close friend Kasia." },
            { id:"a1-family-people-012", pl:"znajomy", en:"acquaintance (m)", relatedIds:["a1-family-people-023"], relationType:"gender-variant", hint:"Less intimate than 'przyjaciel'.", ex:"To jest mój znajomy z pracy.", exEn:"This is an acquaintance of mine from work." },
            { id:"a1-family-people-023", pl:"znajoma", en:"acquaintance (f)", relatedIds:["a1-family-people-012"], relationType:"gender-variant", hint:"The feminine form of 'znajomy'.", ex:"To jest moja znajoma z pracy.", exEn:"This is an acquaintance of mine from work." },
            { id:"a1-family-people-013", pl:"kolega", en:"mate, colleague (m)", relatedIds:["a1-family-people-024"], relationType:"gender-variant", hint:"From work, school, or the neighbourhood.", ex:"Mój kolega z pracy jest z Ukrainy.", exEn:"My mate from work is from Ukraine." },
            { id:"a1-family-people-024", pl:"koleżanka", en:"mate, colleague (f)", relatedIds:["a1-family-people-013"], relationType:"gender-variant", hint:"The feminine form of 'kolega'.", ex:"Moja koleżanka z pracy jest z Ukrainy.", exEn:"My colleague from work is from Ukraine." },
            { id:"a1-family-people-014", pl:"chłopak", en:"boyfriend (also: boy)", relatedIds:["a1-family-people-025"], relationType:"contrast", hint:"Context decides between 'boyfriend' and 'boy'.", ex:"To jest mój chłopak.", exEn:"This is my boyfriend." },
            { id:"a1-family-people-025", pl:"dziewczyna", en:"girlfriend (also: girl)", relatedIds:["a1-family-people-014"], relationType:"contrast", hint:"Context decides between 'girlfriend' and 'girl'.", ex:"Moja dziewczyna uczy się polskiego.", exEn:"My girlfriend is learning Polish." },
            { id:"a1-family-people-015", cardType:"template", pl:"To jest mój... / moja...", en:"This is my... (m / f)", hint:"'mój' before masculine, 'moja' before feminine nouns.", ex:"To jest mój brat, a to moja siostra.", exEn:"This is my brother, and this is my sister.", pattern:"To jest mój/moja {osoba}." },
            { id:"a1-family-people-016", pl:"Czy masz rodzeństwo?", en:"Do you have siblings?", hint:"'rodzeństwo' = siblings, used in singular.", ex:"Czy masz rodzeństwo?", exEn:"Do you have siblings?" },
            { id:"a1-family-people-017", pl:"ludzie", en:"people", hint:"Plural only - the singular is 'człowiek'. 'ludzie' is the subject form, but after 'dużo', 'mało', 'kilku', 'wielu' or a negation it becomes 'ludzi': dużo ludzi, nie ma ludzi.", ex:"W parku jest dużo ludzi.", exEn:"There are a lot of people in the park." },
            { id:"a1-family-people-018", pl:"pan", en:"gentleman, sir (m)", relatedIds:["a1-family-people-026"], relationType:"gender-variant", hint:"Also how you politely address a man.", ex:"Ten pan czeka na autobus.", exEn:"That gentleman is waiting for the bus." },
            { id:"a1-family-people-026", pl:"pani", en:"lady, madam (f)", relatedIds:["a1-family-people-018"], relationType:"gender-variant", hint:"Also how you politely address a woman.", ex:"Ta pani czeka na autobus.", exEn:"That lady is waiting for the bus." }
          ]
        },
        { id:"a1-days-time",
          name: "Dni i czas",
          emoji: "📅",
          desc: "Days of the week and talking about time",
          cards: [
            { id:"a1-days-time-001", pl:"poniedziałek", en:"Monday", hint:"'w poniedziałek' = on Monday.", ex:"W poniedziałek zaczynam pracę.", exEn:"On Monday I start work." },
            { id:"a1-days-time-002", pl:"wtorek", en:"Tuesday", hint:"'we wtorek' = on Tuesday - note 'we', not 'w'.", ex:"We wtorek mam lekcję polskiego.", exEn:"On Tuesday I have a Polish lesson." },
            { id:"a1-days-time-003", pl:"środa", en:"Wednesday", hint:"'w środę' = on Wednesday. Literally 'the middle' of the week.", ex:"W środę idę na siłownię.", exEn:"On Wednesday I go to the gym." },
            { id:"a1-days-time-004", pl:"czwartek", en:"Thursday", hint:"'w czwartek' = on Thursday. From 'cztery' (four) - the fourth day.", ex:"W czwartek mam spotkanie.", exEn:"On Thursday I have a meeting." },
            { id:"a1-days-time-005", pl:"piątek", en:"Friday", hint:"'w piątek' = on Friday. From 'pięć' (five).", ex:"W piątek wieczorem spotykam się ze znajomymi.", exEn:"On Friday evening I meet up with friends." },
            { id:"a1-days-time-006", pl:"sobota", en:"Saturday", hint:"'w sobotę' = on Saturday.", ex:"W sobotę długo śpię.", exEn:"On Saturday I sleep in." },
            { id:"a1-days-time-007", pl:"niedziela", en:"Sunday", hint:"'w niedzielę' = on Sunday. Most shops in Poland are closed on Sundays.", ex:"W niedzielę sklepy są zamknięte.", exEn:"On Sunday the shops are closed." },
            { id:"a1-days-time-008", pl:"dzień", en:"day", hint:"'dzień dobry' = good day.", ex:"Miłego dnia!", exEn:"Have a nice day!" },
            { id:"a1-days-time-023", pl:"tydzień", en:"week", hint:"'w tym tygodniu' = this week.", ex:"Mam wolny dzień w tym tygodniu.", exEn:"I have a day off this week." },
            { id:"a1-days-time-009", pl:"weekend", en:"weekend", hint:"'w weekend' = at the weekend.", ex:"Co robisz w weekend?", exEn:"What are you doing at the weekend?" },
            { id:"a1-days-time-010", pl:"dziś", en:"today", acceptedAnswers:["dzisiaj"], variants:[{form:"dzisiaj",label:"synonym"}], hint:"Both forms are common and interchangeable.", ex:"Dzisiaj jest piątek.", exEn:"Today is Friday." },
            { id:"a1-days-time-011", pl:"jutro", en:"tomorrow", hint:"'pojutrze' = the day after tomorrow.", ex:"Jutro mam egzamin.", exEn:"Tomorrow I have an exam." },
            { id:"a1-days-time-012", pl:"wczoraj", en:"yesterday", hint:"'przedwczoraj' = the day before yesterday. A woman says: byłam.", ex:"Wczoraj byłem w kinie.", exEn:"Yesterday I was at the cinema." },
            { id:"a1-days-time-013", pl:"rano", en:"in the morning", hint:"'jutro rano' = tomorrow morning.", ex:"Rano piję kawę.", exEn:"In the morning I drink coffee." },
            { id:"a1-days-time-014", pl:"po południu", en:"in the afternoon", hint:"Literally 'after noon'.", ex:"Po południu mam czas.", exEn:"In the afternoon I have time." },
            { id:"a1-days-time-015", pl:"wieczorem", en:"in the evening", hint:"'dziś wieczorem' = tonight.", ex:"Wieczorem oglądam serial.", exEn:"In the evening I watch a series." },
            { id:"a1-days-time-016", pl:"w nocy", en:"at night", hint:"'dobranoc' = good night.", ex:"W nocy dobrze śpię.", exEn:"At night I sleep well." },
            { id:"a1-days-time-017", pl:"godzina", en:"hour / o'clock", hint:"'pół godziny' = half an hour.", ex:"Lekcja trwa jedną godzinę.", exEn:"The lesson lasts one hour." },
            { id:"a1-days-time-018", pl:"O której godzinie?", en:"At what time?", hint:"The key question for appointments.", ex:"O której godzinie zaczynamy?", exEn:"At what time do we start?" },
            { id:"a1-days-time-019", pl:"o siódmej", en:"at seven (o'clock)", hint:"Times use ordinal numbers: o siódmej, o ósmej, o dziewiątej.", ex:"Wstaję o siódmej rano.", exEn:"I get up at seven in the morning." },
            { id:"a1-days-time-020", pl:"Która jest godzina?", en:"What time is it?", hint:"The everyday way to ask for the time.", ex:"Przepraszam, która jest godzina?", exEn:"Excuse me, what time is it?" },
            { id:"a1-days-time-021", pl:"teraz", en:"now", relatedIds:["a1-days-time-024"], relationType:"contrast", hint:"Two words you'll use constantly.", ex:"Teraz nie mam czasu.", exEn:"I don't have time now." },
            { id:"a1-days-time-024", pl:"później", en:"later", relatedIds:["a1-days-time-021"], relationType:"contrast", senseGroups:["time-later"], hint:"The opposite of 'teraz'.", ex:"Porozmawiamy później.", exEn:"We'll talk later." },
            { id:"a1-days-time-022", pl:"zawsze", en:"always", relatedIds:["a1-days-time-025"], relationType:"contrast", hint:"Adverb of frequency.", ex:"Zawsze jem śniadanie.", exEn:"I always eat breakfast." },
            { id:"a1-days-time-025", pl:"nigdy", en:"never", relatedIds:["a1-days-time-022"], relationType:"contrast", hint:"'nigdy' pairs with 'nie': nigdy nie mam czasu.", ex:"Nigdy nie jem kolacji.", exEn:"I never eat supper." }
          ]
        },
        { id:"a1-months-seasons",
          name: "Miesiące i pory roku",
          emoji: "🍂",
          desc: "Months, seasons, and saying when something happens",
          cards: [
            { id:"a1-months-seasons-001", pl:"styczeń", en:"January", hint:"'w styczniu' = in January.", ex:"W styczniu jest bardzo zimno.", exEn:"In January it is very cold." },
            { id:"a1-months-seasons-002", pl:"luty", en:"February", hint:"'w lutym' = in February.", ex:"W lutym często pada śnieg.", exEn:"In February it often snows." },
            { id:"a1-months-seasons-003", pl:"marzec", en:"March", hint:"'w marcu' = in March.", ex:"W marcu zaczyna się wiosna.", exEn:"In March spring begins." },
            { id:"a1-months-seasons-004", pl:"kwiecień", en:"April", hint:"'w kwietniu' = in April. From 'kwiat' (flower).", ex:"W kwietniu wszystko kwitnie.", exEn:"In April everything is in bloom." },
            { id:"a1-months-seasons-005", pl:"maj", en:"May", hint:"'w maju' = in May. The long weekend 'majówka' starts the month.", ex:"W maju jest piękna pogoda.", exEn:"In May the weather is beautiful." },
            { id:"a1-months-seasons-006", pl:"czerwiec", en:"June", hint:"'w czerwcu' = in June.", ex:"W czerwcu kończy się szkoła.", exEn:"In June school ends." },
            { id:"a1-months-seasons-007", pl:"lipiec", en:"July", hint:"'w lipcu' = in July. From 'lipa' (linden tree).", ex:"W lipcu mam urlop.", exEn:"In July I have time off." },
            { id:"a1-months-seasons-008", pl:"sierpień", en:"August", hint:"'w sierpniu' = in August.", ex:"W sierpniu jadę nad morze.", exEn:"In August I am going to the seaside." },
            { id:"a1-months-seasons-009", pl:"wrzesień", en:"September", hint:"'we wrześniu' = in September - note 'we'.", ex:"We wrześniu dzieci wracają do szkoły.", exEn:"In September children go back to school." },
            { id:"a1-months-seasons-010", pl:"październik", en:"October", hint:"'w październiku' = in October.", ex:"W październiku zaczynają się zajęcia na uczelni.", exEn:"In October university classes begin." },
            { id:"a1-months-seasons-011", pl:"listopad", en:"November", hint:"'w listopadzie' = in November. From 'liść' (leaf) - leaves falling.", ex:"W listopadzie jest szaro i zimno.", exEn:"In November it is grey and cold." },
            { id:"a1-months-seasons-012", pl:"grudzień", en:"December", hint:"'w grudniu' = in December.", ex:"W grudniu są święta.", exEn:"In December there are the holidays." },
            { id:"a1-months-seasons-013", pl:"miesiąc", en:"month", hint:"'w tym miesiącu' = this month; 'za miesiąc' = in a month.", ex:"Mieszkam tu od trzech miesięcy.", exEn:"I have lived here for three months." },
            { id:"a1-months-seasons-014", pl:"rok", en:"year", hint:"'w tym roku' = this year. Plural: lata.", ex:"Uczę się polskiego od roku.", exEn:"I have been learning Polish for a year." },
            { id:"a1-months-seasons-015", pl:"wiosna", en:"spring", hint:"'wiosną' or 'na wiosnę' = in spring.", ex:"Wiosną dni są coraz dłuższe.", exEn:"In spring the days get longer and longer." },
            { id:"a1-months-seasons-016", pl:"lato", en:"summer", hint:"'latem' = in summer. Also the plural of 'rok' (lata = years).", ex:"Latem jeżdżę nad jezioro.", exEn:"In summer I go to the lake." },
            { id:"a1-months-seasons-017", pl:"jesień", en:"autumn", hint:"'jesienią' = in autumn.", ex:"Jesienią często pada deszcz.", exEn:"In autumn it often rains." },
            { id:"a1-months-seasons-018", pl:"zima", en:"winter", hint:"'zimą' or 'w zimie' = in winter.", ex:"Zimą wcześnie robi się ciemno.", exEn:"In winter it gets dark early." },
            { id:"a1-months-seasons-019", pl:"Kiedy?", en:"When?", hint:"The question word for time.", ex:"Kiedy masz urodziny?", exEn:"When is your birthday?" },
            { id:"a1-months-seasons-020", pl:"urodziny", en:"birthday", hint:"Plural only. 'Wszystkiego najlepszego!' = happy birthday!", ex:"Moje urodziny są w maju.", exEn:"My birthday is in May." }
          ]
        },
        { id:"a1-food-basics",
          name: "Jedzenie - podstawy",
          emoji: "🍞",
          desc: "Basic food words and saying what you like",
          cards: [
            { id:"a1-food-basics-001", pl:"chleb", en:"bread", hint:"Masculine noun. 'kromka chleba' = a slice of bread.", ex:"Kupuję świeży chleb w piekarni.", exEn:"I buy fresh bread at the bakery." },
            { id:"a1-food-basics-002", pl:"bułka", en:"bread roll", hint:"Feminine noun. A breakfast staple in Poland.", ex:"Na śniadanie jem bułkę z masłem.", exEn:"For breakfast I eat a roll with butter." },
            { id:"a1-food-basics-003", pl:"masło", en:"butter", hint:"Neuter noun.", ex:"Poproszę chleb i masło.", exEn:"Bread and butter, please." },
            { id:"a1-food-basics-004", pl:"ser", en:"cheese", hint:"'ser żółty' = hard cheese, 'biały ser' = curd cheese.", ex:"Lubię kanapki z serem.", exEn:"I like cheese sandwiches." },
            { id:"a1-food-basics-005", pl:"jajko", en:"egg", hint:"Neuter noun. Plural: 'jajka'.", ex:"Na śniadanie jem dwa jajka.", exEn:"For breakfast I eat two eggs." },
            { id:"a1-food-basics-006", pl:"szynka", en:"ham", hint:"Feminine noun.", ex:"Poproszę kanapkę z szynką.", exEn:"A ham sandwich, please." },
            { id:"a1-food-basics-007", pl:"mięso", en:"meat", hint:"Neuter noun. 'kurczak' = chicken, 'wieprzowina' = pork.", ex:"Nie jem mięsa.", exEn:"I don't eat meat." },
            { id:"a1-food-basics-008", pl:"kurczak", en:"chicken", hint:"Masculine noun.", ex:"Na obiad jest kurczak z ryżem.", exEn:"For lunch there is chicken with rice." },
            { id:"a1-food-basics-009", pl:"ryba", en:"fish", hint:"Feminine noun.", ex:"W piątek często jem rybę.", exEn:"On Friday I often eat fish." },
            { id:"a1-food-basics-010", pl:"warzywa", en:"vegetables", hint:"Plural noun. Singular: 'warzywo'.", ex:"Kupuję warzywa na targu.", exEn:"I buy vegetables at the market." },
            { id:"a1-food-basics-011", pl:"owoce", en:"fruit", hint:"Plural noun. Singular: 'owoc'.", ex:"Jem dużo owoców latem.", exEn:"I eat a lot of fruit in summer." },
            { id:"a1-food-basics-012", pl:"jabłko", en:"apple", hint:"Neuter noun. Poland is famous for its apples.", ex:"Codziennie jem jedno jabłko.", exEn:"Every day I eat one apple." },
            { id:"a1-food-basics-013", pl:"pomidor", en:"tomato", hint:"Masculine noun. 'zupa pomidorowa' = tomato soup.", ex:"Do kanapki dodaję pomidora.", exEn:"I add a tomato to my sandwich." },
            { id:"a1-food-basics-014", pl:"ziemniaki", en:"potatoes", hint:"Plural of 'ziemniak'. A staple of Polish dinners.", ex:"Na obiad są ziemniaki i kotlet.", exEn:"For lunch there are potatoes and a cutlet." },
            { id:"a1-food-basics-015", pl:"ryż", en:"rice", hint:"A common alternative to potatoes.", ex:"Na obiad jem ryż.", exEn:"I'm having rice for lunch." },
            { id:"a1-food-basics-022", pl:"makaron", en:"pasta", hint:"Another common alternative to potatoes.", ex:"Wolę makaron niż ryż.", exEn:"I prefer pasta to rice." },
            { id:"a1-food-basics-016", pl:"zupa", en:"soup", hint:"Feminine noun. Poles often start lunch with soup.", ex:"Na początek poproszę zupę.", exEn:"To start, I'd like soup." },
            { id:"a1-food-basics-017", pl:"obiad", en:"lunch / dinner (main meal)", hint:"The main meal of the day, usually early afternoon.", ex:"Obiad jem zazwyczaj o czternastej.", exEn:"I usually eat lunch at two p.m." },
            { id:"a1-food-basics-018", pl:"kolacja", en:"supper / evening meal", hint:"A lighter evening meal.", ex:"Na kolację jem kanapki.", exEn:"For supper I eat sandwiches." },
            { id:"a1-food-basics-019", pl:"lubię", en:"I like", relatedIds:["a1-food-basics-023"], relationType:"contrast", hint:"'lubić' + accusative: lubię kawę.", ex:"Lubię pierogi.", exEn:"I like pierogi." },
            { id:"a1-food-basics-023", pl:"nie lubię", en:"I don't like", relatedIds:["a1-food-basics-019"], relationType:"contrast", hint:"The negation: nie lubię + accusative.", ex:"Nie lubię ryb.", exEn:"I don't like fish." },
            { id:"a1-food-basics-020", pl:"smaczny", en:"tasty", hint:"'To jest bardzo smaczne!' = this is very tasty!", ex:"Ta zupa jest bardzo smaczna.", exEn:"This soup is very tasty." },
            { id:"a1-food-basics-021", pl:"głodny", en:"hungry", acceptedAnswers:["głodna"], variants:[{form:"głodny",label:"m"},{form:"głodna",label:"f"}], relationType:"gender-variant", hint:"A woman says 'głodna'.", ex:"Jestem głodny.", exEn:"I'm hungry." },
            { id:"a1-food-basics-024", pl:"chce mi się pić", en:"I'm thirsty", hint:"Polish uses this phrase for thirst.", ex:"Chce mi się pić.", exEn:"I'm thirsty." }
          ]
        },
        { id:"a1-weather-today",
          name: "Pogoda dzisiaj",
          emoji: "🌤️",
          desc: "Everyday weather talk and small-talk openers",
          cards: [
            { id:"a1-weather-today-001", pl:"Jaka jest pogoda?", en:"What's the weather like?", hint:"The basic weather question.", ex:"Jaka dzisiaj jest pogoda?", exEn:"What's the weather like today?" },
            { id:"a1-weather-today-002", pl:"Pada deszcz", en:"It's raining", hint:"Often just 'pada'.", ex:"Weź parasol, pada deszcz.", exEn:"Take an umbrella, it's raining." },
            { id:"a1-weather-today-003", pl:"Pada śnieg", en:"It's snowing", hint:"Same verb 'padać' as for rain.", ex:"Zimą często pada śnieg.", exEn:"In winter it often snows." },
            { id:"a1-weather-today-004", pl:"Świeci słońce", en:"The sun is shining", hint:"'słonecznie' = sunny.", ex:"Dzisiaj świeci słońce.", exEn:"Today the sun is shining." },
            { id:"a1-weather-today-005", pl:"Jest zimno", en:"It's cold", hint:"'Jest mi zimno' = I am cold.", ex:"Dzisiaj jest bardzo zimno.", exEn:"Today it is very cold." },
            { id:"a1-weather-today-006", pl:"Jest ciepło", en:"It's warm", hint:"'Jest gorąco' = it's hot.", ex:"Na dworze jest ciepło.", exEn:"It is warm outside." },
            { id:"a1-weather-today-007", pl:"Jest gorąco", en:"It's hot", hint:"For real summer heat.", ex:"W lipcu jest bardzo gorąco.", exEn:"In July it is very hot." },
            { id:"a1-weather-today-008", pl:"Wieje wiatr", en:"The wind is blowing", hint:"'wietrznie' = windy.", ex:"Nad morzem zawsze wieje wiatr.", exEn:"At the seaside the wind is always blowing." },
            { id:"a1-weather-today-009", pl:"Jest pochmurno", en:"It's cloudy", hint:"'chmura' = a cloud.", ex:"Dzisiaj jest pochmurno i szaro.", exEn:"Today it is cloudy and grey." },
            { id:"a1-weather-today-010", pl:"mgła", en:"fog", hint:"Feminine noun. 'Jest mgła' = it's foggy.", ex:"Rano była gęsta mgła.", exEn:"In the morning there was thick fog." },
            { id:"a1-weather-today-011", pl:"stopnie", en:"degrees", hint:"'pięć stopni' = five degrees; 'minus pięć' below zero.", ex:"Dzisiaj jest dziesięć stopni.", exEn:"Today it is ten degrees." },
            { id:"a1-weather-today-012", pl:"prognoza pogody", en:"weather forecast", hint:"Check it before a trip: 'sprawdzić prognozę'.", ex:"Sprawdzam prognozę pogody na jutro.", exEn:"I'm checking the weather forecast for tomorrow." },
            { id:"a1-weather-today-013", pl:"parasol", en:"umbrella", hint:"Masculine noun. A woman says: zapomniałam.", ex:"Zapomniałem parasola.", exEn:"I forgot my umbrella." },
            { id:"a1-weather-today-014", pl:"Ale ładna pogoda!", en:"What lovely weather!", hint:"'Ale...' = what a...! Great small talk.", ex:"Ale ładna dzisiaj pogoda!", exEn:"What lovely weather today!" },
            { id:"a1-weather-today-015", pl:"Ale brzydka pogoda!", en:"What awful weather!", hint:"The other half of Polish small talk.", ex:"Ale brzydka pogoda, cały dzień pada.", exEn:"What awful weather, it's been raining all day." },
            { id:"a1-weather-today-016", pl:"Zimno dzisiaj, prawda?", en:"Cold today, isn't it?", hint:"'prawda?' turns anything into small talk.", ex:"Zimno dzisiaj, prawda?", exEn:"Cold today, isn't it?" },
            { id:"a1-weather-today-017", pl:"Podobno będzie padać", en:"Apparently it's going to rain", hint:"'podobno' = apparently / they say.", ex:"Podobno jutro będzie padać.", exEn:"Apparently it's going to rain tomorrow." }
          ]
        },
        { id:"a1-first-verbs",
          name: "Pierwsze czasowniki",
          emoji: "🏃",
          desc: "The twenty survival verbs you need first",
          cards: [
            { id:"a1-first-verbs-001", pl:"być", en:"to be", hint:"Irregular: jestem, jesteś, jest, jesteśmy, jesteście, są.", ex:"Jestem z Hiszpanii.", exEn:"I am from Spain." },
            { id:"a1-first-verbs-002", pl:"mieć", en:"to have", pair:"mieć (impf only)", hint:"mam, masz, ma. 'Mam pytanie' = I have a question.", ex:"Mam dwa koty i psa.", exEn:"I have two cats and a dog." },
            { id:"a1-first-verbs-003", pl:"chcieć", en:"to want", pair:"chcieć / zechcieć", hint:"chcę, chcesz, chce. Softer: 'chciałbym' = I would like.", ex:"Chcę mówić po polsku.", exEn:"I want to speak Polish." },
            { id:"a1-first-verbs-004", pl:"móc", en:"can / to be able to", pair:"móc (impf only)", hint:"mogę, możesz, może. 'Czy mogę...?' = may I...?", ex:"Czy mogę tu usiąść?", exEn:"Can I sit here?" },
            { id:"a1-first-verbs-005", pl:"musieć", en:"must / to have to", pair:"musieć (impf only)", hint:"muszę, musisz, musi.", ex:"Muszę już iść.", exEn:"I have to go now." },
            { id:"a1-first-verbs-006", pl:"iść", en:"to go (on foot, now)", pair:"iść / pójść", hint:"idę, idziesz, idzie. For walking somewhere right now.", ex:"Idę do sklepu.", exEn:"I am going to the shop." },
            { id:"a1-first-verbs-007", pl:"jechać", en:"to go (by vehicle, now)", pair:"jechać / pojechać", hint:"jadę, jedziesz, jedzie. For any transport.", ex:"Jadę tramwajem do centrum.", exEn:"I am going to the centre by tram." },
            { id:"a1-first-verbs-008", pl:"robić", en:"to do / to make", pair:"robić / zrobić", hint:"robię, robisz, robi. 'Co robisz?' = what are you doing?", ex:"Co robisz w weekend?", exEn:"What are you doing at the weekend?" },
            { id:"a1-first-verbs-009", pl:"mówić", en:"to speak / to say", pair:"mówić / powiedzieć", hint:"mówię, mówisz, mówi. 'Mówię po polsku' = I speak Polish.", ex:"Mówię trochę po polsku.", exEn:"I speak a little Polish." },
            { id:"a1-first-verbs-010", pl:"rozumieć", en:"to understand", pair:"rozumieć / zrozumieć", hint:"rozumiem, rozumiesz, rozumie.", ex:"Rozumiem, ale proszę mówić wolniej.", exEn:"I understand, but please speak more slowly." },
            { id:"a1-first-verbs-011", pl:"wiedzieć", en:"to know (a fact)", pair:"wiedzieć (impf only)", hint:"wiem, wiesz, wie. For facts; for people and places use 'znać'.", ex:"Nie wiem, gdzie to jest.", exEn:"I don't know where it is." },
            { id:"a1-first-verbs-012", pl:"znać", en:"to know (a person, place)", pair:"znać / poznać", hint:"znam, znasz, zna. 'Znam Warszawę' = I know Warsaw.", ex:"Czy znasz tę restaurację?", exEn:"Do you know this restaurant?" },
            { id:"a1-first-verbs-013", pl:"jeść", en:"to eat", pair:"jeść / zjeść", senseGroups:["verb-to-eat"], hint:"jem, jesz, je. Irregular but essential.", ex:"Co jesz na śniadanie?", exEn:"What do you eat for breakfast?" },
            { id:"a1-first-verbs-014", pl:"pić", en:"to drink", pair:"pić / wypić", hint:"piję, pijesz, pije.", ex:"Piję dużo wody.", exEn:"I drink a lot of water." },
            { id:"a1-first-verbs-015", pl:"kupować", en:"to buy", pair:"kupować / kupić", hint:"kupuję, kupujesz. Perfective 'kupić' for a single purchase.", ex:"Kupuję bilet w aplikacji.", exEn:"I buy a ticket in the app." },
            { id:"a1-first-verbs-016", pl:"mieszkać", en:"to live (reside)", pair:"mieszkać / zamieszkać", hint:"mieszkam, mieszkasz. 'Gdzie mieszkasz?' = where do you live?", ex:"Mieszkam w Warszawie od roku.", exEn:"I have lived in Warsaw for a year." },
            { id:"a1-first-verbs-017", pl:"pracować", en:"to work", pair:"pracować (impf only)", hint:"pracuję, pracujesz.", ex:"Pracuję w biurze w centrum.", exEn:"I work in an office in the centre." },
            { id:"a1-first-verbs-018", pl:"lubić", en:"to like", pair:"lubić / polubić", hint:"lubię, lubisz. Takes accusative: lubię kawę.", ex:"Lubię polskie jedzenie.", exEn:"I like Polish food." },
            { id:"a1-first-verbs-019", pl:"kochać", en:"to love", pair:"kochać / pokochać", hint:"kocham, kochasz. 'Kocham cię' = I love you.", ex:"Kocham to miasto.", exEn:"I love this city." },
            { id:"a1-first-verbs-020", pl:"szukać", en:"to look for", pair:"szukać / poszukać", hint:"szukam, szukasz. Takes genitive: szukam pracy.", ex:"Szukam dobrej kawiarni.", exEn:"I am looking for a good café." },
            { id:"a1-first-verbs-021", pl:"czekać", en:"to wait", pair:"czekać / poczekać", hint:"czekam, czekasz. 'Czekam na...' + accusative.", ex:"Czekam na autobus.", exEn:"I am waiting for the bus." },
            { id:"a1-first-verbs-022", pl:"pomagać", en:"to help", pair:"pomagać / pomóc", hint:"pomagam, pomagasz. Takes dative: pomagam mamie.", ex:"Czy mogę ci pomóc?", exEn:"Can I help you?" }
          ]
        },
        { id:"a1-colours-clothes",
          name: "Kolory i ubrania",
          emoji: "🎨",
          desc: "Colours and the clothes you wear every day",
          cards: [
            { id:"a1-colours-clothes-001", pl:"kolor", en:"colour", hint:"Masculine noun. 'Jaki kolor?' = what colour?", ex:"Jaki kolor lubisz najbardziej?", exEn:"What colour do you like most?" },
            { id:"a1-colours-clothes-002", pl:"czerwony", en:"red", hint:"Adjective. Feminine: czerwona, neuter: czerwone.", ex:"Lubię czerwone jabłka.", exEn:"I like red apples." },
            { id:"a1-colours-clothes-003", pl:"niebieski", en:"blue", hint:"Adjective. 'granatowy' = navy blue.", ex:"Niebo jest dziś niebieskie.", exEn:"The sky is blue today." },
            { id:"a1-colours-clothes-004", pl:"zielony", en:"green", hint:"Adjective. Also means 'inexperienced', like in English.", ex:"Lubię zieloną herbatę.", exEn:"I like green tea." },
            { id:"a1-colours-clothes-005", pl:"żółty", en:"yellow", hint:"Adjective.", ex:"Mam żółty parasol.", exEn:"I have a yellow umbrella." },
            { id:"a1-colours-clothes-006", pl:"czarny", en:"black", hint:"Adjective. 'czarna kawa' = black coffee.", ex:"Poproszę czarną kawę.", exEn:"A black coffee, please." },
            { id:"a1-colours-clothes-007", pl:"biały", en:"white", hint:"Adjective. 'białe wino' = white wine.", ex:"On nosi białą koszulę.", exEn:"He wears a white shirt." },
            { id:"a1-colours-clothes-008", pl:"szary", en:"grey", hint:"Adjective. 'szary' also means dull or drab.", ex:"Listopad jest zawsze szary.", exEn:"November is always grey." },
            { id:"a1-colours-clothes-009", pl:"brązowy", en:"brown", hint:"Adjective. From 'brąz' (bronze).", ex:"Mam brązowe oczy.", exEn:"I have brown eyes." },
            { id:"a1-colours-clothes-010", pl:"różowy", en:"pink", hint:"Adjective. From 'róża' (rose).", ex:"Ona ma różową sukienkę.", exEn:"She has a pink dress." },
            { id:"a1-colours-clothes-011", pl:"pomarańczowy", en:"orange", typeItCue:"the colour", hint:"Adjective. Same root as 'pomarańcza' (the fruit).", ex:"Lubię sok pomarańczowy.", exEn:"I like orange juice." },
            { id:"a1-colours-clothes-012", pl:"ubranie", en:"clothing / clothes", hint:"Neuter noun. Often used in plural: 'ubrania'.", ex:"Muszę kupić nowe ubrania.", exEn:"I need to buy new clothes." },
            { id:"a1-colours-clothes-013", pl:"koszulka", en:"T-shirt", hint:"Feminine noun. 'koszula' is a formal shirt.", ex:"Noszę koszulkę i dżinsy.", exEn:"I'm wearing a T-shirt and jeans." },
            { id:"a1-colours-clothes-014", pl:"spodnie", en:"trousers", hint:"Plural only, like in English.", ex:"Te spodnie są za długie.", exEn:"These trousers are too long." },
            { id:"a1-colours-clothes-015", pl:"sukienka", en:"dress", hint:"Feminine noun.", ex:"Kupiłam nową sukienkę na wesele.", exEn:"I bought a new dress for the wedding. A man: kupiłem." },
            { id:"a1-colours-clothes-016", pl:"buty", en:"shoes", hint:"Plural. Singular 'but' is rare.", ex:"Gdzie są moje buty?", exEn:"Where are my shoes?" },
            { id:"a1-colours-clothes-017", pl:"kurtka", en:"jacket", hint:"Feminine noun. 'płaszcz' = a longer coat.", ex:"Weź kurtkę, jest zimno.", exEn:"Take a jacket, it's cold." },
            { id:"a1-colours-clothes-018", pl:"czapka", en:"hat / beanie", hint:"Feminine noun. Essential for a Polish winter.", ex:"Zimą zawsze noszę czapkę.", exEn:"In winter I always wear a hat." },
            { id:"a1-colours-clothes-019", pl:"nosić", en:"to wear", pair:"nosić (impf, habitual)", hint:"noszę, nosisz. For what you wear regularly.", ex:"Nie noszę sukienek.", exEn:"I don't wear dresses." },
            { id:"a1-colours-clothes-020", pl:"Jaki masz rozmiar?", en:"What size are you?", hint:"Informal. A shop assistant will ask: 'Jaki rozmiar pan/pani nosi?'", ex:"Jaki masz rozmiar?", exEn:"What size are you?" },
            { id:"a1-colours-clothes-021", pl:"pasować", en:"to fit / to suit", pair:"pasować (impf only)", hint:"'To mi pasuje' = that suits me / works for me.", ex:"Ta kurtka do ciebie pasuje.", exEn:"This jacket suits you." }
          ]
        },
        { id:"a1-free-time",
          name: "Czas wolny",
          emoji: "🎸",
          desc: "Hobbies and what you like doing in your free time",
          cards: [
            { id:"a1-free-time-001", pl:"czas wolny", en:"free time", hint:"Masculine phrase. 'W wolnym czasie' = in my free time.", ex:"W wolnym czasie czytam książki.", exEn:"In my free time I read books." },
            { id:"a1-free-time-002", pl:"hobby", en:"hobby", hint:"Neuter, does not change form. Plural also 'hobby'.", ex:"Moje hobby to gotowanie.", exEn:"My hobby is cooking." },
            { id:"a1-free-time-003", pl:"czytać", en:"to read", pair:"czytać / przeczytać", hint:"czytam, czytasz. 'lubię czytać' = I like reading.", ex:"Lubię czytać przed snem.", exEn:"I like reading before bed." },
            { id:"a1-free-time-004", pl:"oglądać", en:"to watch", pair:"oglądać / obejrzeć", hint:"oglądam, oglądasz. For TV, films, matches.", ex:"Wieczorem oglądam seriale.", exEn:"In the evening I watch series." },
            { id:"a1-free-time-005", pl:"słuchać muzyki", en:"to listen to music", pair:"słuchać / posłuchać", hint:"'słuchać' takes the genitive: słucham muzyki.", ex:"Słucham muzyki w drodze do pracy.", exEn:"I listen to music on the way to work." },
            { id:"a1-free-time-006", pl:"grać", en:"to play", pair:"grać / zagrać", hint:"gram, grasz. 'grać w' + sport/game, 'grać na' + instrument.", ex:"Gram w piłkę w każdą sobotę.", exEn:"I play football every Saturday." },
            { id:"a1-free-time-007", pl:"grać na gitarze", en:"to play the guitar", pair:"grać / zagrać", hint:"'grać na' + instrument in the locative: na gitarze, na pianinie.", ex:"Uczę się grać na gitarze.", exEn:"I'm learning to play the guitar." },
            { id:"a1-free-time-008", pl:"śpiewać", en:"to sing", pair:"śpiewać / zaśpiewać", hint:"śpiewam, śpiewasz.", ex:"Lubię śpiewać pod prysznicem.", exEn:"I like singing in the shower." },
            { id:"a1-free-time-009", pl:"tańczyć", en:"to dance", pair:"tańczyć / zatańczyć", hint:"tańczę, tańczysz.", ex:"Czy lubisz tańczyć?", exEn:"Do you like dancing?" },
            { id:"a1-free-time-010", pl:"gotować", en:"to cook", pair:"gotować / ugotować", hint:"gotuję, gotujesz.", ex:"W weekend lubię gotować dla znajomych.", exEn:"At the weekend I like cooking for friends." },
            { id:"a1-free-time-011", pl:"malować", en:"to paint / to draw", pair:"malować / namalować", hint:"maluję, malujesz. 'rysować' = to draw with a pencil.", ex:"Moja córka lubi malować.", exEn:"My daughter likes painting." },
            { id:"a1-free-time-012", pl:"pływać", en:"to swim", pair:"pływać (impf, habitual)", hint:"pływam, pływasz.", ex:"Latem często pływam w jeziorze.", exEn:"In summer I often swim in the lake." },
            { id:"a1-free-time-013", pl:"biegać", en:"to run / to jog", pair:"biegać (impf, habitual)", hint:"biegam, biegasz. As regular exercise.", ex:"Biegam w parku trzy razy w tygodniu.", exEn:"I run in the park three times a week." },
            { id:"a1-free-time-014", pl:"jeździć na rowerze", en:"to ride a bike", pair:"jeździć (impf, habitual)", hint:"'jeździć na' + locative.", ex:"W weekend jeździmy na rowerach.", exEn:"At the weekend we ride bikes." },
            { id:"a1-free-time-015", pl:"grać w gry", en:"to play games", pair:"grać / zagrać", hint:"Video or board games. 'gra planszowa' = board game.", ex:"Wieczorami gram w gry na komputerze.", exEn:"In the evenings I play games on the computer." },
            { id:"a1-free-time-016", pl:"spotykać się ze znajomymi", en:"to meet up with friends", pair:"spotykać się / spotkać się", hint:"'spotykać się z' + instrumental.", ex:"W piątki spotykam się ze znajomymi.", exEn:"On Fridays I meet up with friends." },
            { id:"a1-free-time-017", pl:"podróżować", en:"to travel", pair:"podróżować (impf only)", hint:"podróżuję, podróżujesz.", ex:"Uwielbiam podróżować po Europie.", exEn:"I love travelling around Europe." },
            { id:"a1-free-time-018", pl:"robić zdjęcia", en:"to take photos", pair:"robić / zrobić", hint:"Literally 'to make photos'.", ex:"Lubię robić zdjęcia w podróży.", exEn:"I like taking photos when travelling." },
            { id:"a1-free-time-019", pl:"sport", en:"sport", hint:"Masculine noun. 'uprawiać sport' = to do sport.", ex:"Sport to moja pasja.", exEn:"Sport is my passion." },
            { id:"a1-free-time-020", pl:"film", en:"film / movie", hint:"Masculine noun. 'iść na film' = to go to a film.", ex:"Idziemy dziś na film?", exEn:"Shall we go to a film today?" },
            { id:"a1-free-time-021", pl:"książka", en:"book", hint:"Feminine noun.", ex:"Czytam teraz ciekawą książkę.", exEn:"I'm reading an interesting book right now." },
            { id:"a1-free-time-022", pl:"Co lubisz robić?", en:"What do you like doing?", hint:"The key question for small talk about hobbies.", ex:"Co lubisz robić w wolnym czasie?", exEn:"What do you like doing in your free time?" }
          ]
        },
        { id:"a1-fruit-vegetables",
          name: "Owoce i warzywa",
          emoji: "🍎",
          desc: "Fruit and vegetables, and buying them at the market",
          cards: [
            { id:"a1-fruit-vegetables-001", pl:"owoce", en:"fruit", hint:"Plural noun. Singular 'owoc' is rare in speech.", ex:"Jem owoce codziennie.", exEn:"I eat fruit every day." },
            { id:"a1-fruit-vegetables-002", pl:"warzywa", en:"vegetables", hint:"Plural noun. Singular: 'warzywo'.", ex:"Warzywa są zdrowe.", exEn:"Vegetables are healthy." },
            { id:"a1-fruit-vegetables-003", pl:"jabłko", en:"apple", hint:"Neuter noun. Poland grows a lot of apples.", ex:"Poproszę kilo jabłek.", exEn:"A kilo of apples, please." },
            { id:"a1-fruit-vegetables-004", pl:"banan", en:"banana", hint:"Masculine noun.", ex:"Na śniadanie jem banana.", exEn:"For breakfast I eat a banana." },
            { id:"a1-fruit-vegetables-005", pl:"gruszka", en:"pear", hint:"Feminine noun.", ex:"Te gruszki są bardzo słodkie.", exEn:"These pears are very sweet." },
            { id:"a1-fruit-vegetables-006", pl:"truskawki", en:"strawberries", hint:"Plural. Singular: 'truskawka'. Best in June.", ex:"Latem kupuję truskawki na targu.", exEn:"In summer I buy strawberries at the market." },
            { id:"a1-fruit-vegetables-007", pl:"winogrona", en:"grapes", hint:"Plural noun.", ex:"Kupiłem zielone winogrona.", exEn:"I bought green grapes. A woman: kupiłam." },
            { id:"a1-fruit-vegetables-008", pl:"pomarańcza", en:"orange", typeItCue:"the fruit", hint:"Feminine noun. The fruit; the colour is 'pomarańczowy'.", ex:"Wyciskam sok z pomarańczy.", exEn:"I'm squeezing juice from an orange." },
            { id:"a1-fruit-vegetables-009", pl:"cytryna", en:"lemon", hint:"Feminine noun. 'herbata z cytryną' = tea with lemon.", ex:"Poproszę herbatę z cytryną.", exEn:"Tea with lemon, please." },
            { id:"a1-fruit-vegetables-010", pl:"śliwka", en:"plum", hint:"Feminine noun. 'śliwka' also means a black eye.", ex:"Jesienią jem dużo śliwek.", exEn:"In autumn I eat a lot of plums." },
            { id:"a1-fruit-vegetables-011", pl:"arbuz", en:"watermelon", hint:"Masculine noun. A summer favourite.", ex:"W upał nie ma nic lepszego niż arbuz.", exEn:"In the heat there's nothing better than watermelon." },
            { id:"a1-fruit-vegetables-012", pl:"maliny", en:"raspberries", hint:"Plural. Singular: 'malina'.", ex:"Maliny są moimi ulubionymi owocami.", exEn:"Raspberries are my favourite fruit." },
            { id:"a1-fruit-vegetables-013", pl:"pomidor", en:"tomato", hint:"Masculine noun. 'zupa pomidorowa' = tomato soup.", ex:"Do sałatki dodaję pomidory.", exEn:"I add tomatoes to the salad." },
            { id:"a1-fruit-vegetables-014", pl:"ogórek", en:"cucumber", hint:"Masculine noun. 'ogórek kiszony' = a Polish sour pickle.", ex:"Uwielbiam ogórki kiszone.", exEn:"I love sour pickled cucumbers." },
            { id:"a1-fruit-vegetables-015", pl:"marchewka", en:"carrot", hint:"Feminine noun. Formal form: 'marchew'.", ex:"Zupa z marchewki jest pyszna.", exEn:"Carrot soup is delicious." },
            { id:"a1-fruit-vegetables-016", pl:"ziemniaki", en:"potatoes", hint:"Plural of 'ziemniak'. A dinner staple.", ex:"Na obiad są ziemniaki.", exEn:"For lunch there are potatoes." },
            { id:"a1-fruit-vegetables-017", pl:"cebula", en:"onion", hint:"Feminine noun.", ex:"Ta zupa potrzebuje cebuli.", exEn:"This soup needs onion." },
            { id:"a1-fruit-vegetables-018", pl:"czosnek", en:"garlic", hint:"Masculine noun. A remedy Poles swear by for colds.", ex:"Dodaję czosnek do prawie wszystkiego.", exEn:"I add garlic to almost everything." },
            { id:"a1-fruit-vegetables-019", pl:"papryka", en:"pepper (bell) / paprika", hint:"Feminine noun. Both the vegetable and the spice.", ex:"Czerwona papryka jest słodka.", exEn:"Red pepper is sweet." },
            { id:"a1-fruit-vegetables-020", pl:"sałata", en:"lettuce", hint:"Feminine noun. 'sałatka' (with -ka) is a made salad.", ex:"Kupię sałatę na kanapki.", exEn:"I'll buy lettuce for sandwiches." },
            { id:"a1-fruit-vegetables-021", pl:"kilo", en:"a kilo", hint:"'kilo' doesn't change form. 'kilogram' also works.", ex:"Poproszę kilo jabłek.", exEn:"A kilo of apples, please." },
            { id:"a1-fruit-vegetables-024", pl:"pół kilo", en:"half a kilo", hint:"'pół' = half.", ex:"Poproszę pół kilo pomidorów.", exEn:"Half a kilo of tomatoes, please." },
            { id:"a1-fruit-vegetables-022", pl:"świeży", en:"fresh", hint:"'zepsuty' = gone off.", ex:"Te warzywa są świeże.", exEn:"These vegetables are fresh." },
            { id:"a1-fruit-vegetables-025", pl:"dojrzały", en:"ripe", hint:"'niedojrzały' = unripe.", ex:"Czy te banany są dojrzałe?", exEn:"Are these bananas ripe?" },
            { id:"a1-fruit-vegetables-023", cardType:"template", pl:"Poproszę kilo...", en:"A kilo of..., please", hint:"The core market phrase. The fruit follows in the genitive.", ex:"Poproszę kilo jabłek i dwie cytryny.", exEn:"A kilo of apples and two lemons, please.", pattern:"Poproszę kilo {coś (dopełniacz)}." }
          ]
        }
      ]
    }
  );
})();
