"""Phase 4F-I1 normalisation, shared by every historical Priority 7 suite.

Phase 4F-I1 is the **atomic activation** phase.  It is the first phase that
turns the dormant Priority 7 reference surface on, and it is deliberately one
indivisible transition across four kinds of file:

1. ``content/verb-patterns.json`` -- the official runtime document appears, with
   the exact bytes the approval-gated tooling produces from the approved corpus
   (``freeze_editorial`` then ``verified_runtime_from_frozen``);
2. ``index.html`` -- ``APP_VERSION`` advances ``8.10`` -> ``8.11`` and the one
   production loader activation is added;
3. ``sw.js`` -- the shell cache advances ``popolsku-v65`` -> ``popolsku-v66``,
   the helper and the runtime join the required precache inventory, and the
   runtime gets its own network-first classification while being excluded from
   the cache-first static inventory;
4. the 31 generator-owned pages and ``sitemap.xml`` -- regenerated by
   ``build_pages.py`` because the footer stamps ``APP_VERSION``.

Every Priority 7 phase before this one states, against its own pinned baseline,
some version of *the runtime file does not exist*, *the loader is dormant*,
*``APP_VERSION`` is 8.10*, *the shell cache is v65* or *no shipping file moved*.
Those were true statements about the tiers that had run.  Phase 4F-I1
legitimately supersedes all of them, so they are restated over the bundle with
the I1 layer removed -- exactly as Phase 4F-H3's wording claims are restated
over the shell with the H3 layer removed::

    bundle = I1.bundle(index_text=..., worker_text=..., runtime_bytes=...)
    self.assertEqual(git_blob("index.html"), bundle.without_activation("index.html"))

**All-or-nothing, by construction.**  There is no way to obtain a normalised
byte from this module without first building a :class:`Phase4FI1Bundle` over
*all three* core components together.  :func:`bundle` raises unless the layer is
uniformly ``absent`` or uniformly ``complete`` across:

* both pinned ``index.html`` edits;
* all six pinned ``sw.js`` edits;
* the runtime file -- present with **exactly** the pinned SHA-256, byte length
  and ``patternDataRevision``, or absent altogether.

So a tree that materialised the runtime but forgot the loader, that bumped the
version but not the cache, that shipped different runtime bytes, that shipped
the right bytes at the wrong revision, or that applied five of the six worker
edits is ``partial`` -- and ``partial`` is refused, never half-reverted.

**What it can hide, and therefore what it cannot.**  The two ``index.html``
edits and the six ``sw.js`` edits are pinned literal strings; every other byte
of both files is passed through untouched.  A caller comparing the normalised
text with its baseline blob therefore still sees, in full:

* a second loader activation, a different runtime URL, a preview/fixture URL,
  or an activation that survives reverting the pinned block;
* any other edit to ``index.html`` or ``sw.js``, anywhere, including an
  ``APP_VERSION`` or cache generation past the pinned I1 values;
* a missing, extra, mutated or wrongly-revisioned runtime file -- those are
  checked by digest, not by substitution, and a mismatch makes the whole bundle
  ``partial``;
* any missing required service-worker asset or changed classification, because
  those live in the pinned worker edits and a partial application is refused;
* H3 wording, recognition-only semantics, governance, corpus, audio and
  activity eligibility, none of which appear in any pinned string and none of
  which this module reads;
* an arbitrary generated-page change: :func:`is_exactly_the_i1_generated_page`
  admits only the single ``&middot; v8.10 &middot;`` -> ``&middot; v8.11
  &middot;`` footer stamp, and :func:`is_exactly_the_i1_sitemap` admits only
  ``<lastmod>`` movement with an identical URL set, order and structure.

This module is phase-owned and additive.  It imports nothing from the suites
that use it, opens no file, runs no subprocess and writes nothing.
"""

from __future__ import annotations

import dataclasses
import hashlib
import re

# --------------------------------------------------------------------------
# The pinned I1 release identity.  Nothing here is derived from the tree being
# normalised; each value is the transition this phase is allowed to hide.
# --------------------------------------------------------------------------

#: The one repository path the official runtime document may occupy.
PHASE_4FI1_RUNTIME_PATH = "content/verb-patterns.json"

#: The URL the shipping application is allowed to name, and only once.
PHASE_4FI1_RUNTIME_URL = "./content/verb-patterns.json"

#: SHA-256 of the runtime bytes produced by the approval-gated path from the
#: 45-example approved corpus.  A different corpus, a different revision or a
#: hand-edited file cannot reach this digest.
PHASE_4FI1_RUNTIME_SHA256 = (
    "d7911b2a4597147f3f0336c9b0cd154d1bec390d246fc4f33620b7bcf46460ed")
PHASE_4FI1_RUNTIME_BYTE_LENGTH = 93600
PHASE_4FI1_PATTERN_DATA_REVISION = 1
PHASE_4FI1_FORMAT_VERSION = 1

PHASE_4FI1_APP_VERSION_BEFORE = "8.10"
PHASE_4FI1_APP_VERSION_AFTER = "8.11"
PHASE_4FI1_SHELL_CACHE_BEFORE = "popolsku-v65"
PHASE_4FI1_SHELL_CACHE_AFTER = "popolsku-v66"

#: The two shipping sources I1 edits by hand.
PHASE_4FI1_SHIPPING_PATHS = ("index.html", "sw.js")

#: The generator-owned pages I1 regenerates, plus the sitemap.  They are
#: regenerated, never hand-edited: the footer stamps ``APP_VERSION``.
PHASE_4FI1_GENERATED_PAGES = (
    "grammar/biernik-accusative/index.html",
    "grammar/celownik-dative/index.html",
    "grammar/dopelniacz-genitive/index.html",
    "grammar/jesli-i-gdyby-conditions/index.html",
    "grammar/kazdy-i-wszyscy-every-vs-all/index.html",
    "grammar/korespondencja-formal-writing/index.html",
    "grammar/ktory-relative-clauses/index.html",
    "grammar/liczebniki-numbers-meet-cases/index.html",
    "grammar/mianownik-nominative/index.html",
    "grammar/miejscownik-locative/index.html",
    "grammar/narodowosci-nationalities/index.html",
    "grammar/narzednik-instrumental/index.html",
    "grammar/pan-i-pani-formal-address/index.html",
    "grammar/panowie-panie-panstwo-plural-formal-address/index.html",
    "grammar/przeczenie-negation/index.html",
    "grammar/przymiotniki-adjectives-traits/index.html",
    "grammar/stopniowanie-comparison/index.html",
    "grammar/tryb-przypuszczajacy-conditional/index.html",
    "grammar/wolacz-vocative/index.html",
    "grammar/zaimki-pronouns-determiners/index.html",
    "grammar/zawody-professions/index.html",
    "grammar/zdrobnienia-diminutives/index.html",
    "grammar/zeby-so-that-want-to/index.html",
    "guide/index.html",
    "guide/listening/index.html",
    "vocabulary/everyday-polish-slang/index.html",
    "vocabulary/polish-corporate-slang/index.html",
    "vocabulary/polish-exclamations/index.html",
    "vocabulary/polish-idioms/index.html",
    "vocabulary/polish-party-slang/index.html",
    "vocabulary/polish-proverbs/index.html",
)
PHASE_4FI1_SITEMAP_PATH = "sitemap.xml"

#: Every repository path Phase 4F-I1 is entitled to move, outside ``tests/``
#: and ``reports/``.  Anything else in a footprint is unexpected.
PHASE_4FI1_FOOTPRINT = tuple(sorted(
    PHASE_4FI1_SHIPPING_PATHS + PHASE_4FI1_GENERATED_PAGES
    + (PHASE_4FI1_SITEMAP_PATH, PHASE_4FI1_RUNTIME_PATH)))

#: The one production activation block, verbatim.  It is pinned whole rather
#: than by fragment so that a *second* activation, a different URL or an edited
#: call cannot be reverted away: reverting removes exactly this text once, and
#: whatever else was added stays visible to the caller's comparison.
_ACTIVATION = '''
/* ---------------- Priority 7 reference data: the one production load ----------------
   The reference surface ships dormant and stays honest with no data: the tile
   says "Not ready yet" and the surface renders its own neutral unavailable
   state. This is the single call that offers it data, and the only place in the
   application that names the runtime URL.

   The transport itself lives in pp-verb-patterns.js and is dependency-injected,
   so the URL, the retry policy (there is none) and the re-render policy are
   owned here rather than by the helper. `fetch` is wrapped rather than passed
   by reference because a bare `fetch` loses its binding.

   FAILURE IS NON-BLOCKING AND SILENT. Offline, a missing file, an HTTP error, a
   truncated body, a document that fails the closed public-shape check - every
   one of them settles to `false`, leaves the neutral unavailable state exactly
   where it was, and changes nothing else about startup. There is no fixture,
   preview, editorial or query-string alternative to this URL: an unusable
   runtime means the reference surface has nothing to show, never that some
   other document gets shown instead.

   On success, only what is already on screen is refreshed: the topic tile's
   count and, if the learner is already standing on the unavailable state, the
   index. Nothing is persisted, nothing navigates and no focus moves. */
const PRIORITY7_RUNTIME_URL = "./content/verb-patterns.json";
function pSettleRuntime(accepted){
  if(accepted !== true) return;                    /* unavailable is a settled answer */
  if($("home").classList.contains("active")) renderTopics();
  if($("patterns").classList.contains("active") && P.view === "index") pRenderIndex(false);
}
void PP_VERB_PATTERNS.loadRuntimeDocument(
  (url, options)=> fetch(url, options), PRIORITY7_RUNTIME_URL
).then(pSettleRuntime, ()=>{});
'''
_GRAMMAR_MARKER = (
    "\n/* ---------------- grammar (teach -> drill) ---------------- */\n")

#: The two pinned ``(pre-I1, post-I1)`` pairs for ``index.html``, in file order.
I1_INDEX_EDITS = (
    # 1. the human-facing release version, which the generated pages stamp
    ('const APP_VERSION = "8.10";', 'const APP_VERSION = "8.11";'),
    # 2. the one production loader activation, at the end of the Priority 7
    #    block.  Pinned together with the marker that follows it so its
    #    position is part of the pin, not only its text.
    (_GRAMMAR_MARKER, _ACTIVATION + _GRAMMAR_MARKER),
)

#: The six pinned ``(pre-I1, post-I1)`` pairs for ``sw.js``, in file order.
I1_WORKER_EDITS = (
    # 1. the shell cache generation
    ('const CACHE = "popolsku-v65";', 'const CACHE = "popolsku-v66";'),
    # 2. the helper and the runtime join the required precache inventory
    ('''  "./data-podcasts.js",
  "./audio-manifest.json"
];''',
     '''  "./data-podcasts.js",
  "./audio-manifest.json",
  /* Priority 7 reference data. The helper is an ordinary shell script and is
     cached like one; the runtime document it consumes is REQUIRED rather than
     optional, because the reference surface is part of the offline app and a
     surface that only works online is not one this shell ships. Its runtime
     strategy is network-first (see PATTERN_RUNTIME_PATH below) - precaching is
     what makes it available offline, not what decides how it revalidates. */
  "./pp-verb-patterns.js",
  "./content/verb-patterns.json"
];'''),
    # 3. the runtime's own canonical path constant
    ('const AUDIO_MANIFEST_PATH = SCOPE_PATH + "audio-manifest.json";\n',
     '''const AUDIO_MANIFEST_PATH = SCOPE_PATH + "audio-manifest.json";
/* The Priority 7 runtime document. Content, not shell: republishing it must
   reach a returning learner on the next online visit without waiting for a
   CACHE bump, exactly like the lesson data files and the audio manifest. It is
   therefore precached for offline use but revalidated network-first, and is
   deliberately excluded from the cache-first static inventory below. */
const PATTERN_RUNTIME_PATH = SCOPE_PATH + "content/verb-patterns.json";\n'''),
    # 4. and its exclusion from the cache-first static inventory
    ('''  .filter(path => path !== null && path !== SCOPE_PATH &&
                  !DATA_FILE.test(path) && path !== AUDIO_MANIFEST_PATH);''',
     '''  .filter(path => path !== null && path !== SCOPE_PATH &&
                  !DATA_FILE.test(path) && path !== AUDIO_MANIFEST_PATH &&
                  path !== PATTERN_RUNTIME_PATH);'''),
    # 5. its own request category
    ('  if (path === AUDIO_MANIFEST_PATH) return "audio-manifest";\n',
     '  if (path === AUDIO_MANIFEST_PATH) return "audio-manifest";\n'
     '  if (path === PATTERN_RUNTIME_PATH) return "pattern-runtime";\n'),
    # 6. and its network-first strategy
    ('  if (category === "audio-manifest") { networkFirst(e, key, false); return; }\n',
     '''  if (category === "audio-manifest") { networkFirst(e, key, false); return; }

  /* The Priority 7 runtime document: regenerate the reference corpus, re-upload
     it, users pick up the new revision on their next online visit. Same
     contract as the lesson data - a cached copy answers offline, and it is
     never served cache-first while the network can say otherwise. */
  if (category === "pattern-runtime") { networkFirst(e, key, false); return; }
'''),
)

I1_EDITS = {
    "index.html": I1_INDEX_EDITS,
    "sw.js": I1_WORKER_EDITS,
}

#: The one generated-page edit: the footer version stamp, once per page.
I1_GENERATED_PAGE_EDIT = ("&middot; v8.10 &middot;", "&middot; v8.11 &middot;")

_LASTMOD = re.compile(r"<lastmod>[^<]*</lastmod>")


# --------------------------------------------------------------------------
# Layer state
# --------------------------------------------------------------------------

def _edit_state(text: str, pre: str, post: str) -> str:
    """Report one pinned edit as ``absent``, ``complete`` or ``unrecognised``."""
    before, after = text.count(pre), text.count(post)
    # ``post`` may contain ``pre`` (an insertion keeps the anchor), so an
    # applied edit is recognised by the post-count and by the pre-count that
    # the post-text itself accounts for.
    accounted = post.count(pre)
    if after == 0 and before == 1:
        return "absent"
    if after == 1 and before == accounted:
        return "complete"
    return "unrecognised"


def phase_4fi1_file_state(path: str, text: str) -> str:
    """Report one shipping file's I1 layer as ``absent``/``complete``/``partial``."""
    edits = I1_EDITS.get(path)
    if edits is None:
        raise AssertionError(f"{path!r} is not a Phase 4F-I1 shipping path")
    states = {_edit_state(text, pre, post) for pre, post in edits}
    if states == {"absent"}:
        return "absent"
    if states == {"complete"}:
        return "complete"
    return "partial"


def phase_4fi1_runtime_state(runtime_bytes: bytes | None) -> str:
    """Report the runtime file as ``absent``, ``complete`` or ``partial``.

    ``complete`` means the exact pinned release bytes.  Anything else that
    exists at that path -- other bytes, a mutated digest, an extra private key,
    a different revision -- is ``partial`` and is never normalised away.
    """
    if runtime_bytes is None:
        return "absent"
    if not isinstance(runtime_bytes, (bytes, bytearray)):
        return "partial"
    if len(runtime_bytes) != PHASE_4FI1_RUNTIME_BYTE_LENGTH:
        return "partial"
    if hashlib.sha256(bytes(runtime_bytes)).hexdigest() != PHASE_4FI1_RUNTIME_SHA256:
        return "partial"
    return "complete"


def phase_4fi1_layer_state(index_text: str, worker_text: str,
                           runtime_bytes: bytes | None) -> str:
    """The whole-bundle verdict.  ``complete`` needs every component to agree."""
    states = {
        phase_4fi1_file_state("index.html", index_text),
        phase_4fi1_file_state("sw.js", worker_text),
        phase_4fi1_runtime_state(runtime_bytes),
    }
    if states == {"absent"}:
        return "absent"
    if states == {"complete"}:
        return "complete"
    return "partial"


# --------------------------------------------------------------------------
# The bundle
# --------------------------------------------------------------------------

@dataclasses.dataclass(frozen=True)
class Phase4FI1Bundle:
    """One validated view of the I1 transition, or of the tree before it.

    Constructed only through :func:`bundle`, which refuses a partial layer.  A
    caller therefore cannot normalise ``index.html`` without having proved, in
    the same breath, that the worker and the runtime moved with it.
    """

    index_text: str
    worker_text: str
    runtime_bytes: bytes | None
    state: str

    def without_activation(self, path: str) -> str:
        """Return ``path`` as it stood before Phase 4F-I1.

        Only the pinned strings are reversed, each exactly once.  Every other
        byte is passed through, so whatever the caller compares the result
        against still sees every other difference.
        """
        text = {"index.html": self.index_text, "sw.js": self.worker_text}.get(path)
        if text is None:
            raise AssertionError(f"{path!r} is not a Phase 4F-I1 shipping path")
        if self.state == "absent":
            return text
        for pre, post in I1_EDITS[path]:
            text = text.replace(post, pre, 1)
        if phase_4fi1_file_state(path, text) != "absent":   # pragma: no cover
            raise AssertionError(
                f"reverting the Phase 4F-I1 layer did not reach the pre-I1 {path}")
        return text

    def with_activation(self, path: str, baseline_text: str) -> str:
        """The exact inverse: apply the pinned layer to a pre-I1 file."""
        if phase_4fi1_file_state(path, baseline_text) != "absent":
            raise AssertionError(
                f"{path!r} does not carry the pre-I1 shape this layer applies to")
        text = baseline_text
        for pre, post in I1_EDITS[path]:
            text = text.replace(pre, post, 1)
        return text

    def is_exactly_the_i1_activation(self, path: str, baseline_text: str,
                                     live_text: str) -> bool:
        """True only when ``path``'s sole difference from baseline is the layer."""
        if path not in I1_EDITS:
            return False
        try:
            probe = dataclasses.replace(
                self,
                index_text=live_text if path == "index.html" else self.index_text,
                worker_text=live_text if path == "sw.js" else self.worker_text,
            )
            return probe.without_activation(path) == baseline_text
        except AssertionError:
            return False


def bundle(*, index_text: str, worker_text: str,
           runtime_bytes: bytes | None) -> Phase4FI1Bundle:
    """Validate the three core components together, or refuse.

    This is the all-or-nothing gate.  A tree in which the layer is present on
    some components and not others -- or in which the runtime exists with
    bytes other than the pinned release -- raises here, so no partly-activated
    tree can ever be normalised into looking like a clean pre-I1 baseline.
    """
    state = phase_4fi1_layer_state(index_text, worker_text, runtime_bytes)
    if state == "partial":
        raise AssertionError(
            "the Phase 4F-I1 activation layer is present on some but not all "
            "of the runtime document, index.html and sw.js, or the runtime "
            "bytes are not the pinned I1 release; the bundle is incomplete and "
            "must not be normalised away")
    return Phase4FI1Bundle(
        index_text=index_text, worker_text=worker_text,
        runtime_bytes=bytes(runtime_bytes) if runtime_bytes is not None else None,
        state=state)


# --------------------------------------------------------------------------
# Generator-owned output
# --------------------------------------------------------------------------

def without_phase_4fi1_version_stamp(text: str) -> str:
    """Return a generated page as it stood before the I1 version bump."""
    post, pre = I1_GENERATED_PAGE_EDIT[1], I1_GENERATED_PAGE_EDIT[0]
    if text.count(post) == 0 and text.count(pre) == 1:
        return text
    if text.count(post) != 1 or text.count(pre) != 0:
        raise AssertionError(
            "the generated page does not carry exactly one recognisable "
            "Phase 4F-I1 footer version stamp")
    return text.replace(post, pre, 1)


def is_exactly_the_i1_generated_page(baseline_text: str, live_text: str) -> bool:
    """True only when the page's sole difference is the footer version stamp."""
    try:
        return without_phase_4fi1_version_stamp(live_text) == baseline_text
    except AssertionError:
        return False


def is_exactly_the_i1_sitemap(baseline_text: str, live_text: str) -> bool:
    """True only when the sitemap differs by ``<lastmod>`` values alone.

    The generator moves a page's ``<lastmod>`` exactly when that page's bytes
    moved, so regenerating for the version stamp moves the 31 generated dates
    and carries the app shell's own date forward.  URL set, URL order and every
    other byte of the document must be identical, so an added, removed or
    reordered URL is still reported.
    """
    return _LASTMOD.sub("<lastmod/>", baseline_text) == \
        _LASTMOD.sub("<lastmod/>", live_text)


def is_phase_4fi1_path(path: str) -> bool:
    """True for the paths Phase 4F-I1 is entitled to move outside tests/reports."""
    return path in PHASE_4FI1_FOOTPRINT


def is_exactly_the_i1_transition(path: str, baseline_text: str, live_text: str,
                                 *, bundle: Phase4FI1Bundle | None = None) -> bool:
    """Classify one path's baseline->live difference as exactly the I1 layer.

    ``index.html`` and ``sw.js`` need the validated ``bundle``, because their
    layer is only meaningful as part of the whole transition.
    """
    if path in I1_EDITS:
        if bundle is None:
            return False
        return bundle.is_exactly_the_i1_activation(path, baseline_text, live_text)
    if path in PHASE_4FI1_GENERATED_PAGES:
        return is_exactly_the_i1_generated_page(baseline_text, live_text)
    if path == PHASE_4FI1_SITEMAP_PATH:
        return is_exactly_the_i1_sitemap(baseline_text, live_text)
    return False
