"""Priority 7 Phase 4F-I1 — the final atomic activation, and nothing else.

Phase 4F-H3 closed the content and wording work: 30 lemmas, 34 meanings, 45
patterns, 45 examples, all 45 approved, the surface named ``Verb Patterns`` and
the recognition-only badge reading ``Understand for now``.  Audio stayed
deferred.  Nothing was switched on.

Phase 4F-I1 is the release.  It is deliberately ONE transition across four
kinds of file, and this suite's job is to prove that all four moved together
and that nothing else moved at all:

1. **the runtime** -- ``content/verb-patterns.json``, produced only by the
   approval-gated path (``freeze_editorial`` then
   ``verified_runtime_from_frozen``) from the live approved corpus, at the
   revision the tooling itself derives, serialised the way the tooling writes
   runtime files, and pinned here by SHA-256 and byte length;
2. **the shell** -- ``index.html`` gains ``APP_VERSION`` 8.11 and the single
   production call to the existing shipping consumer, at the one official URL;
3. **the worker** -- ``sw.js`` gains ``popolsku-v66``, the helper and the
   runtime as REQUIRED precache entries, the runtime's own canonical path
   constant, its network-first classification, and its exclusion from the
   cache-first static inventory;
4. **the generated output** -- 31 pages and ``sitemap.xml``, regenerated by
   ``build_pages.py`` because the footer stamps ``APP_VERSION``.

**What I1 is not.**  It is release activation, not content or governance work.
The two editorial files are byte-identical to the baseline, no review event was
added, all 45 rows stay ``approved``, every ``activityEligibility`` array stays
empty, every example stays ``audioEligible: false``, and the audio cache,
storage schema and content-migration revision do not move.

**Negative controls.**  Sections 8 and 9 tamper with each half of the bundle in
turn -- mutated runtime bytes, a wrong revision, a missing or extra runtime, a
private key smuggled back in, a wrong or missing or duplicated loader URL, a
synthetic preview URL, a missing service-worker asset, a wrong classification,
a stale or future version or cache, an H3 wording regression, a corpus or audio
or activity mutation, and every partial dependency bundle -- and prove that the
release gate, the tooling and the phase-owned normaliser each refuse it.

Run:  python3 -m unittest tests.test_priority7_phase4fi1
"""

from __future__ import annotations

import ast
import copy
import functools
import hashlib
import json
import os.path as _i1_os_path
import re
import subprocess
import sys as _i1_sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in _i1_sys.path:
    _i1_sys.path.insert(0, str(ROOT))
_I1_DIR = _i1_os_path.dirname(_i1_os_path.abspath(__file__))
if _I1_DIR not in _i1_sys.path:
    _i1_sys.path.insert(0, _I1_DIR)

import build_pages                                              # noqa: E402
import priority7_tooling as T                                   # noqa: E402
import priority7_phase4fh3_normalizer as H3                     # noqa: E402
import priority7_phase4fi1_normalizer as I1                     # noqa: E402
import test_priority7_phase3fa as F3A                           # noqa: E402

# ---------------------------------------------------------------------------
# The pinned I1 release identity.
# ---------------------------------------------------------------------------

#: Phase 4F-I1 arrived on top of this commit and states every claim against it.
BASELINE_COMMIT = "fe07bd32e0379e6b96c06659063ce30cba8514b3"
BASELINE_TREE = "77b761b100dfda9825efb1ed65302663d23480f1"

CORPUS_PATH = "editorial/verb-pattern-candidates.json"
CONTEXT_PATH = "editorial/priority-7-authoring-context.json"
RUNTIME_PATH = "content/verb-patterns.json"
NORMALISER_PATH = "tests/priority7_phase4fi1_normalizer.py"
MANIFEST_PATH = "reports/priority-7-phase-4fi1-release-manifest.json"
SUMMARY_PATH = (
    "reports/priority-7-phase-4fi1-final-atomic-activation-summary.md")

#: The governance state I1 inherited and must return byte-for-byte unchanged.
CORPUS_SHA256 = (
    "3613a841a992d5848b4c422b247075c15a75efcf69b85070c6fb4168a011ee3f")
CONTEXT_SHA256 = (
    "4ab2bb4b1ae0fa522ec68822731a547cc04a51858beab6e2cd6ff9ae69c79a1c")

LEMMA_COUNT = 30
MEANING_COUNT = 34
PATTERN_COUNT = 45
EXAMPLE_COUNT = 45
APPROVED_COUNT = 45
RECOGNITION_ONLY_COUNT = 4
ACTIVE_PRODUCTION_COUNT = 41
EXPECTED_EVENTS = {
    "reference-verification": 47,
    "editorial-review": 133,
    "correction": 42,
    "product-approval": 89,
}

#: The runtime the approval-gated path produces from the approved corpus.
RUNTIME_SHA256 = (
    "d7911b2a4597147f3f0336c9b0cd154d1bec390d246fc4f33620b7bcf46460ed")
RUNTIME_BYTE_LENGTH = 93600
PATTERN_DATA_REVISION = 1
PATTERN_ID_SET_DIGEST = (
    "be25c5cc78a9a42e0868aef0829c270bb0f42806f1397ae1f08f5639b4372d7d")
LEMMA_ID_SET_DIGEST = (
    "323b26bfd579c48c4c2a6cca00d664468ec64defba71146ffff93c73bbea0ca2")
EXAMPLE_ID_SET_DIGEST = (
    "080b27721cb8184e413129c869f5b53c20d3e4229f7e760170515000771d5a12")

#: The Phase 4F-G1 projection of the pre-H2 29-example corpus.  Obsolete: it
#: was never materialised, and the released runtime must NOT be these bytes.
SUPERSEDED_G1_RUNTIME_SHA256 = (
    "4a42cd6a15b5a52246484aa82bbbf214b3525b88ea11756b0fac937793606671")

#: Private identities that may never appear in a public runtime.
FORBIDDEN_IDENTITIES = (
    "product-owner-001",
    "priority7-reference-analysis",
    "priority7-editorial-review",
    "priority7-editorial-corroboration",
    "priority7-example-generation",
    "native-reviewer-001",
)

#: Envelope and authority markers that may never appear in a public runtime.
FORBIDDEN_ENVELOPE_TOKENS = (
    "artifactStatus", "releaseAuthorized", "runtimeProjection", "reviewState",
    "reviewEvents", "reviewerRef", "authorRef", "sourceRegistry",
    "reviewerRegistry", "authorRegistry", "editorialNotes", "scopeDigest",
    "scopeVersion", "supportingEvidenceDigests", "evidenceRefs", "evidence",
    "internalScope", "repositorySource", "specificationNotice", "origin",
)

#: The one production activation, and the sites that make it exactly one.
RUNTIME_URL = "./content/verb-patterns.json"
URL_CONSTANT = 'const PRIORITY7_RUNTIME_URL = "./content/verb-patterns.json";'
ACTIVATION_CALL = "PP_VERB_PATTERNS.loadRuntimeDocument("

#: Wording Phase 4F-H3 fixed, which I1 must not regress.
H3_TITLE = "Verb Patterns"
H3_BADGE = "Understand for now"
H3_RETIRED_BADGE = "Understand this one"


# ---------------------------------------------------------------------------
# Helpers.  None of them mutates the repository.
# ---------------------------------------------------------------------------

def read(relative: str) -> str:
    return (ROOT / relative).read_text(encoding="utf-8")


def read_bytes(relative: str) -> bytes:
    return (ROOT / relative).read_bytes()


def git(*arguments: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *arguments], cwd=ROOT, capture_output=True, text=True,
        check=False)


def git_blob(reference: str, relative: str) -> bytes | None:
    result = subprocess.run(
        ["git", "show", f"{reference}:{relative}"], cwd=ROOT,
        capture_output=True, check=False)
    return result.stdout if result.returncode == 0 else None


def sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def id_set_digest(identifiers) -> str:
    return hashlib.sha256(
        "\n".join(sorted(identifiers)).encode("utf-8")).hexdigest()


def serialize_runtime(runtime: dict) -> str:
    """The tooling's own file-writing convention, and the digest's definition."""
    return json.dumps(runtime, ensure_ascii=False, indent=2,
                      sort_keys=False) + "\n"


def walk_objects(value):
    if isinstance(value, dict):
        yield value
        for child in value.values():
            yield from walk_objects(child)
    elif isinstance(value, list):
        for child in value:
            yield from walk_objects(child)


def patterns_of(document) -> list:
    return [
        pattern
        for lemma in document["lemmas"]
        for meaning in lemma["meanings"]
        for pattern in meaning["patterns"]
    ]


def examples_of(document) -> list:
    return [example for pattern in patterns_of(document)
            for example in pattern.get("examples", [])]


@functools.lru_cache(maxsize=1)
def repository_context() -> T.ValidationContext:
    """Built once: it indexes every shipped ``data-*.js`` file and is costly."""
    return T._load_context(str(ROOT / CONTEXT_PATH), str(ROOT))


def live_corpus() -> dict:
    return json.loads(read(CORPUS_PATH))


def priority7_corpus(document):
    """Exact released Priority 7 identity slice, independent of ordering."""
    released = released_runtime()
    expected_lemmas = {lemma["id"] for lemma in released["lemmas"]}
    expected_meanings = {
        meaning["id"] for lemma in released["lemmas"]
        for meaning in lemma["meanings"]}
    expected_patterns = {
        pattern["id"] for lemma in released["lemmas"]
        for meaning in lemma["meanings"] for pattern in meaning["patterns"]}
    lemmas = [lemma for lemma in document["lemmas"]
              if lemma.get("id") in expected_lemmas]
    meanings = [meaning for lemma in lemmas for meaning in lemma["meanings"]]
    patterns = [pattern for meaning in meanings for pattern in meaning["patterns"]]
    observed = ([lemma["id"] for lemma in lemmas],
                [meaning["id"] for meaning in meanings],
                [pattern["id"] for pattern in patterns])
    expected = (expected_lemmas, expected_meanings, expected_patterns)
    if any(len(ids) != len(wanted) or set(ids) != wanted
           for ids, wanted in zip(observed, expected)):
        raise AssertionError("historical Priority 7 identity set changed")
    return {**document, "lemmas": lemmas}


@functools.lru_cache(maxsize=1)
def official_runtime() -> dict:
    """The runtime, via the ONLY approval-gated path there is.

    ``freeze_editorial`` validates the whole editorial document against the
    real private context and refuses anything unapproved;
    ``verified_runtime_from_frozen`` validates the complete frozen envelope and
    only then returns the projection.  There is no preview, no lower-level
    assembly and no hand-written file anywhere in this suite.
    """
    frozen = T.freeze_editorial(
        live_corpus(), PATTERN_DATA_REVISION, repository_context())
    return T.verified_runtime_from_frozen(frozen)


def released_runtime() -> dict:
    return json.loads(read(RUNTIME_PATH))


def i1_bundle() -> I1.Phase4FI1Bundle:
    runtime = ROOT / RUNTIME_PATH
    return I1.bundle(
        index_text=read("index.html"),
        worker_text=read("sw.js"),
        runtime_bytes=runtime.read_bytes() if runtime.is_file() else None)


def footprint() -> set[str]:
    """Every path this phase moved, whether committed or still in the tree."""
    touched = {
        line[3:].strip().strip('"')
        for line in git("status", "--porcelain").stdout.splitlines()
        if line.strip()}
    committed = git("diff", "--name-only", BASELINE_COMMIT, "HEAD")
    if committed.returncode == 0:
        touched |= {line.strip() for line in committed.stdout.splitlines()
                    if line.strip()}
    return touched


def strip_comments(source: str) -> str:
    return F3A.strip_javascript_comments(source)


# ---------------------------------------------------------------------------
# 1.  The starting checkpoint
# ---------------------------------------------------------------------------

class StartingCheckpointTests(unittest.TestCase):
    """Exactly the Phase 4F-H3 state, restated before anything is claimed."""

    def test_the_baseline_is_the_declared_commit_and_tree(self):
        self.assertEqual(
            BASELINE_TREE,
            git("rev-parse", f"{BASELINE_COMMIT}^{{tree}}").stdout.strip())

    def test_the_corpus_and_context_are_the_h3_checkpoint_bytes(self):
        self.assertEqual(CORPUS_SHA256, sha256(read_bytes(CORPUS_PATH)))
        self.assertEqual(CONTEXT_SHA256, sha256(read_bytes(CONTEXT_PATH)))

    def test_the_approved_corpus_is_30_34_45_45_and_all_approved(self):
        corpus = priority7_corpus(live_corpus())
        patterns = patterns_of(corpus)
        self.assertEqual(LEMMA_COUNT, len(corpus["lemmas"]))
        self.assertEqual(
            MEANING_COUNT, sum(len(l["meanings"]) for l in corpus["lemmas"]))
        self.assertEqual(PATTERN_COUNT, len(patterns))
        self.assertEqual(EXAMPLE_COUNT, len(examples_of(corpus)))
        self.assertEqual({"approved"},
                         {pattern["reviewState"] for pattern in patterns})
        self.assertEqual(
            APPROVED_COUNT,
            sum(1 for pattern in patterns
                if pattern["reviewState"] == "approved"))

    def test_the_baseline_had_no_runtime_no_loader_and_the_old_markers(self):
        """The state I1 started from, read from the baseline commit itself."""
        self.assertIsNone(git_blob(BASELINE_COMMIT, RUNTIME_PATH))
        index = git_blob(BASELINE_COMMIT, "index.html").decode("utf-8")
        worker = git_blob(BASELINE_COMMIT, "sw.js").decode("utf-8")
        self.assertNotIn("loadRuntimeDocument", index)
        self.assertNotIn(RUNTIME_PATH, index)
        self.assertNotIn(RUNTIME_PATH, worker)
        self.assertIn('const APP_VERSION = "8.10";', index)
        self.assertIn('const CACHE = "popolsku-v65";', worker)
        self.assertEqual(2, index.count("fetch("))

    def test_the_baseline_already_carried_the_h3_wording(self):
        index = git_blob(BASELINE_COMMIT, "index.html").decode("utf-8")
        self.assertEqual("complete", H3.phase_4fh3_layer_state(index))
        self.assertIn(H3_BADGE, index)
        self.assertNotIn(H3_RETIRED_BADGE, index)


# ---------------------------------------------------------------------------
# 2.  The runtime came from the approval-gated path, and is deterministic
# ---------------------------------------------------------------------------

class OfficialRuntimeTests(unittest.TestCase):

    def test_the_released_bytes_are_what_the_approval_gated_path_produces(self):
        self.assertEqual(
            serialize_runtime(official_runtime()).encode("utf-8"),
            read_bytes(RUNTIME_PATH))

    def test_the_released_runtime_matches_the_locked_digest_and_length(self):
        released = read_bytes(RUNTIME_PATH)
        self.assertEqual(RUNTIME_SHA256, sha256(released))
        self.assertEqual(RUNTIME_BYTE_LENGTH, len(released))

    def test_regeneration_is_byte_identical_every_time(self):
        digests = set()
        for _ in range(3):
            frozen = T.freeze_editorial(
                live_corpus(), PATTERN_DATA_REVISION, repository_context())
            runtime = T.verified_runtime_from_frozen(frozen)
            digests.add(sha256(serialize_runtime(runtime).encode("utf-8")))
        self.assertEqual({RUNTIME_SHA256}, digests)

    def test_the_revision_is_derived_mechanically_not_chosen(self):
        """The tooling admits exactly one value, and refuses every other.

        ``freeze_editorial`` takes a previous baseline or none.  No prior
        frozen envelope is retained anywhere in this repository, so ``previous``
        is ``None`` and only revision 1 is admissible.
        """
        self.assertEqual(PATTERN_DATA_REVISION,
                         released_runtime()["patternDataRevision"])
        for rejected in (2, 3, 424242):
            with self.subTest(revision=rejected):
                with self.assertRaises(T.ValidationFailure) as raised:
                    T.freeze_editorial(
                        live_corpus(), rejected, repository_context())
                self.assertIn(
                    "FROZEN_INITIAL_REVISION",
                    {issue.code for issue in raised.exception.issues})
        for invalid in (0, -1):
            with self.subTest(revision=invalid):
                with self.assertRaises(T.ValidationFailure):
                    T.freeze_editorial(
                        live_corpus(), invalid, repository_context())

    def test_no_prior_frozen_priority_7_envelope_is_retained(self):
        retained = sorted(
            str(path.relative_to(ROOT))
            for path in ROOT.rglob("*.json")
            if path.is_file() and "frozen" in path.name.lower()
            and ".git" not in path.parts)
        self.assertEqual(["reports/priority-5-forward-frozen-baseline.json"],
                         retained)

    def test_the_released_runtime_is_not_the_superseded_g1_projection(self):
        self.assertNotEqual(SUPERSEDED_G1_RUNTIME_SHA256,
                            sha256(read_bytes(RUNTIME_PATH)))

    def test_the_identity_digests_are_exact(self):
        runtime = released_runtime()
        patterns = patterns_of(runtime)
        self.assertEqual(
            PATTERN_ID_SET_DIGEST, id_set_digest(p["id"] for p in patterns))
        self.assertEqual(
            LEMMA_ID_SET_DIGEST,
            id_set_digest(lemma["id"] for lemma in runtime["lemmas"]))
        self.assertEqual(
            EXAMPLE_ID_SET_DIGEST,
            id_set_digest(e["id"] for e in examples_of(runtime)))

    def test_pattern_and_lemma_identities_survived_the_content_completion(self):
        """The IDs are the Phase 4F-G1 ones: H2 added examples, not identities."""
        manifest = json.loads(read(
            "reports/priority-7-phase-4fg1-freeze-manifest.json"))
        self.assertEqual(manifest["patternIdSetDigest"], PATTERN_ID_SET_DIGEST)
        self.assertEqual(manifest["lemmaIdSetDigest"], LEMMA_ID_SET_DIGEST)

    def test_the_official_validator_accepts_the_shipping_file(self):
        self.assertEqual(
            [], T.validate_runtime(released_runtime(), T.ValidationContext()))

    def test_the_explicit_validate_runtime_command_accepts_the_shipping_path(self):
        result = subprocess.run(
            [_i1_sys.executable, str(ROOT / "priority7_tooling.py"),
             "validate-runtime", str(ROOT / RUNTIME_PATH),
             "--repository-root", str(ROOT)],
            cwd=ROOT, capture_output=True, text=True, check=False)
        self.assertEqual(0, result.returncode, result.stdout + result.stderr)
        self.assertIn("runtime projection: valid", result.stdout)

    def test_the_release_manifest_agrees_with_the_shipping_file(self):
        manifest = json.loads(read(MANIFEST_PATH))
        self.assertEqual(RUNTIME_SHA256, manifest["runtimeSha256"])
        self.assertEqual(RUNTIME_BYTE_LENGTH, manifest["runtimeByteLength"])
        self.assertEqual(PATTERN_DATA_REVISION,
                         manifest["patternDataRevision"])
        self.assertEqual(BASELINE_COMMIT, manifest["baselineCommit"])
        self.assertEqual(BASELINE_TREE, manifest["baselineTree"])
        self.assertEqual(CORPUS_SHA256, manifest["canonicalSha256"])
        self.assertEqual(
            {"lemmas": LEMMA_COUNT, "meanings": MEANING_COUNT,
             "patterns": PATTERN_COUNT, "examples": EXAMPLE_COUNT,
             "contentRefs": 101, "errorNotes": 24,
             "recognitionOnlyPatterns": RECOGNITION_ONLY_COUNT,
             "activeProductionPatterns": ACTIVE_PRODUCTION_COUNT},
            manifest["counts"])
        self.assertFalse(manifest["pushed"])
        self.assertFalse(manifest["productionRepositoryModified"])


# ---------------------------------------------------------------------------
# 3.  Content correspondence
# ---------------------------------------------------------------------------

class ContentCorrespondenceTests(unittest.TestCase):

    def setUp(self):
        self.runtime = released_runtime()
        self.patterns = patterns_of(self.runtime)

    def test_the_counts_are_30_34_45_45(self):
        self.assertEqual(LEMMA_COUNT, len(self.runtime["lemmas"]))
        self.assertEqual(
            MEANING_COUNT,
            sum(len(l["meanings"]) for l in self.runtime["lemmas"]))
        self.assertEqual(PATTERN_COUNT, len(self.patterns))
        self.assertEqual(EXAMPLE_COUNT, len(examples_of(self.runtime)))

    def test_exactly_one_example_per_pattern_with_no_gap_and_no_extra(self):
        corpus_ids = {
            p["id"] for p in patterns_of(priority7_corpus(live_corpus()))}
        runtime_ids = {p["id"] for p in self.patterns}
        self.assertEqual(set(), corpus_ids - runtime_ids, "missing pattern IDs")
        self.assertEqual(set(), runtime_ids - corpus_ids, "extra pattern IDs")
        counts = {p["id"]: len(p.get("examples", [])) for p in self.patterns}
        self.assertEqual({1}, set(counts.values()))
        self.assertEqual(PATTERN_COUNT, len(counts))

    def test_every_example_carries_polish_english_and_no_audio(self):
        for pattern in self.patterns:
            for example in pattern["examples"]:
                with self.subTest(example=example["id"]):
                    self.assertIsInstance(example["pl"], str)
                    self.assertIsInstance(example["en"], str)
                    self.assertTrue(example["pl"].strip())
                    self.assertTrue(example["en"].strip())
                    self.assertIs(False, example["audioEligible"])
                    self.assertEqual(
                        {"id", "pl", "en", "audioEligible"}, set(example))

    def test_every_pattern_activity_eligibility_is_empty(self):
        self.assertEqual(
            0, sum(len(p["activityEligibility"]) for p in self.patterns))
        self.assertEqual({()},
                         {tuple(p["activityEligibility"]) for p in self.patterns})

    def test_recognition_only_and_active_production_split_is_preserved(self):
        self.assertEqual(
            RECOGNITION_ONLY_COUNT,
            sum(1 for p in self.patterns
                if p["teachingStatus"] == "recognition-only"))
        self.assertEqual(
            ACTIVE_PRODUCTION_COUNT,
            sum(1 for p in self.patterns
                if p["teachingStatus"] == "active-production"))

    def test_the_runtime_examples_are_the_corpus_examples(self):
        corpus = {e["id"]: (e["pl"], e["en"])
                  for e in examples_of(priority7_corpus(live_corpus()))}
        released = {e["id"]: (e["pl"], e["en"])
                    for e in examples_of(self.runtime)}
        self.assertEqual(corpus, released)


# ---------------------------------------------------------------------------
# 4.  Public/private audit of the actual shipping bytes
# ---------------------------------------------------------------------------

class PublicPrivateAuditTests(unittest.TestCase):

    def setUp(self):
        self.text = read(RUNTIME_PATH)
        self.runtime = json.loads(self.text)

    def test_the_envelope_is_the_closed_public_shape(self):
        self.assertEqual(
            {"formatVersion", "patternDataRevision", "lemmas"},
            set(self.runtime))
        self.assertEqual(1, self.runtime["formatVersion"])

    def test_no_private_runtime_key_appears_at_any_depth(self):
        present = {
            key
            for record in walk_objects(self.runtime)
            for key in record
            if key in T.PRIVATE_RUNTIME_KEYS
        }
        self.assertEqual(set(), present)

    def test_no_private_envelope_or_authority_token_appears_in_the_bytes(self):
        for token in FORBIDDEN_ENVELOPE_TOKENS:
            with self.subTest(token=token):
                self.assertNotIn(token, self.text)

    def test_no_reviewer_actor_or_editorial_identity_appears_in_the_bytes(self):
        for identity in FORBIDDEN_IDENTITIES:
            with self.subTest(identity=identity):
                self.assertNotIn(identity, self.text)

    def test_the_private_context_identities_are_all_absent(self):
        """Derived from the real private file, not from a hand-copied list."""
        context = json.loads(read(CONTEXT_PATH))
        identities = set()
        for registry in ("sourceRegistry", "reviewerRegistry", "authorRegistry",
                         "editorialActorRegistry"):
            identities |= set(context.get(registry) or {})
        self.assertTrue(identities, "the audit must have evidence")
        for identity in sorted(identities):
            with self.subTest(identity=identity):
                self.assertNotIn(identity, self.text)

    def test_the_shipping_keys_are_exactly_the_closed_runtime_schema(self):
        self.assertEqual(
            {"id", "canonicalLemma", "reflexive", "aspect", "meanings"},
            {key for lemma in self.runtime["lemmas"] for key in lemma})
        self.assertEqual(
            {"id", "activityEligibility", "cefr", "complements", "contentRefs",
             "errorNotes", "examples", "learnerExplanationEn", "relationType",
             "teachingStatus", "usage"},
            {key for pattern in patterns_of(self.runtime) for key in pattern})

    def test_the_browser_consumer_would_also_refuse_a_private_key(self):
        """The loader's own rejection list mirrors the tooling's, in the file."""
        loader = read("pp-verb-patterns.js")
        for key in ("reviewState", "reviewEvents", "evidence", "reviewerRef"):
            with self.subTest(key=key):
                self.assertIn(f'"{key}"', loader)


# ---------------------------------------------------------------------------
# 5.  The loader activation
# ---------------------------------------------------------------------------

class LoaderActivationTests(unittest.TestCase):

    def setUp(self):
        self.index = read("index.html")
        self.executable = strip_comments(self.index)

    def test_there_is_exactly_one_production_call_site(self):
        self.assertEqual(1, self.index.count("loadRuntimeDocument"))
        self.assertEqual(1, self.executable.count(ACTIVATION_CALL))

    def test_it_uses_the_existing_shipping_consumer_and_no_second_parser(self):
        loader = read("pp-verb-patterns.js")
        self.assertEqual(1, loader.count("loadRuntimeDocument: loadRuntimeDocument"))
        self.assertEqual(git_blob(BASELINE_COMMIT, "pp-verb-patterns.js"),
                         read_bytes("pp-verb-patterns.js"))
        for token in ("JSON.parse(", "acceptRuntimeDocument", "__acceptForTest"):
            with self.subTest(token=token):
                self.assertNotIn(token, strip_comments(
                    self.index[self.index.index("const PRIORITY7_RUNTIME_URL"):
                               self.index.index(
                                   "/* ---------------- grammar (teach -> drill)")]))

    def test_the_official_url_is_named_once_and_no_other_runtime_url_exists(self):
        self.assertEqual(1, self.index.count(URL_CONSTANT))
        self.assertEqual(1, self.index.count(RUNTIME_PATH))
        self.assertEqual(2, self.index.count("PRIORITY7_RUNTIME_URL"))
        for forbidden in ("verb-patterns.preview", "runtime-fixture",
                          "release-runtime-fixture", "tests/fixtures",
                          "editorial/", "verb-pattern-candidates",
                          "verb-patterns.json?", ".preview.json"):
            with self.subTest(token=forbidden):
                self.assertNotIn(forbidden, self.index)

    def test_no_query_switch_storage_or_developer_bypass_can_redirect_it(self):
        """Scoped to the activation itself, and to the shell's own switches.

        The shell reads ``location.search`` elsewhere, for ordinary routing; it
        did so before this phase and still does.  What must not exist is any
        switch that could point the RUNTIME load somewhere else.
        """
        block = self.index[self.index.index("const PRIORITY7_RUNTIME_URL"):]
        block = block[:block.index(
            "/* ---------------- grammar (teach -> drill)")]
        for token in ("URLSearchParams", "location", "searchParams", "?",
                      "loadFixture", "__acceptForTest", "localStorage"):
            with self.subTest(token=token):
                self.assertNotIn(token, strip_comments(block))
        for token in ("URLSearchParams", "searchParams", "?fixture",
                      "loadFixture", "__acceptForTest"):
            with self.subTest(shell_token=token):
                self.assertNotIn(token, self.executable)

    def test_startup_stays_asynchronous_and_non_blocking(self):
        """One extra fetch, no await, and a rejection handler on both legs."""
        self.assertEqual(3, self.index.count("fetch("))
        block = self.index[self.index.index("const PRIORITY7_RUNTIME_URL"):]
        block = block[:block.index(
            "/* ---------------- grammar (teach -> drill)")]
        self.assertNotIn("await", block)
        self.assertIn(").then(pSettleRuntime, ()=>{});", block)
        self.assertIn("if(accepted !== true) return;", block)

    def test_a_failed_load_changes_nothing_and_startup_survives(self):
        """The settle handler cannot run on failure, and holds no side effect.

        Parsed rather than pattern-matched: the guard is the first statement of
        the handler and returns, so every later statement is unreachable for
        any value but ``true``.
        """
        block = self.index[self.index.index("function pSettleRuntime("):]
        block = block[:block.index("\nvoid PP_VERB_PATTERNS")]
        self.assertTrue(block.splitlines()[1].strip().startswith(
            "if(accepted !== true) return;"))
        for forbidden in ("localStorage", "sessionStorage", "indexedDB",
                          "setInterval", "setTimeout", "show(", "history."):
            with self.subTest(token=forbidden):
                self.assertNotIn(forbidden, block)

    def test_the_activation_lives_inside_the_priority_7_block(self):
        start = self.index.index("const P = { li:0, ti:0, topicRef:null")
        end = self.index.index(
            "/* ---------------- grammar (teach -> drill) ---------------- */")
        block = self.index[start:end]
        self.assertIn(URL_CONSTANT, block)
        self.assertIn(ACTIVATION_CALL, block)

    def test_no_other_shipping_source_names_the_runtime_url(self):
        scripts = re.findall(r'<script src="([^"]+)"', self.index)
        self.assertIn("pp-verb-patterns.js", scripts)
        for name in scripts:
            with self.subTest(source=name):
                self.assertNotIn(RUNTIME_PATH, read(name))
        outputs, _, _ = build_pages.build_outputs(str(ROOT))
        for name, text in outputs.items():
            with self.subTest(output=name):
                self.assertNotIn(RUNTIME_PATH, text)
                self.assertNotIn("loadRuntimeDocument", text)


# ---------------------------------------------------------------------------
# 6.  Service worker
# ---------------------------------------------------------------------------

class ServiceWorkerTests(unittest.TestCase):

    def setUp(self):
        self.worker = read("sw.js")
        self.executable = strip_comments(self.worker)
        self.required = F3A.extract_required_assets(self.worker)

    def test_the_helper_and_the_runtime_are_both_required_precache_entries(self):
        self.assertIn("./pp-verb-patterns.js", self.required)
        self.assertIn("./content/verb-patterns.json", self.required)

    def test_the_runtime_has_its_own_canonical_path_constant(self):
        self.assertIn(
            'const PATTERN_RUNTIME_PATH = SCOPE_PATH + "content/verb-patterns.json";',
            self.worker)

    def test_the_runtime_is_classified_and_served_network_first(self):
        self.assertIn(
            '  if (path === PATTERN_RUNTIME_PATH) return "pattern-runtime";',
            self.executable)
        branches = [line for line in self.executable.splitlines()
                    if 'category === "pattern-runtime"' in line]
        self.assertEqual(1, len(branches))
        self.assertIn("networkFirst(", branches[0])
        self.assertNotIn("cacheFirst(", branches[0])

    def test_the_runtime_is_excluded_from_the_cache_first_static_inventory(self):
        self.assertIn("path !== PATTERN_RUNTIME_PATH", self.executable)
        self.assertRegex(
            self.executable,
            r"STATIC_ASSET_PATHS\s*=\s*REQUIRED_ASSETS\s*\.\s*concat\s*"
            r"\(\s*OPTIONAL_ASSETS\s*\)")

    def test_the_static_branch_is_still_cache_first_for_everything_else(self):
        self.assertRegex(
            self.executable,
            r'category\s*===\s*"static"[\s\S]{0,180}?\bcacheFirst\s*\(')

    def test_the_worker_moved_only_by_the_pinned_i1_layer(self):
        baseline = git_blob(BASELINE_COMMIT, "sw.js").decode("utf-8")
        self.assertEqual(baseline, i1_bundle().without_activation("sw.js"))

    def test_unrelated_worker_behaviour_is_untouched(self):
        self.assertIn('const AUDIO_CACHE = "popolsku-audio";', self.worker)
        self.assertNotIn("skipWaiting()", self.executable)
        self.assertNotIn("clients.claim()", self.executable)
        for category in ("root-navigation", "generated-navigation", "data",
                         "audio-manifest", "audio", "static"):
            with self.subTest(category=category):
                self.assertIn(f'"{category}"', self.executable)


# ---------------------------------------------------------------------------
# 7.  Version, cache and the atomic bundle
# ---------------------------------------------------------------------------

class ReleaseMarkerTests(unittest.TestCase):

    def test_the_app_version_advanced_exactly_one_step(self):
        self.assertIn('const APP_VERSION = "8.11";', read("index.html"))
        self.assertNotIn('const APP_VERSION = "8.10";', read("index.html"))
        self.assertEqual((8, 11), F3A.extract_app_version(read("index.html")))

    def test_the_shell_cache_advanced_exactly_one_generation(self):
        self.assertIn('const CACHE = "popolsku-v66";', read("sw.js"))
        self.assertEqual(66, F3A.extract_shell_generation(read("sw.js")))

    def test_the_audio_schema_and_migration_markers_did_not_move(self):
        self.assertIn('const AUDIO_CACHE = "popolsku-audio";', read("sw.js"))
        migrate = read("pp-migrate.js")
        self.assertIn("PP_MIGRATE.SCHEMA_VERSION = 2;", migrate)
        self.assertIn("PP_MIGRATE.CONTENT_MIGRATION_REVISION = 2;", migrate)
        self.assertEqual(git_blob(BASELINE_COMMIT, "pp-migrate.js"),
                         read_bytes("pp-migrate.js"))

    def test_the_phase_3fa_atomic_guard_passes_against_the_live_state(self):
        """The repository's own release rule, run on the shipping files."""
        errors = F3A.release_bundle_errors(
            read("index.html"), read("sw.js"), read("pp-verb-patterns.js"),
            released_runtime(),
            git_blob(BASELINE_COMMIT, "index.html").decode("utf-8"),
            git_blob(BASELINE_COMMIT, "sw.js").decode("utf-8"))
        self.assertEqual([], errors)

    def test_the_loader_and_runtime_format_versions_agree(self):
        loader = read("pp-verb-patterns.js")
        declared = int(re.search(r"\bFORMAT_VERSION\s*=\s*([0-9]+)",
                                 loader).group(1))
        self.assertEqual(declared, released_runtime()["formatVersion"])


# ---------------------------------------------------------------------------
# 8.  Negative controls: the release gate refuses every partial bundle
# ---------------------------------------------------------------------------

class ReleaseGateNegativeControlTests(unittest.TestCase):
    """Each half of the bundle removed in turn, against the live rule."""

    def setUp(self):
        self.baseline_index = git_blob(
            BASELINE_COMMIT, "index.html").decode("utf-8")
        self.baseline_worker = git_blob(
            BASELINE_COMMIT, "sw.js").decode("utf-8")
        self.index = read("index.html")
        self.worker = read("sw.js")
        self.loader = read("pp-verb-patterns.js")
        self.runtime = released_runtime()

    def errors(self, index=None, worker=None, loader=None, runtime=...):
        return F3A.release_bundle_errors(
            self.index if index is None else index,
            self.worker if worker is None else worker,
            self.loader if loader is None else loader,
            self.runtime if runtime is ... else runtime,
            self.baseline_index, self.baseline_worker)

    def test_the_complete_live_bundle_is_the_only_accepted_shape(self):
        self.assertEqual([], self.errors())

    def test_a_missing_runtime_is_refused(self):
        self.assertIn("public runtime missing", self.errors(runtime=None))

    def test_a_missing_loader_activation_is_refused(self):
        self.assertIn("loader activation missing",
                      self.errors(index=self.baseline_index))

    def test_an_old_worker_is_refused(self):
        errors = self.errors(worker=self.baseline_worker)
        self.assertIn("helper missing from required precache", errors)
        self.assertIn("runtime missing from required precache", errors)

    def test_a_worker_missing_only_the_runtime_entry_is_refused(self):
        worker = self.worker.replace('  "./content/verb-patterns.json"\n', "", 1)
        self.assertIn("runtime missing from required precache",
                      self.errors(worker=worker))

    def test_a_worker_missing_only_the_helper_entry_is_refused(self):
        worker = self.worker.replace('  "./pp-verb-patterns.js",\n', "", 1)
        self.assertIn("helper missing from required precache",
                      self.errors(worker=worker))

    def test_a_private_key_in_the_runtime_is_refused(self):
        self.assertIn("public runtime invalid",
                      self.errors(runtime={**self.runtime,
                                           "reviewState": "approved"}))

    def test_a_loader_format_skew_is_refused(self):
        loader = re.sub(r"\bFORMAT_VERSION = 1\b", "FORMAT_VERSION = 2",
                        self.loader, count=1)
        self.assertIn("loader/runtime format mismatch",
                      self.errors(loader=loader))

    def test_a_stale_app_version_is_refused(self):
        index = self.index.replace('const APP_VERSION = "8.11";',
                                   'const APP_VERSION = "8.10";', 1)
        self.assertIn("APP_VERSION did not advance", self.errors(index=index))

    def test_a_stale_shell_cache_is_refused(self):
        worker = self.worker.replace('const CACHE = "popolsku-v66";',
                                     'const CACHE = "popolsku-v65";', 1)
        self.assertIn("shell cache generation did not advance",
                      self.errors(worker=worker))

    def test_the_runtime_swept_into_the_cache_first_inventory_is_refused(self):
        """Dropping the exclusion is not enough; the derivation must survive."""
        worker = self.worker.replace(
            "const STATIC_ASSET_PATHS = REQUIRED_ASSETS.concat(OPTIONAL_ASSETS)",
            "const STATIC_ASSET_PATHS = [].concat(REQUIRED_ASSETS, OPTIONAL_ASSETS)",
            1)
        self.assertIn("required static inventory is not cache-first",
                      self.errors(worker=worker))


# ---------------------------------------------------------------------------
# 9.  Negative controls: the tooling and the normaliser refuse the rest
# ---------------------------------------------------------------------------

class RuntimeAndNormaliserNegativeControlTests(unittest.TestCase):

    def setUp(self):
        self.index = read("index.html")
        self.worker = read("sw.js")
        self.runtime_bytes = read_bytes(RUNTIME_PATH)
        self.baseline_index = git_blob(
            BASELINE_COMMIT, "index.html").decode("utf-8")
        self.baseline_worker = git_blob(
            BASELINE_COMMIT, "sw.js").decode("utf-8")

    def refuses(self, **overrides) -> bool:
        arguments = {"index_text": self.index, "worker_text": self.worker,
                     "runtime_bytes": self.runtime_bytes}
        arguments.update(overrides)
        try:
            I1.bundle(**arguments)
            return False
        except AssertionError:
            return True

    def test_the_live_bundle_and_the_baseline_bundle_both_validate(self):
        self.assertEqual("complete", i1_bundle().state)
        self.assertEqual("absent", I1.bundle(
            index_text=self.baseline_index, worker_text=self.baseline_worker,
            runtime_bytes=None).state)

    def test_a_single_mutated_runtime_byte_is_refused(self):
        mutated = self.runtime_bytes[:1000] + b"X" + self.runtime_bytes[1001:]
        self.assertTrue(self.refuses(runtime_bytes=mutated))

    def test_a_wrong_revision_is_refused_by_digest_and_by_the_tooling(self):
        wrong = copy.deepcopy(released_runtime())
        wrong["patternDataRevision"] = 2
        self.assertTrue(self.refuses(
            runtime_bytes=serialize_runtime(wrong).encode("utf-8")))
        with self.assertRaises(T.ValidationFailure):
            T.freeze_editorial(live_corpus(), 2, repository_context())

    def test_a_reserialised_but_equivalent_runtime_is_refused(self):
        reordered = json.dumps(released_runtime(), ensure_ascii=False,
                               indent=2, sort_keys=True) + "\n"
        self.assertTrue(self.refuses(runtime_bytes=reordered.encode("utf-8")))

    def test_an_extra_private_key_in_the_runtime_is_refused(self):
        smuggled = {**released_runtime(), "reviewState": "approved"}
        self.assertTrue(self.refuses(
            runtime_bytes=serialize_runtime(smuggled).encode("utf-8")))
        self.assertNotEqual(
            [], T.validate_runtime(smuggled, T.ValidationContext()))

    def test_a_missing_runtime_beside_an_activated_shell_is_refused(self):
        self.assertTrue(self.refuses(runtime_bytes=None))

    def test_an_unactivated_shell_beside_a_present_runtime_is_refused(self):
        self.assertTrue(self.refuses(index_text=self.baseline_index))
        self.assertTrue(self.refuses(worker_text=self.baseline_worker))

    def test_each_half_of_each_file_moving_alone_is_refused(self):
        cases = {
            "version without activation":
                {"index_text": self.baseline_index.replace(
                    'const APP_VERSION = "8.10";',
                    'const APP_VERSION = "8.11";', 1)},
            "activation without version":
                {"index_text": self.index.replace(
                    'const APP_VERSION = "8.11";',
                    'const APP_VERSION = "8.10";', 1)},
            "cache without inventory":
                {"worker_text": self.baseline_worker.replace(
                    'const CACHE = "popolsku-v65";',
                    'const CACHE = "popolsku-v66";', 1)},
            "inventory without cache":
                {"worker_text": self.worker.replace(
                    'const CACHE = "popolsku-v66";',
                    'const CACHE = "popolsku-v65";', 1)},
            "classification removed":
                {"worker_text": self.worker.replace(
                    '  if (path === PATTERN_RUNTIME_PATH) return "pattern-runtime";\n',
                    "", 1)},
            "network-first branch removed":
                {"worker_text": self.worker.replace(
                    '  if (category === "pattern-runtime") '
                    '{ networkFirst(e, key, false); return; }\n', "", 1)},
            "static exclusion removed":
                {"worker_text": self.worker.replace(
                    " &&\n                  path !== PATTERN_RUNTIME_PATH", "", 1)},
        }
        for label, overrides in cases.items():
            with self.subTest(case=label):
                self.assertTrue(self.refuses(**overrides), label)

    def test_the_normaliser_hides_no_shell_or_worker_mutation(self):
        bundle = i1_bundle()
        shell_mutations = {
            "future version bump": (
                'const APP_VERSION = "8.11";', 'const APP_VERSION = "8.12";'),
            "duplicate activation": (
                ").then(pSettleRuntime, ()=>{});",
                ").then(pSettleRuntime, ()=>{});\n"
                "void PP_VERB_PATTERNS.loadRuntimeDocument("
                "(u,o)=>fetch(u,o), PRIORITY7_RUNTIME_URL);"),
            "second synthetic preview URL": (
                URL_CONSTANT,
                'const PP_PREVIEW = "./content/verb-patterns.preview.json";\n'
                + URL_CONSTANT),
            "wrong loader URL": (
                URL_CONSTANT,
                'const PRIORITY7_RUNTIME_URL = "./tests/fixtures/priority7/'
                'release-runtime-fixture.json";'),
            "H3 badge regression": (
                '"Understand for now"', '"Understand this one"'),
            "H3 title regression": (
                '<h1 id="pTitle">Verb Patterns</h1>',
                '<h1 id="pTitle">Verb patterns</h1>'),
            "recognition-only guard widened": (
                "if(row.recognitionOnly) main.appendChild(pRecognitionChip());",
                "main.appendChild(pRecognitionChip());"),
            "unrelated shell edit": (
                'blurb:"Which case does this verb take?"',
                'blurb:"Which case?"'),
        }
        for label, (old, new) in shell_mutations.items():
            with self.subTest(mutation=label):
                self.assertEqual(1, self.index.count(old), label)
                tampered = self.index.replace(old, new, 1)
                self.assertFalse(
                    bundle.is_exactly_the_i1_activation(
                        "index.html", self.baseline_index, tampered), label)

        worker_mutations = {
            "future cache bump": (
                'const CACHE = "popolsku-v66";',
                'const CACHE = "popolsku-v67";'),
            "audio cache renamed": (
                'const AUDIO_CACHE = "popolsku-audio";',
                'const AUDIO_CACHE = "popolsku-audio-v2";'),
            "an unrelated required asset dropped": (
                '  "./data-a1.js",\n', ""),
        }
        for label, (old, new) in worker_mutations.items():
            with self.subTest(mutation=label):
                self.assertEqual(1, self.worker.count(old), label)
                tampered = self.worker.replace(old, new, 1)
                self.assertFalse(
                    bundle.is_exactly_the_i1_activation(
                        "sw.js", self.baseline_worker, tampered), label)

    def test_the_normaliser_hides_no_generated_page_or_sitemap_mutation(self):
        page = "guide/index.html"
        baseline_page = git_blob(BASELINE_COMMIT, page).decode("utf-8")
        self.assertTrue(I1.is_exactly_the_i1_generated_page(
            baseline_page, read(page)))
        tampered = read(page).replace("Explore more Polish", "Explore Polish", 1)
        self.assertFalse(I1.is_exactly_the_i1_generated_page(
            baseline_page, tampered))

        baseline_sitemap = git_blob(BASELINE_COMMIT, "sitemap.xml").decode("utf-8")
        self.assertTrue(I1.is_exactly_the_i1_sitemap(
            baseline_sitemap, read("sitemap.xml")))
        for label, tampered in {
            "a URL removed": read("sitemap.xml").replace(
                "  <url>\n    <loc>https://popolsku.app/grammar/wolacz-vocative/"
                "</loc>\n", "  <url>\n", 1),
            "a URL renamed": read("sitemap.xml").replace(
                "https://popolsku.app/grammar/wolacz-vocative/",
                "https://popolsku.app/grammar/wolacz/", 1),
        }.items():
            with self.subTest(mutation=label):
                self.assertFalse(I1.is_exactly_the_i1_sitemap(
                    baseline_sitemap, tampered), label)

    def test_a_partly_applied_layer_is_refused_not_half_reverted(self):
        for index, (pre, post) in enumerate(I1.I1_INDEX_EDITS):
            with self.subTest(site=f"index.html #{index}"):
                partial = self.index.replace(post, pre, 1)
                self.assertEqual("partial",
                                 I1.phase_4fi1_file_state("index.html", partial))
                self.assertTrue(self.refuses(index_text=partial))
        for index, (pre, post) in enumerate(I1.I1_WORKER_EDITS):
            with self.subTest(site=f"sw.js #{index}"):
                partial = self.worker.replace(post, pre, 1)
                self.assertEqual("partial",
                                 I1.phase_4fi1_file_state("sw.js", partial))
                self.assertTrue(self.refuses(worker_text=partial))

    def test_the_revert_and_the_apply_are_exact_inverses(self):
        bundle = i1_bundle()
        self.assertEqual(self.baseline_index,
                         bundle.without_activation("index.html"))
        self.assertEqual(self.baseline_worker,
                         bundle.without_activation("sw.js"))
        self.assertEqual(self.index,
                         bundle.with_activation("index.html", self.baseline_index))
        self.assertEqual(self.worker,
                         bundle.with_activation("sw.js", self.baseline_worker))

    def test_the_normaliser_opens_no_file_and_runs_no_subprocess(self):
        """A pure text module, so importing it from any suite is inert."""
        tree = ast.parse(read(NORMALISER_PATH))
        called = {
            node.func.id for node in ast.walk(tree)
            if isinstance(node, ast.Call) and isinstance(node.func, ast.Name)}
        for forbidden in ("open", "exec", "eval", "compile", "__import__"):
            with self.subTest(name=forbidden):
                self.assertNotIn(forbidden, called)
        imported = {
            alias.name.split(".")[0]
            for node in ast.walk(tree)
            if isinstance(node, ast.Import) for alias in node.names}
        imported |= {
            node.module.split(".")[0] for node in ast.walk(tree)
            if isinstance(node, ast.ImportFrom) and node.module}
        self.assertEqual({"dataclasses", "hashlib", "re", "__future__"}, imported)


# ---------------------------------------------------------------------------
# 10.  Phase 4F-H3 wording, and recognition-only behaviour
# ---------------------------------------------------------------------------

class WordingAndRecognitionTests(unittest.TestCase):

    def setUp(self):
        self.index = read("index.html")

    def test_the_h3_layer_is_still_complete_and_unregressed(self):
        self.assertEqual("complete", H3.phase_4fh3_layer_state(self.index))
        for site in H3.H3_WORDING_EDITS:
            with self.subTest(site=site[1].strip()):
                self.assertEqual(1, self.index.count(site[1]))
                self.assertEqual(0, self.index.count(site[0]))

    def test_the_retired_badge_is_gone_and_the_current_one_is_present(self):
        self.assertNotIn(H3_RETIRED_BADGE, self.index)
        self.assertIn(H3_BADGE, self.index)

    def test_the_sentence_case_phrases_h3_left_alone_are_still_untouched(self):
        for relative, snippet, occurrences in H3.H3_UNCHANGED_PHRASES:
            with self.subTest(snippet=snippet):
                self.assertEqual(occurrences, read(relative).count(snippet))

    def test_recognition_only_rendering_is_unchanged(self):
        self.assertIn(
            "if(row.recognitionOnly) main.appendChild(pRecognitionChip());",
            self.index)
        self.assertIn(
            '"usage-badge u-recognition vp-recognition", "Understand for now"',
            self.index)

    def test_the_shell_moved_only_by_the_pinned_i1_layer(self):
        self.assertEqual(git_blob(BASELINE_COMMIT, "index.html").decode("utf-8"),
                         i1_bundle().without_activation("index.html"))


# ---------------------------------------------------------------------------
# 11.  Governance, audio and activity are untouched
# ---------------------------------------------------------------------------

class InvariantTests(unittest.TestCase):

    def test_the_two_editorial_files_are_byte_identical_to_the_baseline(self):
        for relative, expected in ((CORPUS_PATH, CORPUS_SHA256),
                                   (CONTEXT_PATH, CONTEXT_SHA256)):
            with self.subTest(path=relative):
                self.assertEqual(git_blob(BASELINE_COMMIT, relative),
                                 read_bytes(relative))
                self.assertEqual(expected, sha256(read_bytes(relative)))

    def test_no_review_event_was_added_and_all_45_stay_approved(self):
        patterns = patterns_of(live_corpus())
        counts: dict[str, int] = {}
        for pattern in patterns:
            for event in pattern["reviewEvents"]:
                counts[event["kind"]] = counts.get(event["kind"], 0) + 1
        self.assertEqual(EXPECTED_EVENTS, counts)
        self.assertEqual({"approved"},
                         {pattern["reviewState"] for pattern in patterns})

    def test_no_audio_file_rule_or_manifest_moved(self):
        for relative in ("pp_audio_rule.py", "pp-usage.js",
                         "audio-manifest.json"):
            with self.subTest(path=relative):
                self.assertEqual(git_blob(BASELINE_COMMIT, relative),
                                 read_bytes(relative))
        changed = git("diff", "--name-only", BASELINE_COMMIT, "--", "audio")
        self.assertEqual("", changed.stdout.strip())

    def test_no_activity_or_audio_eligibility_moved_anywhere(self):
        for document in (live_corpus(), released_runtime()):
            patterns = patterns_of(document)
            self.assertEqual(
                0, sum(len(p["activityEligibility"]) for p in patterns))
            self.assertEqual(
                0, sum(1 for p in patterns for e in p.get("examples", [])
                       if e["audioEligible"] is True))

    def test_the_shipping_helpers_and_data_files_are_untouched(self):
        for relative in (
            "pp-verb-patterns.js", "pp-usage.js", "pp-answer.js",
            "pp-distractor.js", "pp-migrate.js", "manifest.json", "robots.txt",
            "data-a1.js", "data-a2.js", "data-b1.js", "data-grammar.js",
            "data-podcasts.js", "data-scenarios.js", "data-verbs.js",
            "priority7_tooling.py", "validate_content.py", "build_pages.py",
            "verify_audio.py", "generate_audio.py", "CNAME",
        ):
            with self.subTest(path=relative):
                self.assertEqual(git_blob(BASELINE_COMMIT, relative),
                                 read_bytes(relative))

    def test_the_editorial_validator_still_accepts_the_untouched_corpus(self):
        self.assertEqual(
            [], T.validate_editorial(live_corpus(), repository_context()))


# ---------------------------------------------------------------------------
# 12.  Generated output and the phase footprint
# ---------------------------------------------------------------------------

class GeneratedOutputTests(unittest.TestCase):

    def test_the_committed_generated_output_is_current(self):
        outputs, _, _ = build_pages.build_outputs(str(ROOT))
        self.assertEqual([], build_pages.drift_report(outputs, str(ROOT)))

    def test_the_generator_stamps_the_new_version_into_every_page(self):
        self.assertEqual("8.11", build_pages.read_app_version())
        outputs, _, _ = build_pages.build_outputs(str(ROOT))
        stamped = sorted(name for name in outputs
                         if "&middot; v8.11 &middot;" in outputs[name])
        self.assertEqual(sorted(I1.PHASE_4FI1_GENERATED_PAGES), stamped)
        for name in stamped:
            with self.subTest(page=name):
                self.assertEqual(1, outputs[name].count("&middot; v8.11 &middot;"))
                self.assertEqual(0, outputs[name].count("&middot; v8.10 &middot;"))
        # The two hub redirect stubs carry no footer at all, so the version
        # bump cannot move them, and it did not.
        for stub in ("grammar/index.html", "vocabulary/index.html"):
            with self.subTest(page=stub):
                self.assertNotIn("&middot; v", outputs[stub])
                self.assertEqual(git_blob(BASELINE_COMMIT, stub),
                                 read_bytes(stub))

    def test_every_generated_page_moved_by_exactly_the_version_stamp(self):
        for relative in I1.PHASE_4FI1_GENERATED_PAGES:
            with self.subTest(page=relative):
                baseline = git_blob(BASELINE_COMMIT, relative)
                self.assertIsNotNone(baseline, relative)
                self.assertTrue(I1.is_exactly_the_i1_generated_page(
                    baseline.decode("utf-8"), read(relative)), relative)

    def test_the_sitemap_moved_only_by_lastmod_and_keeps_its_32_urls(self):
        baseline = git_blob(BASELINE_COMMIT, "sitemap.xml").decode("utf-8")
        live = read("sitemap.xml")
        self.assertTrue(I1.is_exactly_the_i1_sitemap(baseline, live))
        self.assertEqual(re.findall(r"<loc>([^<]+)</loc>", baseline),
                         re.findall(r"<loc>([^<]+)</loc>", live))
        self.assertEqual(32, live.count("<loc>"))
        moved = sum(
            1 for before, after in zip(
                re.findall(r"<lastmod>([^<]+)</lastmod>", baseline),
                re.findall(r"<lastmod>([^<]+)</lastmod>", live))
            if before != after)
        self.assertEqual(len(I1.PHASE_4FI1_GENERATED_PAGES), moved)

    def test_the_generator_itself_did_not_move(self):
        self.assertEqual(git_blob(BASELINE_COMMIT, "build_pages.py"),
                         read_bytes("build_pages.py"))


class PhaseFootprintTests(unittest.TestCase):

    def test_the_footprint_is_the_release_bundle_plus_tests_and_reports(self):
        touched = footprint()
        self.assertTrue(touched, "the footprint guard must have evidence")
        unexpected = sorted(
            path for path in touched
            if not path.startswith(("tests/", "reports/"))
            and not I1.is_phase_4fi1_path(path.rstrip("/"))
            and path.rstrip("/") != "content")
        self.assertEqual([], unexpected, f"unexpected footprint: {unexpected}")

    def test_no_editorial_path_is_in_the_footprint(self):
        self.assertEqual(
            [], sorted(path for path in footprint()
                       if path.startswith("editorial/")))

    def test_the_phase_owned_artifacts_exist(self):
        for relative in (NORMALISER_PATH, MANIFEST_PATH, SUMMARY_PATH,
                         "tests/test_priority7_phase4fi1.py", RUNTIME_PATH):
            with self.subTest(path=relative):
                self.assertTrue((ROOT / relative).exists(), relative)

    def test_the_content_directory_holds_exactly_the_released_runtime(self):
        present = sorted(
            str(path.relative_to(ROOT))
            for path in (ROOT / "content").rglob("*") if path.is_file())
        self.assertEqual([RUNTIME_PATH], present)

    def test_no_remote_exists_so_nothing_can_have_been_pushed(self):
        """A workflow invariant, stated without any machine-specific path."""
        self.assertEqual("", git("remote").stdout.strip())

    def test_no_phase_artifact_records_a_value_it_can_only_learn_later(self):
        """The candidate must be a fixed point: building it changes nothing.

        A tracked artifact may name the baseline commit and the baseline tree,
        because both exist before this candidate does.  It may NOT name the
        scratch commit or the candidate's own tree: those are functions of the
        finished candidate, so writing one into a tracked file forces a rewrite
        after the scratch is built -- which changes the very tree the scratch
        was meant to reproduce, and makes the workspace and the scratch differ
        by construction.

        Enforced structurally, over every Git-object-shaped token: exactly two
        40-hex values are admissible anywhere in the phase's own artifacts, and
        they are the two declared inputs.  SHA-256 content digests are 64 hex
        characters and are unaffected, because a 40-hex run inside a 64-hex run
        has no word boundary around it.
        """
        allowed = {BASELINE_COMMIT, BASELINE_TREE}
        for relative in (SUMMARY_PATH, MANIFEST_PATH, NORMALISER_PATH,
                         "tests/test_priority7_phase4fi1.py"):
            with self.subTest(path=relative):
                found = set(re.findall(r"\b[0-9a-f]{40}\b", read(relative)))
                self.assertEqual(
                    set(), found - allowed,
                    f"{relative} records a Git object it can only learn after "
                    f"the candidate is built: {sorted(found - allowed)}")

    def test_the_declared_baseline_inputs_really_are_inputs(self):
        """Both admissible hashes resolve, and both predate this candidate.

        Read-only: it resolves objects and lists paths, and writes nothing --
        not the index, not a tree object, not a file.
        """
        self.assertEqual(
            BASELINE_TREE,
            git("rev-parse", f"{BASELINE_COMMIT}^{{tree}}").stdout.strip())
        # The candidate really does move the tree away from that baseline, so
        # the two admissible hashes cannot be describing this candidate.
        self.assertIsNone(git_blob(BASELINE_COMMIT, RUNTIME_PATH))
        self.assertTrue((ROOT / RUNTIME_PATH).is_file())


if __name__ == "__main__":
    unittest.main()
